"""Tests for vaibify.reproducibility.dependencyPinning."""

import subprocess
import sys
from unittest import mock

import pytest

from vaibify.reproducibility.dependencyPinning import (
    fbIsUvAvailable,
    flistResolveLockCompileCommand,
    flistVerifyRequirementsLock,
    fnGenerateRequirementsLock,
)


_S_VALID_LOCK = (
    "# This file was autogenerated by uv\n"
    "click==8.1.7 \\\n"
    "    --hash=sha256:" + ("a" * 64) + "\n"
    "pyyaml==6.0.1 \\\n"
    "    --hash=sha256:" + ("b" * 64) + "\n"
)

_S_UNHASHED_LOCK = (
    "click==8.1.7 \\\n"
    "    --hash=sha256:" + ("a" * 64) + "\n"
    "pyyaml==6.0.1\n"
)


def _fnFakeRunWriteLock(sLockBody):
    """Build a subprocess.run replacement that writes a lockfile."""

    def fnFake(listCommand, cwd, capture_output, text, timeout=None):
        from pathlib import Path

        pathOut = Path(cwd) / "requirements.lock"
        pathOut.write_text(sLockBody)
        result = mock.Mock()
        result.returncode = 0
        result.stdout = ""
        result.stderr = ""
        return result

    return fnFake


def test_fnGenerateRequirementsLock_pyproject_happy_path(tmp_path):
    (tmp_path / "pyproject.toml").write_text(
        '[project]\nname = "demo"\ndependencies = ["click"]\n'
    )
    sModule = "vaibify.reproducibility.dependencyPinning"
    with mock.patch(sModule + ".shutil.which", return_value="/u/uv"):
        with mock.patch(
            sModule + ".subprocess.run",
            side_effect=_fnFakeRunWriteLock(_S_VALID_LOCK),
        ) as mockRun:
            fnGenerateRequirementsLock(str(tmp_path))

    pathLock = tmp_path / "requirements.lock"
    assert pathLock.is_file()
    listCommand = mockRun.call_args.args[0]
    assert listCommand[0:4] == ["uv", "pip", "compile",
                                "--generate-hashes"]
    assert "pyproject.toml" in listCommand


def test_fnGenerateRequirementsLock_requirements_in_happy_path(
    tmp_path,
):
    (tmp_path / "requirements.in").write_text("click\npyyaml\n")
    sModule = "vaibify.reproducibility.dependencyPinning"
    with mock.patch(sModule + ".shutil.which", return_value="/u/uv"):
        with mock.patch(
            sModule + ".subprocess.run",
            side_effect=_fnFakeRunWriteLock(_S_VALID_LOCK),
        ) as mockRun:
            fnGenerateRequirementsLock(str(tmp_path))

    listCommand = mockRun.call_args.args[0]
    assert "requirements.in" in listCommand
    assert "pyproject.toml" not in listCommand


def test_fnGenerateRequirementsLock_requirements_txt_fallback(
    tmp_path,
):
    (tmp_path / "requirements.txt").write_text("click\npyyaml\n")
    sModule = "vaibify.reproducibility.dependencyPinning"
    with mock.patch(sModule + ".shutil.which", return_value="/u/uv"):
        with mock.patch(
            sModule + ".subprocess.run",
            side_effect=_fnFakeRunWriteLock(_S_VALID_LOCK),
        ) as mockRun:
            fnGenerateRequirementsLock(str(tmp_path))

    listCommand = mockRun.call_args.args[0]
    assert "requirements.txt" in listCommand


def test_fnGenerateRequirementsLock_requirements_in_beats_txt(
    tmp_path,
):
    (tmp_path / "requirements.in").write_text("click\n")
    (tmp_path / "requirements.txt").write_text("click==1.0\n")
    sModule = "vaibify.reproducibility.dependencyPinning"
    with mock.patch(sModule + ".shutil.which", return_value="/u/uv"):
        with mock.patch(
            sModule + ".subprocess.run",
            side_effect=_fnFakeRunWriteLock(_S_VALID_LOCK),
        ) as mockRun:
            fnGenerateRequirementsLock(str(tmp_path))

    listCommand = mockRun.call_args.args[0]
    assert "requirements.in" in listCommand
    assert "requirements.txt" not in listCommand


def test_fnGenerateRequirementsLock_pyproject_takes_precedence(
    tmp_path,
):
    (tmp_path / "pyproject.toml").write_text(
        '[project]\nname = "demo"\n'
    )
    (tmp_path / "requirements.in").write_text("click\n")
    sModule = "vaibify.reproducibility.dependencyPinning"
    with mock.patch(sModule + ".shutil.which", return_value="/u/uv"):
        with mock.patch(
            sModule + ".subprocess.run",
            side_effect=_fnFakeRunWriteLock(_S_VALID_LOCK),
        ) as mockRun:
            fnGenerateRequirementsLock(str(tmp_path))

    listCommand = mockRun.call_args.args[0]
    assert "pyproject.toml" in listCommand
    assert "requirements.in" not in listCommand


def test_fnGenerateRequirementsLock_no_input_files(tmp_path):
    sModule = "vaibify.reproducibility.dependencyPinning"
    with mock.patch(sModule + ".shutil.which", return_value="/u/uv"):
        with pytest.raises(FileNotFoundError) as excInfo:
            fnGenerateRequirementsLock(str(tmp_path))

    sMessage = str(excInfo.value)
    assert "pyproject.toml" in sMessage
    assert "requirements.in" in sMessage


def test_fnGenerateRequirementsLock_no_generator_actionable_message(
    tmp_path,
):
    (tmp_path / "pyproject.toml").write_text("[project]\n")
    sModule = "vaibify.reproducibility.dependencyPinning"
    with mock.patch(sModule + ".shutil.which", return_value=None):
        with mock.patch(
            sModule + "._fbModuleAvailable", return_value=False,
        ):
            with pytest.raises(FileNotFoundError) as excInfo:
                fnGenerateRequirementsLock(str(tmp_path))

    sMessage = str(excInfo.value)
    assert "uv" in sMessage
    assert "https://docs.astral.sh/uv/" in sMessage
    assert "pip-tools" in sMessage


def test_resolve_compile_command_prefers_path_uv():
    sModule = "vaibify.reproducibility.dependencyPinning"
    with mock.patch(sModule + ".shutil.which", return_value="/u/uv"):
        assert flistResolveLockCompileCommand() == [
            "uv", "pip", "compile",
        ]


def test_resolve_compile_command_falls_back_to_uv_module():
    sModule = "vaibify.reproducibility.dependencyPinning"
    with mock.patch(sModule + ".shutil.which", return_value=None):
        with mock.patch(
            sModule + "._fbModuleAvailable",
            side_effect=lambda sName: sName == "uv",
        ):
            assert flistResolveLockCompileCommand() == [
                sys.executable, "-m", "uv", "pip", "compile",
            ]


def test_resolve_compile_command_falls_back_to_piptools():
    sModule = "vaibify.reproducibility.dependencyPinning"
    with mock.patch(sModule + ".shutil.which", return_value=None):
        with mock.patch(
            sModule + "._fbModuleAvailable",
            side_effect=lambda sName: sName == "piptools",
        ):
            assert flistResolveLockCompileCommand() == [
                sys.executable, "-m", "piptools", "compile",
            ]


def test_resolve_compile_command_empty_when_nothing_installed():
    sModule = "vaibify.reproducibility.dependencyPinning"
    with mock.patch(sModule + ".shutil.which", return_value=None):
        with mock.patch(
            sModule + "._fbModuleAvailable", return_value=False,
        ):
            assert flistResolveLockCompileCommand() == []


def test_generate_lock_uses_piptools_fallback_with_hashes(tmp_path):
    """pip-tools fallback still compiles with --generate-hashes."""
    (tmp_path / "pyproject.toml").write_text("[project]\n")
    sModule = "vaibify.reproducibility.dependencyPinning"
    with mock.patch(sModule + ".shutil.which", return_value=None):
        with mock.patch(
            sModule + "._fbModuleAvailable",
            side_effect=lambda sName: sName == "piptools",
        ):
            with mock.patch(
                sModule + ".subprocess.run",
                side_effect=_fnFakeRunWriteLock(_S_VALID_LOCK),
            ) as mockRun:
                fnGenerateRequirementsLock(str(tmp_path))

    listCommand = mockRun.call_args.args[0]
    assert listCommand[:3] == [sys.executable, "-m", "piptools"]
    assert "--generate-hashes" in listCommand
    assert (tmp_path / "requirements.lock").is_file()


def test_fnGenerateRequirementsLock_compile_failure(tmp_path):
    (tmp_path / "pyproject.toml").write_text("[project]\n")
    sModule = "vaibify.reproducibility.dependencyPinning"
    resultFail = mock.Mock()
    resultFail.returncode = 2
    resultFail.stdout = ""
    resultFail.stderr = "error: could not resolve dependency 'foo'"
    with mock.patch(sModule + ".shutil.which", return_value="/u/uv"):
        with mock.patch(
            sModule + ".subprocess.run", return_value=resultFail
        ):
            with pytest.raises(
                subprocess.CalledProcessError
            ) as excInfo:
                fnGenerateRequirementsLock(str(tmp_path))

    assert excInfo.value.returncode == 2
    assert "could not resolve" in excInfo.value.stderr


def test_flistVerifyRequirementsLock_happy_path(tmp_path):
    (tmp_path / "requirements.lock").write_text(_S_VALID_LOCK)

    listIssues = flistVerifyRequirementsLock(str(tmp_path))

    assert listIssues == []


def test_flistVerifyRequirementsLock_missing_file(tmp_path):
    listIssues = flistVerifyRequirementsLock(str(tmp_path))

    assert len(listIssues) == 1
    assert "requirements.lock not found" in listIssues[0]


def test_flistVerifyRequirementsLock_unhashed_entry(tmp_path):
    (tmp_path / "requirements.lock").write_text(_S_UNHASHED_LOCK)

    listIssues = flistVerifyRequirementsLock(str(tmp_path))

    assert len(listIssues) == 1
    assert "pyyaml" in listIssues[0]
    assert "--hash=sha256" in listIssues[0]


def test_fbIsUvAvailable_reflects_shutil_which():
    sModule = "vaibify.reproducibility.dependencyPinning"
    with mock.patch(sModule + ".shutil.which", return_value="/u/uv"):
        assert fbIsUvAvailable() is True
    with mock.patch(sModule + ".shutil.which", return_value=None):
        assert fbIsUvAvailable() is False


def test_uv_compile_timeout_raises_called_process_error(tmp_path):
    """A ``TimeoutExpired`` from uv must surface as a redacted error.

    Regression test for Wave-4 hardening: a network-stalled uv index
    fetch must not hang the host backend. The timeout is mapped to
    ``CalledProcessError`` (rc=124) so the upstream caller sees a
    uniform failure shape regardless of whether uv exited non-zero or
    was killed by the wall clock.
    """
    (tmp_path / "pyproject.toml").write_text("[project]\n")
    sModule = "vaibify.reproducibility.dependencyPinning"
    with mock.patch(sModule + ".shutil.which", return_value="/u/uv"):
        with mock.patch(
            sModule + ".subprocess.run",
            side_effect=subprocess.TimeoutExpired(
                cmd=["uv"], timeout=120,
            ),
        ):
            with pytest.raises(
                subprocess.CalledProcessError,
            ) as excInfo:
                fnGenerateRequirementsLock(str(tmp_path))
    assert excInfo.value.returncode == 124
    assert "timed out" in excInfo.value.stderr.lower()


def test_uv_disappeared_race_yields_file_not_found(tmp_path):
    """If uv disappears between availability check and run, we tell the user.

    The race window between :func:`fbIsUvAvailable` and the
    :func:`subprocess.run` invocation can yield ``FileNotFoundError``;
    the hardening converts this into a clean ``FileNotFoundError``
    with the install URL — same UX as the up-front "uv missing" arm.
    """
    (tmp_path / "pyproject.toml").write_text("[project]\n")
    sModule = "vaibify.reproducibility.dependencyPinning"
    with mock.patch(sModule + ".shutil.which", return_value="/u/uv"):
        with mock.patch(
            sModule + ".subprocess.run",
            side_effect=FileNotFoundError("[Errno 2] uv vanished"),
        ):
            with pytest.raises(FileNotFoundError) as excInfo:
                fnGenerateRequirementsLock(str(tmp_path))
    sMessage = str(excInfo.value)
    assert "uv" in sMessage
    assert "https://docs.astral.sh/uv/" in sMessage


def test_uv_compile_failure_redacts_credential_url(tmp_path):
    """uv stderr containing a ``user:tok@`` URL must be scrubbed.

    Regression test for the Wave-1 hardening: ``_fnRunUvCompile``
    pipes uv's stderr through ``fsRedactStderr`` before embedding it
    in ``CalledProcessError`` so a misconfigured index URL with
    embedded credentials cannot leak to logs or user-facing toasts.
    """
    (tmp_path / "pyproject.toml").write_text("[project]\n")
    sModule = "vaibify.reproducibility.dependencyPinning"
    sLeakyStderr = (
        "could not connect to https://user:tok123@example.com/index/"
    )
    resultFail = mock.Mock()
    resultFail.returncode = 1
    resultFail.stdout = ""
    resultFail.stderr = sLeakyStderr
    with mock.patch(sModule + ".shutil.which", return_value="/u/uv"):
        with mock.patch(
            sModule + ".subprocess.run", return_value=resultFail,
        ):
            with pytest.raises(
                subprocess.CalledProcessError,
            ) as excInfo:
                fnGenerateRequirementsLock(str(tmp_path))
    assert "tok123" not in excInfo.value.stderr
    assert "user:tok123" not in excInfo.value.stderr
    assert "<redacted>" in excInfo.value.stderr


# ---------------------------------------------------------------------
# The container lane pins what the CONTAINER runs (2026-09-13)
# ---------------------------------------------------------------------


class _ContainerAnsweringProbes:
    """A container-rooted adapter whose probes answer from a table."""

    def __init__(self, pathRoot, sVersionLine, sFreeze, iProbeExit=0):
        self.pathRoot = pathRoot
        self.sVersionLine = sVersionLine
        self.sFreeze = sFreeze
        self.iProbeExit = iProbeExit
        self.dictWritten = {}
        self.listCommands = []

    def fsLocalRootOrNone(self):
        return None

    def fbIsFile(self, sRelPath):
        return (self.pathRoot / sRelPath).is_file()

    def fsReadText(self, sRelPath):
        return (self.pathRoot / sRelPath).read_text()

    def fnWriteTextAtomic(self, sRelPath, sText):
        self.dictWritten[sRelPath] = sText

    def ftRunCommand(self, saCommand, fTimeoutSeconds):
        self.listCommands.append(list(saCommand))
        if self.iProbeExit:
            return self.iProbeExit, "", "no such container"
        if "freeze" in saCommand:
            return 0, self.sFreeze, ""
        return 0, self.sVersionLine, ""


_S_FREEZE = (
    "numpy==2.5.2\n"
    "scipy==1.18.1\n"
    "-e git+https://example.invalid/tool.git#egg=tool\n"
    "vaibify @ file:///workspace/vaibify\n"
    "# a comment\n"
    "matplotlib==3.11.1\n"
)


def _ffnFakeRunRecordingStaging(sLockBody, dictSeen):
    """A subprocess.run replacement that records what the staging dir held."""

    def fnFake(listCommand, cwd, capture_output, text, timeout=None):
        from pathlib import Path

        dictSeen["listCommand"] = list(listCommand)
        pathConstraints = Path(cwd) / "constraints.txt"
        dictSeen["sConstraints"] = (
            pathConstraints.read_text() if pathConstraints.is_file() else None
        )
        (Path(cwd) / "requirements.lock").write_text(sLockBody)
        result = mock.Mock()
        result.returncode = 0
        result.stdout = ""
        result.stderr = ""
        return result

    return fnFake


@pytest.mark.falsification
def test_a_container_lock_is_constrained_to_what_the_container_runs(tmp_path):
    """The resolver is handed the container's installed set, interpreter
    and platform; a host with a different Python cannot steer the pins.

    Kills: compiling without the constraints, which pins whatever the
    host's own interpreter would install today.
    """
    (tmp_path / "requirements.txt").write_text("numpy>=1.26\nscipy>=1.10\n")
    filesRepo = _ContainerAnsweringProbes(tmp_path, "3 12 x86_64", _S_FREEZE)
    dictSeen = {}
    sModule = "vaibify.reproducibility.dependencyPinning"
    with mock.patch(sModule + ".shutil.which", return_value="/u/uv"):
        with mock.patch(
            sModule + ".subprocess.run",
            side_effect=_ffnFakeRunRecordingStaging(_S_VALID_LOCK, dictSeen),
        ):
            fnGenerateRequirementsLock(filesRepo)
    assert filesRepo.dictWritten["requirements.lock"] == _S_VALID_LOCK
    listCommand = dictSeen["listCommand"]
    assert listCommand[:4] == ["uv", "pip", "compile", "--generate-hashes"]
    assert listCommand[listCommand.index("-c") + 1] == "constraints.txt"
    assert listCommand[listCommand.index("--python-version") + 1] == "3.12"
    assert listCommand[listCommand.index("--python-platform") + 1] == (
        "x86_64-unknown-linux-gnu"
    )
    assert dictSeen["sConstraints"] == (
        "numpy==2.5.2\nscipy==1.18.1\nmatplotlib==3.11.1\n"
    )
    # The probes ran INSIDE the container, through the adapter.
    assert any("freeze" in listProbe for listProbe in filesRepo.listCommands)


def test_the_freeze_is_reduced_to_exact_pins():
    from vaibify.reproducibility.dependencyPinning import (
        flistConstraintPinsFromFreeze,
    )
    assert flistConstraintPinsFromFreeze(_S_FREEZE) == [
        "numpy==2.5.2", "scipy==1.18.1", "matplotlib==3.11.1",
    ]
    assert flistConstraintPinsFromFreeze("") == []


@pytest.mark.falsification
def test_a_container_that_cannot_be_asked_refuses_to_compile(tmp_path):
    """Kills: compiling unconstrained when the probe fails, which is the
    defect itself with a quieter log line."""
    (tmp_path / "requirements.txt").write_text("numpy>=1.26\n")
    filesRepo = _ContainerAnsweringProbes(tmp_path, "", "", iProbeExit=1)
    sModule = "vaibify.reproducibility.dependencyPinning"
    with mock.patch(sModule + ".shutil.which", return_value="/u/uv"):
        with mock.patch(sModule + ".subprocess.run") as mockRun:
            with pytest.raises(subprocess.CalledProcessError) as excInfo:
                fnGenerateRequirementsLock(filesRepo)
    assert not mockRun.called
    assert "could not be asked" in excInfo.value.stderr
    assert "requirements.lock" not in filesRepo.dictWritten


def test_piptools_gets_the_constraints_but_no_target_flags(tmp_path):
    (tmp_path / "requirements.txt").write_text("numpy>=1.26\n")
    filesRepo = _ContainerAnsweringProbes(tmp_path, "3 12 aarch64", _S_FREEZE)
    dictSeen = {}
    sModule = "vaibify.reproducibility.dependencyPinning"
    with mock.patch(sModule + ".shutil.which", return_value=None):
        with mock.patch(
            sModule + "._fbModuleAvailable",
            side_effect=lambda sName: sName == "piptools",
        ):
            with mock.patch(
                sModule + ".subprocess.run",
                side_effect=_ffnFakeRunRecordingStaging(_S_VALID_LOCK, dictSeen),
            ):
                fnGenerateRequirementsLock(filesRepo)
    listCommand = dictSeen["listCommand"]
    assert listCommand[:3] == [sys.executable, "-m", "piptools"]
    assert "-c" in listCommand and "constraints.txt" in listCommand
    assert "--python-version" not in listCommand
    assert "--python-platform" not in listCommand


def test_an_unknown_machine_gets_a_version_but_no_platform(tmp_path):
    (tmp_path / "requirements.txt").write_text("numpy>=1.26\n")
    filesRepo = _ContainerAnsweringProbes(tmp_path, "3 11 riscv64", _S_FREEZE)
    dictSeen = {}
    sModule = "vaibify.reproducibility.dependencyPinning"
    with mock.patch(sModule + ".shutil.which", return_value="/u/uv"):
        with mock.patch(
            sModule + ".subprocess.run",
            side_effect=_ffnFakeRunRecordingStaging(_S_VALID_LOCK, dictSeen),
        ):
            fnGenerateRequirementsLock(filesRepo)
    listCommand = dictSeen["listCommand"]
    assert listCommand[listCommand.index("--python-version") + 1] == "3.11"
    assert "--python-platform" not in listCommand


def test_a_host_clone_compiles_in_place_without_a_target(tmp_path):
    """The host lane is unchanged: its resolver's interpreter is the one
    the steps run under, so no constraints and no target are named."""
    (tmp_path / "requirements.txt").write_text("numpy>=1.26\n")
    sModule = "vaibify.reproducibility.dependencyPinning"
    with mock.patch(sModule + ".shutil.which", return_value="/u/uv"):
        with mock.patch(
            sModule + ".subprocess.run",
            side_effect=_fnFakeRunWriteLock(_S_VALID_LOCK),
        ) as mockRun:
            fnGenerateRequirementsLock(str(tmp_path))
    listCommand = mockRun.call_args.args[0]
    assert "-c" not in listCommand
    assert "--python-version" not in listCommand
