"""The mirror must name the packages it stops installing.

Dependencies are declared once, in ``vaibify.yml`` (2026-09-01 ruling),
and the entrypoint replaces each repository's
``.vaibify/requirements.txt`` with a generated mirror of the image's
list. A package that lived ONLY in that repository file was installed
at container start and is absent from the image, so once the mirror
replaces it the package is simply gone -- and the loss surfaces later,
somewhere else, as a step that will not run or a test suite that
cannot start.

``pytest`` is the ordinary case rather than an exotic one: every
vaibify project's test tiers need it, and a project that declared it
only in the repository file would lose its tests entirely on the next
rebuild. "This file was regenerated" does not tell a researcher that.

These drive the REAL shell function, extracted from ``entrypoint.sh``
and executed. Reading it is not enough: the first version used
``tr -d '[:space:]'``, which deletes NEWLINES as well as blanks, so it
collapsed the whole file into a single token -- it then reported one
nonsense package as dropped and missed every real one. That bug is
invisible on the page and obvious the moment it runs.
"""

import subprocess

from pathlib import Path

import pytest


PATH_ENTRYPOINT = (
    Path(__file__).resolve().parents[1]
    / "vaibify" / "containerImage" / "entrypoint.sh"
)
S_FUNCTION_NAME = "fnListRequirementNames"


def _fsExtractShellFunction(sName):
    """Return one function's source, straight out of entrypoint.sh."""
    listLines = PATH_ENTRYPOINT.read_text(encoding="utf-8").splitlines()
    listOut, bInside = [], False
    for sLine in listLines:
        if sLine.startswith(sName + "()"):
            bInside = True
        if bInside:
            listOut.append(sLine)
            if sLine == "}":
                break
    assert listOut, sName + " not found in entrypoint.sh"
    return "\n".join(listOut)


def _flistNamesFor(sRequirementsText, tmp_path):
    """Run the real shell function over one requirements text."""
    pathFile = tmp_path / "requirements.txt"
    pathFile.write_text(sRequirementsText)
    sScript = (
        _fsExtractShellFunction(S_FUNCTION_NAME)
        + "\n" + S_FUNCTION_NAME + " '" + str(pathFile) + "'\n"
    )
    resultRun = subprocess.run(
        ["bash", "-c", sScript], capture_output=True, text=True, check=True,
    )
    return resultRun.stdout.split()


def test_each_requirement_yields_its_own_name(tmp_path):
    """The bug that shipped first: newlines eaten, one token out."""
    assert _flistNamesFor(
        "matplotlib>=3.8\nnumpy>=1.26\npytest>=8.0\nvplot>=1.0\n", tmp_path,
    ) == ["matplotlib", "numpy", "pytest", "vplot"]


def test_the_generated_header_is_not_read_as_a_package(tmp_path):
    assert _flistNamesFor(
        "# GENERATED BY VAIBIFY -- do not edit.\n#\n# blah\nnumpy>=1.26\n",
        tmp_path,
    ) == ["numpy"]


def test_names_are_normalized_so_a_faithful_copy_is_not_a_difference(
    tmp_path,
):
    """``Foo_Bar`` and ``foo-bar`` are one package; so are two bounds."""
    assert _flistNamesFor("Foo_Bar>=1.0\n", tmp_path) == ["foo-bar"]
    assert _flistNamesFor("numpy>=1.24\n", tmp_path) == ["numpy"]
    assert _flistNamesFor("numpy>=1.26\n", tmp_path) == ["numpy"]


def test_extras_and_markers_do_not_become_part_of_the_name(tmp_path):
    assert _flistNamesFor(
        "requests[security]>=2\nnumpy>=1.26;python_version>='3.9'\n",
        tmp_path,
    ) == ["numpy", "requests"]


@pytest.mark.falsification
def test_a_package_only_in_the_repo_file_is_detected_as_dropped(tmp_path):
    """The whole point: pytest declared only in the repo file.

    Kills: in fnListRequirementNames, swapping ``[:blank:]`` back to
    ``[:space:]`` -- the file collapses to one token and the comparison
    below finds a nonsense name instead of pytest.
    """
    listRepo = _flistNamesFor(
        "matplotlib>=3.8\nnumpy>=1.26\npytest>=8.0\nvplot>=1.0\n", tmp_path,
    )
    listImage = _flistNamesFor(
        "# GENERATED\nmatplotlib\nnumpy\nvplot\n", tmp_path,
    )
    assert [s for s in listRepo if s not in listImage] == ["pytest"]
