"""A verification must not grade an image older than its declaration.

Dependencies are declared once, in ``vaibify.yml``'s ``pythonPackages``
(2026-09-01 ruling). The image is built from that list, the entrypoint
mirrors it into each repository, and ``requirements.lock`` compiles
from the mirror — so declaration, image and lock agree by
construction.

One link still breaks silently, and it is the one a researcher hits:
edit ``vaibify.yml`` and do not rebuild. Everything downstream still
agrees with the IMAGE, so every check passes while the project's own
declaration names a package the image does not have. That is not
hypothetical — a project declared ``pytest``, its image predated the
declaration by two days, and the resulting wall took six rounds to
diagnose (2026-09-01).

The comparison is by package NAME on purpose. Loosening ``numpy>=1.26``
to ``numpy>=1.24`` does not make an image stale — the installed numpy
satisfies both — whereas adding or removing a name always does. A
line-by-line comparison would fire on every version-bound edit and be
switched off within a week, which is worse than not having it.
"""

import pytest

from vaibify.reproducibility.declaredPackages import (
    fdictComparePackageDeclarations,
    flistParseRequirementNames,
)


S_MIRROR_HEADER = (
    "# GENERATED BY VAIBIFY -- do not edit.\n"
    "#\n"
    "# To add a dependency: edit vaibify.yml.\n"
)


def test_names_are_parsed_without_their_version_bounds():
    assert flistParseRequirementNames(
        "matplotlib>=3.8\nnumpy>=1.26\npytest>=8.0\n",
    ) == ["matplotlib", "numpy", "pytest"]


def test_comments_and_blank_lines_are_not_packages():
    """The mirror carries a generated header; it must not read as deps."""
    assert flistParseRequirementNames(
        S_MIRROR_HEADER + "\nnumpy>=1.26\n",
    ) == ["numpy"]


def test_names_are_normalized_the_way_pypa_normalizes_them():
    """``Foo_Bar`` and ``foo-bar`` are one package, not a divergence."""
    dictSeen = fdictComparePackageDeclarations(
        ["Foo_Bar>=1.0"], S_MIRROR_HEADER + "foo-bar>=1.0\n",
    )
    assert dictSeen["bMatches"] is True, dictSeen


def test_a_matching_declaration_and_image_agree():
    dictSeen = fdictComparePackageDeclarations(
        ["matplotlib>=3.8", "numpy>=1.26"],
        S_MIRROR_HEADER + "matplotlib>=3.8\nnumpy>=1.26\n",
    )
    assert dictSeen["bChecked"] is True
    assert dictSeen["bMatches"] is True


@pytest.mark.falsification
def test_a_package_declared_but_absent_from_the_image_is_reported():
    """The exact shape that cost six rounds of diagnosis.

    Kills: in fdictComparePackageDeclarations, compute listMissing as
    [] — a declaration the image does not satisfy reports as a match,
    and the verification proceeds against a stale image.
    """
    dictSeen = fdictComparePackageDeclarations(
        ["matplotlib>=3.8", "numpy>=1.26", "pytest>=8.0"],
        S_MIRROR_HEADER + "matplotlib>=3.8\nnumpy>=1.26\n",
    )
    assert dictSeen["bMatches"] is False
    assert dictSeen["listMissingFromImage"] == ["pytest"]
    assert dictSeen["listExtraInImage"] == []


def test_a_package_dropped_from_the_declaration_is_also_reported():
    """Divergence runs both ways: the image carries what nobody declares."""
    dictSeen = fdictComparePackageDeclarations(
        ["numpy>=1.26"],
        S_MIRROR_HEADER + "numpy>=1.26\nscipy>=1.11\n",
    )
    assert dictSeen["bMatches"] is False
    assert dictSeen["listExtraInImage"] == ["scipy"]


def test_a_version_bound_change_is_not_a_divergence():
    """Otherwise the check fires on edits that cannot stale an image."""
    dictSeen = fdictComparePackageDeclarations(
        ["numpy>=1.24"], S_MIRROR_HEADER + "numpy>=1.26\n",
    )
    assert dictSeen["bMatches"] is True


def test_an_unreadable_mirror_is_unchecked_not_matching():
    """"Could not ask" must never be recorded as "they agree"."""
    dictSeen = fdictComparePackageDeclarations(["numpy>=1.26"], None)
    assert dictSeen["bChecked"] is False


def test_an_unknown_declaration_is_unchecked_not_matching():
    """A project whose config cannot be found has not been shown to match."""
    dictSeen = fdictComparePackageDeclarations(
        [], S_MIRROR_HEADER + "numpy>=1.26\n",
    )
    assert dictSeen["bChecked"] is False


def test_editable_and_url_requirements_are_skipped_not_guessed():
    """A wrong name here would report a divergence that does not exist."""
    assert flistParseRequirementNames(
        "-e ./localpkg\n"
        "thing @ https://example.invalid/thing.whl\n"
        "--index-url https://example.invalid/simple\n"
        "numpy>=1.26\n",
    ) == ["numpy"]
