"""A pinned, token-free reproduce.sh can still be unrunnable.

Found on a live project (2026-09-14). Its `reproduce.sh` existed, was
hashed into MANIFEST.sha256, and carried no template tokens — so every
Level 3 check that looked at it passed. It was 29 lines: `docker pull`
the pinned digest, then run it. The image was built locally, so no
registry serves that digest, and the script had no way to fall back to
the project's own Zenodo deposit — which held exactly the image it
needed. A stranger's reproduction would have died on line 13, and the
ladder said Level 3.

The generator had grown that fallback long before; the script on disk
simply predated it. Nothing compared the two, so nothing could tell.

The comparison is exact rather than heuristic because
``fsRenderReproduceScript`` is pure and idempotent: the generator IS
the definition of "current", so a check that asks it cannot drift from
it the way a hand-written "does it contain fnLoadImageFromArchive"
probe would.
"""

import os
import subprocess

import pytest

from vaibify.reproducibility import levelGates
from vaibify.reproducibility.reproduceScriptGenerator import (
    S_REPRODUCE_SCRIPT_FILENAME, fsRenderReproduceScript,
)


_S_STALE_SCRIPT = """#!/usr/bin/env bash
# Auto-generated by vaibify. Reproduces this workflow on a stock host.
# Requires: docker, jq, sha256sum.
set -euo pipefail

sImageRef=$(jq -r .dictContainer.sImageDigest \\
    .vaibify/environment.json)
docker pull "$sImageRef"
"""


def _fdictBuildWorkflow():
    return {
        "sWorkflowName": "project",
        "sPlotDirectory": "Plot",
        "listSteps": [{
            "sName": "Make Data",
            "sDirectory": "MakeData",
            "saDataCommands": ["python makeData.py"],
            "saOutputDataFiles": ["out.json"],
        }],
    }


@pytest.fixture
def sProjectRepo(tmp_path):
    subprocess.run(["git", "init", "-q", str(tmp_path)], check=True)
    os.makedirs(os.path.join(str(tmp_path), ".vaibify"), exist_ok=True)
    return str(tmp_path)


def _fnWriteScript(sProjectRepo, sText):
    with open(
        os.path.join(sProjectRepo, S_REPRODUCE_SCRIPT_FILENAME), "w",
    ) as fileOut:
        fileOut.write(sText)


@pytest.mark.falsification
def test_a_script_that_predates_its_generator_is_caught(sProjectRepo):
    """The exact shape found live: pinned, token-free, and unrunnable.

    Kills: comparing anything weaker than the rendered bytes -- for
    instance checking only that the file is non-empty, or that it
    mentions the image digest. The stale script does both.
    """
    dictWorkflow = _fdictBuildWorkflow()
    _fnWriteScript(sProjectRepo, _S_STALE_SCRIPT)
    assert levelGates.fbVerifyReproduceScriptCurrent(
        sProjectRepo, dictWorkflow,
    ) is False


def test_the_script_the_generator_writes_now_passes(sProjectRepo):
    """The check must not condemn a script that is simply correct."""
    dictWorkflow = _fdictBuildWorkflow()
    _fnWriteScript(sProjectRepo, fsRenderReproduceScript(dictWorkflow))
    assert levelGates.fbVerifyReproduceScriptCurrent(
        sProjectRepo, dictWorkflow,
    ) is True


def test_a_stale_script_slips_past_every_older_check(sProjectRepo):
    """Why this needed a criterion of its own, asserted rather than said.

    The older gate asks three things and the stale script satisfies
    all three once it is pinned. If this ever starts failing because
    the older gate grew to cover staleness too, the two have merged
    and one of them should go.
    """
    dictWorkflow = _fdictBuildWorkflow()
    _fnWriteScript(sProjectRepo, _S_STALE_SCRIPT)
    # The declared artefacts have to exist for the manifest writer to
    # hash them; the point of the fixture is the SCRIPT, not them.
    os.makedirs(os.path.join(sProjectRepo, "MakeData"), exist_ok=True)
    for sRelPath in ("MakeData/makeData.py", "MakeData/out.json"):
        with open(os.path.join(sProjectRepo, sRelPath), "w") as fileOut:
            fileOut.write("# fixture\n")
    from vaibify.reproducibility.manifestWriter import fnWriteManifest
    fnWriteManifest(sProjectRepo, dictWorkflow)
    assert levelGates.fbVerifyReproduceScript(
        sProjectRepo, dictWorkflow,
    ) is True, "the older gate is expected to pass the stale script"
    assert levelGates.fbVerifyReproduceScriptCurrent(
        sProjectRepo, dictWorkflow,
    ) is False


def test_an_absent_script_is_the_other_criterions_to_report(sProjectRepo):
    """Two red criteria over one missing file double-charge the header."""
    assert levelGates.fbVerifyReproduceScriptCurrent(
        sProjectRepo, _fdictBuildWorkflow(),
    ) is True
    assert levelGates.fbVerifyReproduceScript(
        sProjectRepo, _fdictBuildWorkflow(),
    ) is False


def test_the_criterion_is_registered_everywhere_it_is_read(sProjectRepo):
    sCriterion = "reproduce-script-stale"
    assert sCriterion in levelGates._fdictL3WorkflowChecks(
        _fdictBuildWorkflow(), sProjectRepo,
    )
    assert sCriterion in levelGates._T_WORKFLOW_LEVEL3_CRITERIA
    assert sCriterion in levelGates._DICT_L3_REMEDIATION_HINTS
    import vaibify.gui as guiPackage
    sDirectory = os.path.join(os.path.dirname(guiPackage.__file__), "static")
    with open(os.path.join(sDirectory, "scriptApplication.js")) as fileIn:
        assert '"' + sCriterion + '"' in fileIn.read()
    with open(os.path.join(sDirectory, "scriptProofTab.js")) as fileIn:
        assert "bReproduceScriptCurrent" in fileIn.read()


@pytest.mark.falsification
def test_a_stale_script_blocks_the_scalar_gate(sProjectRepo, monkeypatch):
    """The gate enumerates by hand, so the dict entry is not enough.

    Kills: registering the criterion in the checks dict and the tuple
    without the ``fbAtLeastLevel3`` conjunct -- the header reports
    Level 3 attained above a row that blocks.
    """
    _fnWriteScript(sProjectRepo, _S_STALE_SCRIPT)
    # EVERY other conjunct satisfied, and the staleness gate left REAL
    # so the fixture's stale script is what refuses. With other
    # conjuncts still failing the gate returns False either way, and
    # the mutation that deletes this criterion SURVIVES unseen.
    from tests.levelGateStubs import fnMakeEveryLevel3ConjunctPass
    fnMakeEveryLevel3ConjunctPass(
        monkeypatch, fbVerifyReproduceScriptCurrent=None,
    )
    assert levelGates.fbAtLeastLevel3(
        _fdictBuildWorkflow(), sProjectRepo, False,
    ) is False


@pytest.mark.falsification
def test_the_artifact_row_goes_red_with_the_criterion(sProjectRepo):
    """The row and the gate must fail on the same set.

    Reported by the researcher on 2026-09-14, looking at a live
    project: the Reproduce script row showed a green Requirement mark
    while ``reproduce-script-stale`` was blocking that project's
    Level 3. The criterion had been registered in the checks dict, the
    header tuple, the remediation hints and both JavaScript surfaces
    -- and not in the map behind the row's own mark, which still asked
    the older gate alone. Every component was internally consistent
    and the screen contradicted the machinery, which is the class this
    module's skill exists for.

    Asserted through the route helper rather than the two gates,
    because a test that re-derives the conjunction here would agree
    with itself no matter what the row renders.

    Kills: dropping ``fbVerifyReproduceScriptCurrent`` from the row's
    entry in ``_fdictEnvelopeArtifactSatisfaction``.
    """
    from vaibify.gui.routes.pipelineRoutes import (
        _fdictEnvelopeArtifactSatisfaction,
    )
    from vaibify.reproducibility.manifestWriter import fnWriteManifest
    dictWorkflow = _fdictBuildWorkflow()
    _fnWriteScript(sProjectRepo, _S_STALE_SCRIPT)
    os.makedirs(os.path.join(sProjectRepo, "MakeData"), exist_ok=True)
    for sRelPath in ("MakeData/makeData.py", "MakeData/out.json"):
        with open(os.path.join(sProjectRepo, sRelPath), "w") as fileOut:
            fileOut.write("# fixture\n")
    fnWriteManifest(sProjectRepo, dictWorkflow)
    dictSatisfaction = _fdictEnvelopeArtifactSatisfaction(
        dictWorkflow, sProjectRepo,
    )
    assert dictSatisfaction["reproduceScript"] is False, (
        "the row claims the script meets its Level 3 check while "
        "reproduce-script-stale blocks the level"
    )


def test_the_artifact_row_is_green_when_the_script_is_current(
    sProjectRepo,
):
    """The conjunction must not condemn a script that is simply correct."""
    from vaibify.gui.routes.pipelineRoutes import (
        _fdictEnvelopeArtifactSatisfaction,
    )
    from vaibify.reproducibility.manifestWriter import fnWriteManifest
    dictWorkflow = _fdictBuildWorkflow()
    _fnWriteScript(sProjectRepo, fsRenderReproduceScript(dictWorkflow))
    os.makedirs(os.path.join(sProjectRepo, "MakeData"), exist_ok=True)
    for sRelPath in ("MakeData/makeData.py", "MakeData/out.json"):
        with open(os.path.join(sProjectRepo, sRelPath), "w") as fileOut:
            fileOut.write("# fixture\n")
    fnWriteManifest(sProjectRepo, dictWorkflow)
    assert _fdictEnvelopeArtifactSatisfaction(
        dictWorkflow, sProjectRepo,
    )["reproduceScript"] is True
