"""Tests for vaibify.reproducibility.dependencyPinning."""

import subprocess
from unittest import mock

import pytest

from vaibify.reproducibility.dependencyPinning import (
    fbIsUvAvailable,
    flistVerifyRequirementsLock,
    fnGenerateRequirementsLock,
)


_S_VALID_LOCK = (
    "# This file was autogenerated by uv\n"
    "click==8.1.7 \\\n"
    "    --hash=sha256:" + ("a" * 64) + "\n"
    "pyyaml==6.0.1 \\\n"
    "    --hash=sha256:" + ("b" * 64) + "\n"
)

_S_UNHASHED_LOCK = (
    "click==8.1.7 \\\n"
    "    --hash=sha256:" + ("a" * 64) + "\n"
    "pyyaml==6.0.1\n"
)


def _fnFakeRunWriteLock(sLockBody):
    """Build a subprocess.run replacement that writes a lockfile."""

    def fnFake(listCommand, cwd, capture_output, text, timeout=None):
        from pathlib import Path

        pathOut = Path(cwd) / "requirements.lock"
        pathOut.write_text(sLockBody)
        result = mock.Mock()
        result.returncode = 0
        result.stdout = ""
        result.stderr = ""
        return result

    return fnFake


def test_fnGenerateRequirementsLock_pyproject_happy_path(tmp_path):
    (tmp_path / "pyproject.toml").write_text(
        '[project]\nname = "demo"\ndependencies = ["click"]\n'
    )
    sModule = "vaibify.reproducibility.dependencyPinning"
    with mock.patch(sModule + ".shutil.which", return_value="/u/uv"):
        with mock.patch(
            sModule + ".subprocess.run",
            side_effect=_fnFakeRunWriteLock(_S_VALID_LOCK),
        ) as mockRun:
            fnGenerateRequirementsLock(str(tmp_path))

    pathLock = tmp_path / "requirements.lock"
    assert pathLock.is_file()
    listCommand = mockRun.call_args.args[0]
    assert listCommand[0:4] == ["uv", "pip", "compile",
                                "--generate-hashes"]
    assert "pyproject.toml" in listCommand


def test_fnGenerateRequirementsLock_requirements_in_happy_path(
    tmp_path,
):
    (tmp_path / "requirements.in").write_text("click\npyyaml\n")
    sModule = "vaibify.reproducibility.dependencyPinning"
    with mock.patch(sModule + ".shutil.which", return_value="/u/uv"):
        with mock.patch(
            sModule + ".subprocess.run",
            side_effect=_fnFakeRunWriteLock(_S_VALID_LOCK),
        ) as mockRun:
            fnGenerateRequirementsLock(str(tmp_path))

    listCommand = mockRun.call_args.args[0]
    assert "requirements.in" in listCommand
    assert "pyproject.toml" not in listCommand


def test_fnGenerateRequirementsLock_pyproject_takes_precedence(
    tmp_path,
):
    (tmp_path / "pyproject.toml").write_text(
        '[project]\nname = "demo"\n'
    )
    (tmp_path / "requirements.in").write_text("click\n")
    sModule = "vaibify.reproducibility.dependencyPinning"
    with mock.patch(sModule + ".shutil.which", return_value="/u/uv"):
        with mock.patch(
            sModule + ".subprocess.run",
            side_effect=_fnFakeRunWriteLock(_S_VALID_LOCK),
        ) as mockRun:
            fnGenerateRequirementsLock(str(tmp_path))

    listCommand = mockRun.call_args.args[0]
    assert "pyproject.toml" in listCommand
    assert "requirements.in" not in listCommand


def test_fnGenerateRequirementsLock_no_input_files(tmp_path):
    sModule = "vaibify.reproducibility.dependencyPinning"
    with mock.patch(sModule + ".shutil.which", return_value="/u/uv"):
        with pytest.raises(FileNotFoundError) as excInfo:
            fnGenerateRequirementsLock(str(tmp_path))

    sMessage = str(excInfo.value)
    assert "pyproject.toml" in sMessage
    assert "requirements.in" in sMessage


def test_fnGenerateRequirementsLock_uv_missing(tmp_path):
    (tmp_path / "pyproject.toml").write_text("[project]\n")
    sModule = "vaibify.reproducibility.dependencyPinning"
    with mock.patch(sModule + ".shutil.which", return_value=None):
        with pytest.raises(FileNotFoundError) as excInfo:
            fnGenerateRequirementsLock(str(tmp_path))

    sMessage = str(excInfo.value)
    assert "uv" in sMessage
    assert "https://docs.astral.sh/uv/" in sMessage


def test_fnGenerateRequirementsLock_compile_failure(tmp_path):
    (tmp_path / "pyproject.toml").write_text("[project]\n")
    sModule = "vaibify.reproducibility.dependencyPinning"
    resultFail = mock.Mock()
    resultFail.returncode = 2
    resultFail.stdout = ""
    resultFail.stderr = "error: could not resolve dependency 'foo'"
    with mock.patch(sModule + ".shutil.which", return_value="/u/uv"):
        with mock.patch(
            sModule + ".subprocess.run", return_value=resultFail
        ):
            with pytest.raises(
                subprocess.CalledProcessError
            ) as excInfo:
                fnGenerateRequirementsLock(str(tmp_path))

    assert excInfo.value.returncode == 2
    assert "could not resolve" in excInfo.value.stderr


def test_flistVerifyRequirementsLock_happy_path(tmp_path):
    (tmp_path / "requirements.lock").write_text(_S_VALID_LOCK)

    listIssues = flistVerifyRequirementsLock(str(tmp_path))

    assert listIssues == []


def test_flistVerifyRequirementsLock_missing_file(tmp_path):
    listIssues = flistVerifyRequirementsLock(str(tmp_path))

    assert len(listIssues) == 1
    assert "requirements.lock not found" in listIssues[0]


def test_flistVerifyRequirementsLock_unhashed_entry(tmp_path):
    (tmp_path / "requirements.lock").write_text(_S_UNHASHED_LOCK)

    listIssues = flistVerifyRequirementsLock(str(tmp_path))

    assert len(listIssues) == 1
    assert "pyyaml" in listIssues[0]
    assert "--hash=sha256" in listIssues[0]


def test_fbIsUvAvailable_reflects_shutil_which():
    sModule = "vaibify.reproducibility.dependencyPinning"
    with mock.patch(sModule + ".shutil.which", return_value="/u/uv"):
        assert fbIsUvAvailable() is True
    with mock.patch(sModule + ".shutil.which", return_value=None):
        assert fbIsUvAvailable() is False
