"""The mutation inventory is complete, unique, current, and well-formed.

The inventory (``tests/mutationInventory.json``, generated by
``tools/generateMutationInventory.py``) is the mandatory checkpoint
before any migration onto a single mutation carrier: one row per
reference that can reach a container, so a 280-site surgery is judged
against a record rather than against whoever last read the diff.

A record that can silently fall behind the code is worse than no record,
because it reads as coverage. THE FIRST VERSION OF THIS FILE WAS THAT
RECORD. It compared the inventory against the same scanner that built
it, and that scanner recognised only a direct call -- so 24 primitives
passed as callbacks (``asyncio.to_thread(connection.fnWriteFile, ...)``)
and 25 Docker CLI invocations assembled from scratch were invisible to
both. 21 of the callbacks were mutation-capable, including the
clean-outputs deletion the whole boundary was justified by. An external
review found it; the tests below are what would have.

So the scanner is now checked ADVERSARIALLY, against synthetic sources
containing each shape it must not miss, rather than only against the
tree it was written from. A scan that agrees with itself proves nothing.
"""

import ast
import collections
import copy
import importlib.util
import pathlib
import textwrap

import pytest


PATH_REPOSITORY = pathlib.Path(__file__).resolve().parent.parent

# The number of rows still awaiting a reviewer's semantic judgement.
# This is a RATCHET: it may only ever be lowered, and lowering it means
# somebody classified those rows. Raising it means new call sites
# shipped unreviewed, which is the state this record exists to make
# visible.
#
# 291 -> 293 on 2026-08-02, and this is the one shape of increase that
# is not new debt: scoping the scanner's command-list resolution per
# FUNCTION rather than per module resolved three sites that were only
# opaque because two functions in a module each named a local
# `listCommand`. Two of them are Docker invocations in a GUI module --
# `docker stats` and a mutation-capable `docker exec` -- so they moved
# OUT of the blind spot and INTO the record, which is the direction
# this file wants. DICT_UNRESOLVED_BUDGET fell from 26 to 23 in the
# same change; read the two numbers together or this one lies.
#
# 293 -> 289 on 2026-08-02: four rows withdrawn as false resolutions
# when the scanner gained a real lexical-scope model. See
# DICT_UNRESOLVED_BUDGET, which rose by the same four.
#
# 289 -> 307 on 2026-08-03, and this rise is the redesign working rather
# than debt arriving. Completeness moved off the command decoder and onto
# the capability, so the 18 launches whose argv the scan cannot read are
# now ROWS with an UNKNOWN command instead of blind-spot entries alone.
# Every one of them was a site the record previously could only count.
# Read this with DICT_UNRESOLVED_BUDGET, which fell 26 -> 18 in the same
# change for an unrelated reason, and with
# I_UNDISPOSED_ACQUISITION_BUDGET, which is the record that is now
# completeness-critical.
I_UNCLASSIFIED_ROW_BUDGET = 307


# Every acquisition of a declared capability that still has no reviewed
# disposition. A RATCHET on the same terms as the row budget, and the one
# that carries completeness: a use site can go unrecorded because nobody
# could decode it, but an acquisition is an import or an attribute load,
# which the scan reads exactly.
#
# Seeded at 66 on 2026-08-03, the count on the day the record was
# created: 37 process-launch, 11 Docker-client, 17 reflection, 1
# Unix-socket. None of them is reviewed yet, and the number says so out
# loud rather than shipping a record that implies a review nobody did.
I_UNDISPOSED_ACQUISITION_BUDGET = 66


def _fmoduleGenerator():
    """Import the inventory generator by path (tools/ is not a package)."""
    pathTool = PATH_REPOSITORY / "tools" / "generateMutationInventory.py"
    spec = importlib.util.spec_from_file_location(
        "generateMutationInventoryUnderTest", pathTool,
    )
    moduleTool = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(moduleTool)
    return moduleTool


@pytest.fixture(scope="module")
def moduleGenerator():
    return _fmoduleGenerator()


def _flistScanSource(moduleGenerator, sSource, sPath="synthetic.py"):
    """Run the scanner over a synthetic module and return its rows."""
    visitor = moduleGenerator._VisitorCallSites(sPath)
    visitor.fnCollect(ast.parse(textwrap.dedent(sSource)))
    return visitor.listRows


def _flistScanAcquisitions(moduleGenerator, sSource, sPath="synthetic.py"):
    """Run the scanner over a synthetic module and return its acquisitions."""
    visitor = moduleGenerator._VisitorCallSites(sPath)
    visitor.fnCollect(ast.parse(textwrap.dedent(sSource)))
    return visitor.listAcquisitions


# ---------------------------------------------------------------------
# The record matches the source.
# ---------------------------------------------------------------------

def testTheInventoryMatchesAFreshScanOfTheSource(moduleGenerator):
    """No added, removed, duplicated, edited, or hand-altered row."""
    dictDrift = moduleGenerator.fdictCompareAgainstSource(
        moduleGenerator.fdictLoadInventory(),
        moduleGenerator.flistScanPackage(),
    )
    assert dictDrift["listAdded"] == [], (
        "these container references are not in the inventory, so "
        "nothing decided whether they may reach a container: "
        f"{dictDrift['listAdded']}. Run "
        "`python tools/generateMutationInventory.py --write` and "
        "classify them."
    )
    assert dictDrift["listRemoved"] == [], (
        "the inventory describes references the source no longer has, "
        f"so a reviewer would be reasoning about fiction: "
        f"{dictDrift['listRemoved']}"
    )
    assert dictDrift["listDuplicated"] == [], (
        f"two rows claim the same site, so one is being ignored and "
        f"nobody knows which: {dictDrift['listDuplicated']}"
    )
    assert dictDrift["listEdited"] == [], (
        "these sites CHANGED since they were recorded, so their "
        "classification describes something else and must be re-read: "
        f"{dictDrift['listEdited']}"
    )
    assert dictDrift["listAltered"] == [], (
        "these rows disagree with a fresh scan about a field the "
        "SCANNER owns, so somebody edited a derived value by hand: "
        f"{dictDrift['listAltered']}"
    )
    assert dictDrift["listCountMismatch"] == [], (
        f"the recorded row count is not the number of rows: "
        f"{dictDrift['listCountMismatch']}"
    )


def testTheUnclassifiedBudgetOnlyEverShrinks(moduleGenerator):
    """The semantic review is unfinished, and says so out loud."""
    listUnclassified = moduleGenerator.flistUnclassifiedKeys(
        moduleGenerator.fdictLoadInventory(),
    )
    assert len(listUnclassified) <= I_UNCLASSIFIED_ROW_BUDGET, (
        f"{len(listUnclassified)} inventory rows are unclassified, over "
        f"the budget of {I_UNCLASSIFIED_ROW_BUDGET}. New call sites "
        f"must be classified as they are added, not deferred onto a "
        f"backlog that only grows."
    )
    if len(listUnclassified) < I_UNCLASSIFIED_ROW_BUDGET:
        pytest.fail(
            f"{len(listUnclassified)} rows are now classified, which is "
            f"progress -- lower I_UNCLASSIFIED_ROW_BUDGET to "
            f"{len(listUnclassified)} so the ratchet holds the gain."
        )


def testClassifiedRowsUseTheDeclaredVocabulary(moduleGenerator):
    """A classification must be comparable, and an exclusion explained.

    The ratchet above counts rows still holding the sentinel. On its
    own that is trivially defeated: replace UNCLASSIFIED with an empty
    string, or with prose, and the row counts as classified while
    saying nothing a reviewer could check. Enumerated values make two
    classifications comparable, and an exclusion from the carrier
    without a rationale is how a boundary's exceptions grow unaudited.
    """
    listViolations = moduleGenerator.flistSchemaViolations(
        moduleGenerator.fdictLoadInventory(),
    )
    assert listViolations == [], (
        f"these classified rows do not use the declared vocabulary: "
        f"{listViolations}"
    )


# The sites the scan cannot resolve, budgeted BY KIND. A DECLARED blind
# spot with a ratchet, not a silence: each one might be a container
# mutation, and the honest position is to say how many the record cannot
# speak for rather than to imply it covers them.
#
# Per-kind, because one number let the two trade against each other: an
# SDK root could go untraceable while an opaque command was resolved,
# and the total would say the blind spot had not grown.
#
# 23 -> 27 on 2026-08-02, and this is the one shape of increase that is
# not lost ground: giving the scanner a real lexical-scope model
# WITHDREW four false resolutions. `_fsRunDetachedCommand(saCommand)`
# and three siblings take their command as a PARAMETER; the old
# module-wide collector borrowed some other function's `saCommand` and
# recorded them as `docker rm` and `docker tag`. One of them runs
# `docker run`. A site the record described wrongly is worse than one
# it admits it cannot read, so these four moved into the blind spot and
# the row count fell 293 -> 289 with them.
# 27 -> 26 on 2026-08-03: the withdrawn host-side director.py held one
# opaque site, ``fnExecuteCommand``'s ``subprocess.Popen(sCommand,
# shell=True)``. Note what that says about the scanner rather than only
# about the count: the most permissive command authority under
# vaibify/gui/ produced NO inventory row, only a blind-spot entry,
# because completeness was keyed on decoding the command instead of on
# the capability. That is the hole plan rule R3 exists to close.
# 26 -> 18 on 2026-08-03: eight of the recorded sites were never
# subprocess launches. ``asyncio.run(...)`` and ``uvicorn.run(...)`` were
# matched because the check read the trailing method name and nothing
# else, which is the same name-based classification the Docker-client
# origin rule was written to end, one primitive over. Launch detection is
# now rooted in a name the scope binds to the subprocess module, so a
# blind spot that had been over-reported by nearly a third is the size it
# always was. Note the direction of the error: the record was pessimistic
# here, which is the safe direction, but eight entries claiming a review
# was owed on code that could not reach a container is still eight
# reviews aimed at fiction.
DICT_UNRESOLVED_BUDGET = {
    "opaque-subprocess-command": 18,
    "untraceable-docker-sdk-root": 12,
}


def testTheScanDeclaresWhatItCannotRead(moduleGenerator):
    """The blind spot is counted per kind, and each may only shrink.

    A boundary that silently drops the commands it cannot parse reports
    a completeness it does not have -- which is exactly how the first
    version of this inventory came to claim 231 sites when there were
    288. Resolving a site (by naming its command literally, by routing
    it through a gateway, or by constructing the Docker client where it
    is used) lowers a number; adding an opaque one raises it and fails
    here.
    """
    dictInventory = moduleGenerator.fdictLoadInventory()
    listUnresolved = moduleGenerator.flistUnresolvedSites()
    dictCounted = collections.Counter(
        dictSite["sBlindSpotKind"] for dictSite in listUnresolved
    )
    assert set(dictCounted) <= set(DICT_UNRESOLVED_BUDGET), (
        f"an unbudgeted blind-spot kind appeared: "
        f"{set(dictCounted) - set(DICT_UNRESOLVED_BUDGET)}"
    )
    for sKind, iBudget in DICT_UNRESOLVED_BUDGET.items():
        iFound = dictCounted.get(sKind, 0)
        assert iFound <= iBudget, (
            f"{iFound} sites of kind {sKind} are unreadable to the scan, "
            f"over the budget of {iBudget}. Any of them could be a "
            f"container mutation: "
            f"{[s for s in listUnresolved if s['sBlindSpotKind'] == sKind]}"
        )
        if iFound < iBudget:
            pytest.fail(
                f"only {iFound} sites of kind {sKind} are now opaque -- "
                f"lower DICT_UNRESOLVED_BUDGET to hold the gain."
            )
    assert dictInventory["iUnresolvedSiteCount"] == len(listUnresolved), (
        "the recorded blind-spot count disagrees with a fresh scan; "
        "regenerate the inventory"
    )


def testTheRecordedBlindSpotCannotDriftFromTheSource(moduleGenerator):
    """Each declared-unreadable site is compared, not just counted.

    The budget above holds the SIZE of the blind spot. It says nothing
    about WHICH sites are in it, so a recorded site's file, function or
    kind could be rewritten by hand and every check stayed green while
    the totals held. That is the same class of defect as the row drift
    check this file already carries, and it matters more once a site
    carries a manual disposition: a disposition bound to a site that
    moved underneath it is a claim about code nobody re-read.

    Kills: comparing the blind spot by count alone.
    """
    dictInventory = moduleGenerator.fdictLoadInventory()
    dictDrift = moduleGenerator.fdictCompareAgainstSource(
        dictInventory, moduleGenerator.flistScanPackage(),
    )
    assert dictDrift["listBlindSpotDrift"] == [], (
        f"the recorded blind spot disagrees with a fresh scan: "
        f"{dictDrift['listBlindSpotDrift']}. Regenerate with "
        f"python tools/generateMutationInventory.py --write"
    )


# ---------------------------------------------------------------------
# The capability record: what a module HOLDS, not what it was decoded
# to run. This is the completeness boundary; everything above it about
# commands is metadata.
# ---------------------------------------------------------------------

@pytest.mark.falsification
def testTheAcquisitionRecordMatchesAFreshScanOfTheSource(moduleGenerator):
    """No added, removed, duplicated, or edited acquisition.

    An acquisition carries a REVIEWED disposition, so it is subject to
    the same drift question a row is, for a sharper reason: a
    disposition bound to an acquisition that moved underneath it is a
    claim about code nobody re-read.

    The mutation this is confirmed against plants a DYNAMIC acquisition
    -- a ``getattr`` whose member name is a variable -- in
    ``pipelineUtils.py``, a leaf module holding no capability of any
    kind. The choice of module is the point: a mutant planted in a
    module the record already lists as dangerous would be caught by that
    module's existing entries while the real hole -- a capability
    arriving somewhere nobody was watching -- stayed open.

    Kills: acquiring reflection dynamically in a module that carries no
    prior classification.
    """
    dictDrift = moduleGenerator.fdictCompareAgainstSource(
        moduleGenerator.fdictLoadInventory(),
        moduleGenerator.flistScanPackage(),
    )
    assert dictDrift["listAcquisitionDrift"] == [], (
        f"the recorded capability acquisitions disagree with a fresh "
        f"scan: {dictDrift['listAcquisitionDrift']}. Regenerate with "
        f"python tools/generateMutationInventory.py --write and dispose "
        f"of anything new."
    )


@pytest.mark.falsification
def testEveryAcquisitionCarriesADisposition(moduleGenerator):
    """A capability nobody ruled on is the failure, not the use of one.

    FAIL-CLOSED, and the direction of the lookup is what makes it so.
    The SCAN is the authority on which acquisitions exist and the record
    answers for each, so an acquisition the record has never heard of
    counts as undisposed. A check written the other way round -- walking
    the recorded entries and asking whether each is disposed -- would
    say nothing at all about a capability that arrived without one,
    which is the only case that matters.

    The budget is a ratchet and may only fall. It is at 66 because
    nothing is reviewed yet; that is a statement about the review, not a
    licence.

    Kills: acquiring a process-launch capability in a module that has
    none, without disposing of it.
    """
    listUndisposed = moduleGenerator.flistUndisposedAcquisitions(
        moduleGenerator.fdictLoadInventory(),
    )
    assert len(listUndisposed) <= I_UNDISPOSED_ACQUISITION_BUDGET, (
        f"{len(listUndisposed)} capability acquisitions carry no reviewed "
        f"disposition, over the budget of "
        f"{I_UNDISPOSED_ACQUISITION_BUDGET}. A new one must be disposed "
        f"of as it lands: {listUndisposed[:8]}"
    )
    if len(listUndisposed) < I_UNDISPOSED_ACQUISITION_BUDGET:
        pytest.fail(
            f"{len(listUndisposed)} acquisitions are now disposed of, "
            f"which is progress -- lower "
            f"I_UNDISPOSED_ACQUISITION_BUDGET to "
            f"{len(listUndisposed)} so the ratchet holds the gain."
        )


def testEveryAcquisitionCarriesItsOwnIdentity(moduleGenerator):
    """Two acquisitions in one scope are distinguishable.

    A disposition is written against one acquisition. Without a unique
    key and a fingerprint the record could only say how many
    capabilities a module holds, never which, and a reviewer's ruling
    would have nothing to attach to.
    """
    listAcquisitions = moduleGenerator.flistAcquisitions()
    listKeys = [
        moduleGenerator.fsAcquisitionKey(dictAcquisition)
        for dictAcquisition in listAcquisitions
    ]
    assert len(set(listKeys)) == len(listKeys), (
        f"two acquisitions share an identity: "
        f"{[sKey for sKey in listKeys if listKeys.count(sKey) > 1]}"
    )
    for dictAcquisition in listAcquisitions:
        assert len(dictAcquisition["sFingerprint"]) == 16, (
            f"{moduleGenerator.fsAcquisitionKey(dictAcquisition)} has no "
            f"usable fingerprint"
        )


@pytest.mark.falsification
def testAnImportedProcessCapabilityIsRecordedWhateverIsDoneWithIt(
    moduleGenerator,
):
    """The three shapes that used to make a use site VANISH.

    A lambda parameter, a comprehension target, and a name reassigned
    twice each defeat the scan's ability to say what a later call runs.
    Under a design whose completeness came from decoding that call, each
    one deleted the site from the record. Under this one the import is
    the record, and no amount of cleverness downstream can remove it --
    which is the entire point of moving the boundary onto the capability.

    Kills: recording an acquisition only when the module's use of it can
    be decoded.
    """
    for sShape, sSource in {
        "lambda parameter shadows the module": (
            "import subprocess\n"
            "fnHide = lambda subprocess: subprocess.run(saCommand)\n"
        ),
        "comprehension target shadows the module": (
            "import subprocess\n"
            "def fnGo(listRunners, saCommand):\n"
            "    return [subprocess for subprocess in listRunners]\n"
        ),
        "the argv is assigned twice": (
            "import subprocess\n"
            "def fnGo(bFlag):\n"
            "    saCommand = ['docker', 'rm', 'a']\n"
            "    if bFlag:\n"
            "        saCommand = ['git', 'status']\n"
            "    subprocess.run(saCommand)\n"
        ),
    }.items():
        listAcquisitions = _flistScanAcquisitions(moduleGenerator, sSource)
        assert [
            dictAcquisition["sCapability"]
            for dictAcquisition in listAcquisitions
        ] == [moduleGenerator.S_CAPABILITY_PROCESS_LAUNCH], (
            f"{sShape}: the module's process capability left the record"
        )


@pytest.mark.falsification
def testAnAcquisitionInsideAClassOrANestedFunctionIsRecorded(
    moduleGenerator,
):
    """An import is not always at the top of a file.

    Collecting acquisitions from module-level statements is the natural
    way to write this and is wrong twice over: this package imports
    ``docker`` inside a function five times, to keep the SDK off the
    import path, and imports ``subprocess`` inside methods. Both would
    be invisible.

    Kills: collecting acquisitions only from module-level statements.
    """
    listAcquisitions = _flistScanAcquisitions(moduleGenerator, """
        class Runner:
            def fnGo(self):
                import subprocess
                return subprocess

        def fouter():
            def finner():
                import docker
                return docker.from_env()
            return finner
    """)
    assert sorted(
        (dictAcquisition["sScope"], dictAcquisition["sCapability"])
        for dictAcquisition in listAcquisitions
    ) == [
        ("finner", moduleGenerator.S_CAPABILITY_DOCKER_CLIENT),
        ("fnGo", moduleGenerator.S_CAPABILITY_PROCESS_LAUNCH),
    ], (
        f"a nested acquisition was lost or misplaced: "
        f"{[(a['sScope'], a['sCapability']) for a in listAcquisitions]}"
    )


@pytest.mark.falsification
def testReflectionThroughSysModulesIsAnAcquisition(moduleGenerator):
    """``sys.modules["subprocess"].run(...)`` imports nothing.

    A vocabulary listing ``importlib`` and ``__import__`` and stopping
    there leaves this outside the record entirely: no import statement
    appears, and the module object arrives through a mapping the scan is
    not looking at. Reflection is acquisition, and the module-table
    lookup is reflection.

    Kills: dropping sys.modules from the dangerous vocabulary.
    """
    listAcquisitions = _flistScanAcquisitions(moduleGenerator, """
        def fnGo(saCommand):
            return sys.modules["subprocess"].run(saCommand)
    """)
    assert [
        dictAcquisition["sCapability"]
        for dictAcquisition in listAcquisitions
    ] == [moduleGenerator.S_CAPABILITY_REFLECTION], (
        "a module fetched from sys.modules left no acquisition"
    )


@pytest.mark.falsification
def testEvalAndExecAreAcquisitions(moduleGenerator):
    """Process authority obtained from a string is still obtained.

    Nothing can read inside the string, and nothing needs to: the
    capability to evaluate one is the capability, and it is what carries
    the disposition.

    Kills: dropping eval and exec from the dangerous vocabulary.
    """
    listAcquisitions = _flistScanAcquisitions(moduleGenerator, """
        def fnGo(sCommand):
            fnLaunch = eval("__import__('subprocess').Popen")
            exec("import subprocess")
            return fnLaunch(sCommand)
    """)
    assert [
        dictAcquisition["sCapabilityName"]
        for dictAcquisition in listAcquisitions
    ] == ["eval", "exec"], (
        f"an eval-obtained handle left no acquisition: "
        f"{[a['sCapabilityName'] for a in listAcquisitions]}"
    )


@pytest.mark.falsification
def testADynamicAttributeLookupIsAnAcquisition(moduleGenerator):
    """``getattr(module, sName)`` reaches whatever the caller asks for.

    Narrowed to a NON-LITERAL attribute name, which is the whole
    distinction: ``getattr(objThing, "sName", None)`` reaches a member
    the reader can see, and recording it would bury the reflection this
    is for under several hundred ordinary lookups.

    Kills: dropping dynamic getattr from the dangerous vocabulary.
    """
    listAcquisitions = _flistScanAcquisitions(moduleGenerator, """
        def fnGo(module, sName, objThing):
            objLiteral = getattr(objThing, "sAttribute", None)
            return (objLiteral, getattr(module, sName))
    """)
    assert [
        dictAcquisition["sCapabilityName"]
        for dictAcquisition in listAcquisitions
    ] == ["getattr(dynamic)"], (
        f"a dynamic attribute lookup was lost, or a literal one swept "
        f"in: {[a['sCapabilityName'] for a in listAcquisitions]}"
    )


@pytest.mark.falsification
def testAMemberOfAnOrdinaryModuleIsAcquiredWhenItIsNamed(moduleGenerator):
    """``import os`` is not acquisition; ``os.system`` is.

    The narrowing that keeps acquisition useful. 33 modules in this
    package import ``os`` and 28 import ``asyncio``, so a module-level
    reading of either would classify most of the package as dangerous
    and tell a reviewer nothing. The member is the capability.

    Kills: recording the import of an ordinary module instead of the
    naming of its dangerous member.
    """
    assert _flistScanAcquisitions(moduleGenerator, """
        import os
        import asyncio

        def fnGo(sPath):
            return os.path.join(sPath, "output")
    """) == [], "importing os was read as acquiring a process capability"
    listAcquisitions = _flistScanAcquisitions(moduleGenerator, """
        import os
        import asyncio

        async def fnGo(sCommand, saCommand):
            os.system(sCommand)
            os.execv(saCommand[0], saCommand)
            await asyncio.create_subprocess_exec(*saCommand)
    """)
    assert [
        dictAcquisition["sCapabilityName"]
        for dictAcquisition in listAcquisitions
    ] == [
        "os.system", "os.execv", "asyncio.create_subprocess_exec",
    ], (
        f"a dangerous member of an ordinary module was not acquired: "
        f"{[a['sCapabilityName'] for a in listAcquisitions]}"
    )


@pytest.mark.falsification
def testAnAliasedModuleDoesNotHideItsDangerousMember(moduleGenerator):
    """``import os as operatingSystem`` then ``operatingSystem.system``.

    A member is looked up under the module it came FROM, never under the
    local name the file gave it. Keying on the spelling is the defect
    the launcher rule and the Docker-client rule each already had, and
    it fails worse here: an aliased launcher degrades to a declared
    blind spot, whereas an aliased ``os.system`` would be absent from
    every record the boundary keeps.

    No module in this package aliases ``os`` today, so this closes a
    hole nothing has fallen into yet -- which is the only time a hole
    can be closed cheaply.

    Kills: looking a dangerous member up under the local name of the
    module it hangs off.
    """
    assert [
        dictAcquisition["sCapabilityName"]
        for dictAcquisition in _flistScanAcquisitions(moduleGenerator, """
            import os as operatingSystem

            def fnGo(sCommand):
                operatingSystem.system(sCommand)
        """)
    ] == ["os.system"], "an aliased module hid its dangerous member"


@pytest.mark.falsification
def testAFromImportOfALauncherIsAcquiredAndItsAliasResolves(
    moduleGenerator,
):
    """``from subprocess import run as X`` then ``X([...])``.

    Two claims about the same shape, and they belong together because
    the second is what the first is FOR: the capability is acquired at
    the import, and the use site is still decoded through the alias so
    the metadata does not degrade just because the caller renamed
    something.

    Kills: reading a from-import of a launcher as neither an acquisition
    nor a binding.
    """
    sSource = """
        from subprocess import run as fnLaunch

        def fnRemoveIt(sContainerName):
            fnLaunch(["docker", "rm", sContainerName])
    """
    assert [
        dictAcquisition["sCapability"]
        for dictAcquisition in _flistScanAcquisitions(
            moduleGenerator, sSource,
        )
    ] == [moduleGenerator.S_CAPABILITY_PROCESS_LAUNCH], (
        "a launcher imported under another name was not acquired"
    )
    assert [
        dictRow["sPrimitive"]
        for dictRow in _flistScanSource(moduleGenerator, sSource)
    ] == ["docker rm"], "the aliased launcher's command was not decoded"


@pytest.mark.falsification
def testALauncherBoundToALocalNameStillResolves(moduleGenerator):
    """``fnLaunch = subprocess.run`` then ``fnLaunch([...])``.

    The assignment form of the shape above, and a separate guard: the
    from-import populates the launcher names from an ``ImportFrom``
    node, this one from an ``Assign``. One mutation cannot break both,
    so they are two tests.

    Kills: reading an assignment from a subprocess launcher as an
    ordinary local.
    """
    assert [
        dictRow["sPrimitive"]
        for dictRow in _flistScanSource(moduleGenerator, """
            import subprocess

            def fnRemoveIt(sContainerName):
                fnLaunch = subprocess.run
                fnLaunch(["docker", "rm", sContainerName])
        """)
    ] == ["docker rm"], "a launcher bound to a local name was not followed"


@pytest.mark.falsification
def testAnUnrelatedRunMethodIsNotAProcessLaunch(moduleGenerator):
    """``runner.run(...)`` is not ``subprocess.run(...)``.

    Matching the trailing method name alone put eight sites in the
    recorded blind spot that were never process launches -- every
    ``asyncio.run`` and ``uvicorn.run`` in the package. A record whose
    entries are nearly a third fiction spends real review effort on code
    that cannot reach a container, which is how a boundary loses the
    attention it needs for the sites that can.

    Kills: matching a launcher by its method name without checking that
    the chain is rooted in the subprocess module.
    """
    visitor = moduleGenerator._VisitorCallSites("probe.py")
    visitor.fnCollect(ast.parse(textwrap.dedent("""
        def fnGo(runner, coroutine, saCommand):
            runner.run(saCommand)
            asyncio.run(coroutine)
    """)))
    assert visitor.listRows == [], (
        f"an unrelated run() was recorded as a process launch: "
        f"{[dictRow['sPrimitive'] for dictRow in visitor.listRows]}"
    )
    assert visitor.listUnresolvedSubprocessSites == [], (
        "an unrelated run() was declared as an unreadable command"
    )


@pytest.mark.falsification
def testAnUnrelatedFromEnvIsNotADockerClient(moduleGenerator):
    """``boto3.from_env()`` spells a constructor this scan knows.

    The Docker-client origin rule checked the constructor's NAME and not
    the root it hung off, so any library offering a ``from_env`` handed
    the record a client. The root is what makes it Docker.

    Kills: accepting a client constructor without checking that its
    chain is rooted in the Docker SDK package.
    """
    assert _flistScanSource(moduleGenerator, """
        def fnGo(sBucket):
            clientStorage = boto3.from_env()
            clientStorage.images.remove(sBucket)
    """) == [], "an unrelated library's client entered the Docker record"


@pytest.mark.falsification
def testAChainedDockerConstructorIsStillTheDockerSdk(moduleGenerator):
    """``sdkDocker.APIClient(...).containers.remove(...)`` binds no name.

    The client is never assigned, so an origin rule that only reads
    assignments sees no client and drops the call. The low-level
    ``APIClient`` is the one that most needs recording: it reaches the
    daemon's HTTP API directly.

    THE ALIAS IS LOAD-BEARING, and finding out why is the reason this
    test reads the way it does. Written with the plain spelling
    ``docker.APIClient()...``, it survived every single mutation: the
    name ``docker`` is ALSO the route context's mapping key, seeded as a
    client name for an unrelated reason, so the chain resolved twice
    over and the test proved only that two guards existed. Importing
    under another name removes the seed from the question and leaves the
    constructor path alone to answer.

    Kills: resolving a Docker client only through an assignment.
    """
    assert [
        dictRow["sPrimitive"]
        for dictRow in _flistScanSource(moduleGenerator, """
            import docker as sdkDocker

            def fnRemoveIt(sContainerName):
                sdkDocker.APIClient().containers.remove(sContainerName)
        """)
    ] == ["sdk containers.remove"], (
        "a chained Docker constructor left no row"
    )


@pytest.mark.falsification
def testANestedFunctionsLocalCannotAnswerForItsParent(moduleGenerator):
    """A scope's bindings stay inside it, in both directions.

    ``ast.walk`` cannot express a scope: skipping a nested FunctionDef
    inside a walk loop does NOT prune its subtree, so a collector
    written that way reads the nested function's assignments as the
    parent's. The consequence was not a wrong label but a DISAPPEARANCE
    -- with the parent's command arriving as a parameter and an inner
    function assigning the same name a readable git list, the scan
    judged the parent readable, found no Docker subcommand, and emitted
    neither a row nor a blind spot. The site was in no part of the
    record at all, which is the one outcome this record exists to make
    impossible.

    Kills: collecting a scope's bindings with ast.walk instead of
    pruning at scope boundaries.
    """
    sSource = textwrap.dedent(
        """
        def outer(listCommand):
            def inner():
                listCommand = ["git", "status"]
            subprocess.run(listCommand)
        """
    )
    visitor = moduleGenerator._VisitorCallSites("probe.py")
    visitor.fnCollect(ast.parse(sSource))
    assert [
        dictSite["sFunction"]
        for dictSite in visitor.listUnresolvedSubprocessSites
    ] == ["outer"], (
        "the parent's opaque command was answered by a nested "
        "function's local, so the site left the record entirely"
    )


def _fnAssertUntraceableRatherThanClient(moduleGenerator, sSource):
    """Assert a source emits no row and one declared SDK blind spot."""
    visitor = moduleGenerator._VisitorCallSites("probe.py")
    visitor.fnCollect(ast.parse(textwrap.dedent(sSource)))
    assert visitor.listRows == [], (
        f"a name that is not a Docker client was recorded as one: "
        f"{[row['sPrimitive'] for row in visitor.listRows]}"
    )
    assert [
        dictSite["sFunction"] for dictSite in visitor.listUnresolvedSdkSites
    ] == ["funrelated"], "the untraceable root was dropped, not declared"


# The reported shape -- a sibling function's parameter mistaken for a
# client -- is covered TWICE over, by scope confinement and by
# shadowing, so no single mutation can kill a test written on it: the
# surviving guard answers correctly on its own. It is split here into
# the two shapes that each isolate one guard, because a falsification
# test that no single defect can break proves only that two guards
# exist, never that either works.
@pytest.mark.falsification
def testASiblingScopesClientNameDoesNotEscapeIt(moduleGenerator):
    """A client bound in one function is not a client in the next.

    Only CONFINEMENT protects this shape: ``funrelated`` binds nothing
    named ``d``, so shadowing has no part to play. Collecting client
    origins across the whole module -- which is what the scan did --
    reinstates exactly the name-based guess the origin rule was written
    to end.

    The honest fallback matters as much as the refusal: the call is
    docker-py-SHAPED with an untraceable root, so it belongs in the
    declared blind spot rather than in silence.

    Kills: collecting a scope's bindings with ast.walk instead of
    pruning at scope boundaries.
    """
    _fnAssertUntraceableRatherThanClient(
        moduleGenerator,
        """
        def fclientMake():
            d = docker.from_env()

        def funrelated():
            d.images.remove("thumbnail")
        """,
    )


@pytest.mark.falsification
def testAParameterShadowsAModuleLevelClient(moduleGenerator):
    """A rebound name is not the outer thing that shares its spelling.

    Only SHADOWING protects this shape: the client really is visible
    from the enclosing scope, and the parameter is what makes it not
    apply. Inheriting outer bindings without subtracting what a scope
    rebinds gets this wrong in the dangerous direction -- it reports a
    confident classification of an object the scan has never seen.

    Kills: inheriting outer bindings without removing the names a scope
    rebinds.
    """
    _fnAssertUntraceableRatherThanClient(
        moduleGenerator,
        """
        d = docker.from_env()

        def funrelated(d):
            d.images.remove("thumbnail")
        """,
    )


def testTheScopeModelStillResolvesWhatItShould(moduleGenerator):
    """The negative control for the two tests above.

    A scope model that resolved NOTHING would pass both of them while
    destroying the record's usefulness -- every site would become a
    blind spot and the boundary would know nothing. These three shapes
    must still resolve: a module-level constant, a function's own
    local, and a closure genuinely reading its parent's local.
    """
    dictExpected = {
        "module constant": (
            "LIST_COMMAND = ['docker', 'rm', 'x']\n"
            "def frun():\n"
            "    subprocess.run(LIST_COMMAND)\n"
        ),
        "own local": (
            "def frun():\n"
            "    listCommand = ['docker', 'rm', 'x']\n"
            "    subprocess.run(listCommand)\n"
        ),
        "closure reads parent local": (
            "def fouter():\n"
            "    listCommand = ['docker', 'rm', 'x']\n"
            "    def finner():\n"
            "        subprocess.run(listCommand)\n"
        ),
    }
    for sShape, sSource in dictExpected.items():
        visitor = moduleGenerator._VisitorCallSites("probe.py")
        visitor.fnCollect(ast.parse(sSource))
        assert [row["sPrimitive"] for row in visitor.listRows] == [
            "docker rm"
        ], f"{sShape} no longer resolves"


@pytest.mark.falsification
def testADuplicatedBlindSpotEntryIsCaught(moduleGenerator):
    """A repeated recorded site must not collapse into one slot.

    Keying the comparison by identity closed the count-only hole and
    opened a narrower one of the same shape: two identical entries
    occupy one dictionary slot, so the recorded list could hold 39
    sites while its count field said 38 and the set comparison found
    nothing wrong. The row check learned this lesson already, which is
    what ``listDuplicated`` is for over there.

    Kills: dropping the duplicate and length checks from
    _flistBlindSpotDrift.
    """
    dictInventory = copy.deepcopy(moduleGenerator.fdictLoadInventory())
    dictInventory["listUnresolvedSites"].append(
        copy.deepcopy(dictInventory["listUnresolvedSites"][0]),
    )
    dictDrift = moduleGenerator.fdictCompareAgainstSource(
        dictInventory, moduleGenerator.flistScanPackage(),
    )
    assert any(
        sDrift.startswith("duplicated")
        for sDrift in dictDrift["listBlindSpotDrift"]
    ), (
        f"a duplicated blind-spot entry passed unnoticed: "
        f"{dictDrift['listBlindSpotDrift']}"
    )


@pytest.mark.falsification
def testABlindSpotDispositionDiesWithItsCommandBuilder(moduleGenerator):
    """Swapping the builder must invalidate a bound manual disposition.

    The call expression of an opaque site is ``subprocess.run(command)``
    before AND after the function that fills ``command`` is changed from
    building a git invocation to building ``docker rm``. A disposition
    bound to that expression alone would survive precisely the edit that
    makes it false -- which is the whole failure mode a fingerprint
    exists to prevent, reintroduced one level up.

    So the enclosing scope is fingerprinted too. Its limit is real and
    stated in the generator: a builder defined in ANOTHER function is
    still outside this hash.

    Kills: dropping sScopeFingerprint, or removing it from the drift
    comparison.
    """
    sBefore = (
        "def f():\n"
        "    command = fbuildGitCommand()\n"
        "    subprocess.run(command)\n"
    )
    sAfter = sBefore.replace("fbuildGitCommand", "fbuildDockerDeleteCommand")

    def ftFingerprintOnly(sSource):
        visitor = moduleGenerator._VisitorCallSites("probe.py")
        visitor.fnCollect(ast.parse(sSource))
        dictSite = visitor.listUnresolvedSubprocessSites[0]
        return (dictSite["sFingerprint"], dictSite["sScopeFingerprint"])

    tBefore = ftFingerprintOnly(sBefore)
    tAfter = ftFingerprintOnly(sAfter)
    assert tBefore[0] == tAfter[0], (
        "the call expression did change -- rewrite this test's premise"
    )
    assert tBefore[1] != tAfter[1], (
        "the builder was swapped and the scope fingerprint held, so a "
        "manual disposition would survive the change that invalidates it"
    )


def testEveryBlindSpotCarriesItsOwnIdentity(moduleGenerator):
    """A site the scan cannot read is still identified exactly.

    Fingerprint and ordinal are what make a per-site disposition
    possible at all -- without them the record can only say how many
    sites it cannot speak for, never which, and two opaque calls in one
    function are indistinguishable.
    """
    listUnresolved = moduleGenerator.flistUnresolvedSites()
    listKeys = [
        moduleGenerator.fsBlindSpotKey(site) for site in listUnresolved
    ]
    assert len(set(listKeys)) == len(listKeys), (
        f"two blind spots share an identity: "
        f"{[k for k in listKeys if listKeys.count(k) > 1]}"
    )
    for dictSite in listUnresolved:
        assert len(dictSite["sFingerprint"]) == 16, (
            f"{moduleGenerator.fsBlindSpotKey(dictSite)} has no usable "
            f"fingerprint"
        )


# ---------------------------------------------------------------------
# The scanner is checked against what it must not miss.
# ---------------------------------------------------------------------

def testTheScannerSeesAPrimitivePassedAsACallback(moduleGenerator):
    """``asyncio.to_thread(connection.fnWriteFile, ...)`` is a call site.

    The exact omission an external review found. The AST node for a
    passed bound method is an attribute LOAD, not a Call, so a scanner
    that visits Call nodes sees the ``to_thread`` and nothing else --
    and 21 mutation-capable sites, including a container-wide file
    deletion, were absent from a record that claimed completeness.
    """
    listRows = _flistScanSource(moduleGenerator, """
        async def fnCleanOutputs(connectionDocker, sContainerId, sCommand):
            await asyncio.to_thread(
                connectionDocker.ftResultExecuteCommand,
                sContainerId, sCommand,
            )
    """)
    assert len(listRows) == 1, listRows
    assert listRows[0]["sPrimitive"] == "ftResultExecuteCommand"
    assert listRows[0]["sReferenceKind"] == (
        moduleGenerator.S_REFERENCE_PASSED_CALLABLE
    )
    assert listRows[0]["bMutationCapable"] is True


def testTheScannerSeesAPrimitiveBoundToALocalName(moduleGenerator):
    """An alias is a reference, and the reference is what matters."""
    listRows = _flistScanSource(moduleGenerator, """
        def fnWriteEverything(connectionDocker, listPaths):
            fnWriter = connectionDocker.fnWriteFile
            for sPath in listPaths:
                fnWriter("cid", sPath, b"")
    """)
    listPassed = [
        dictRow for dictRow in listRows
        if dictRow["sReferenceKind"] == (
            moduleGenerator.S_REFERENCE_PASSED_CALLABLE
        )
    ]
    assert len(listPassed) == 1, listRows
    assert listPassed[0]["sPrimitive"] == "fnWriteFile"


def testADirectCallIsNotAlsoCountedAsAPassedCallable(moduleGenerator):
    """One reference, one row -- the two shapes must not overlap."""
    listRows = _flistScanSource(moduleGenerator, """
        def fnRun(connectionDocker):
            connectionDocker.ftResultExecuteCommand("cid", "true")
    """)
    assert len(listRows) == 1, listRows
    assert listRows[0]["sReferenceKind"] == (
        moduleGenerator.S_REFERENCE_DIRECT_CALL
    )


def testTheScannerSeesADockerCommandBuiltFromScratch(moduleGenerator):
    """A subprocess reaches the daemon without passing any primitive.

    ``docker stop`` in a browser lifecycle route and ``docker cp``
    writing onto the HOST filesystem both bypass the gateways entirely,
    so a scan that enumerated only primitives reported on a boundary it
    had never looked at.
    """
    listRows = _flistScanSource(moduleGenerator, """
        def fnStopIt(sContainerName):
            subprocess.run(
                ["docker", "stop", sContainerName],
                capture_output=True, text=True,
            )
    """)
    assert len(listRows) == 1, listRows
    assert listRows[0]["sPrimitive"] == "docker stop"
    assert listRows[0]["bMutationCapable"] is True
    assert listRows[0]["sAccess"] == (
        moduleGenerator.S_ACCESS_DIRECT_DOCKER_CLI
    )


def testADockerReadCommandIsRecordedAsARead(moduleGenerator):
    """``docker inspect`` reaches the daemon but changes nothing."""
    listRows = _flistScanSource(moduleGenerator, """
        def fnInspect(sContainerName):
            subprocess.run(["docker", "inspect", sContainerName])
    """)
    assert len(listRows) == 1, listRows
    assert listRows[0]["bMutationCapable"] is False


def testANonDockerSubprocessIsNotRecorded(moduleGenerator):
    """The scan must not sweep in every subprocess in the package."""
    assert _flistScanSource(moduleGenerator, """
        def fnRunGit():
            subprocess.run(["git", "status"], capture_output=True)
    """) == []


def testADockerCommandBoundToALocalNameIsStillSeen(moduleGenerator):
    """``saCommand = [...]`` then ``run(saCommand)`` is the common shape.

    Ten real Docker invocations -- ``rm``, ``tag``, ``exec``, ``stats``
    -- were invisible purely because their argv had a name.
    """
    listRows = _flistScanSource(moduleGenerator, """
        def fnRemoveIt(sContainerName):
            saCommand = ["docker", "rm", sContainerName]
            subprocess.run(saCommand, capture_output=True)
    """)
    assert len(listRows) == 1, listRows
    assert listRows[0]["sPrimitive"] == "docker rm"
    assert listRows[0]["bMutationCapable"] is True


@pytest.mark.falsification
def testAnUnreadableCommandIsARowAndNotOnlyABlindSpot(moduleGenerator):
    """A command the scan cannot follow is a ROW, not only a count.

    This assertion used to be ``visitor.listRows == []``: an opaque
    launch produced a blind-spot entry and nothing else. The shipped
    demonstration that it was wrong is ``gui/director.py``, withdrawn in
    6e55cbf -- its ``fnExecuteCommand`` ran ``subprocess.Popen(sCommand,
    shell=True)`` over an arbitrary string, the most permissive command
    authority anywhere under ``vaibify/gui/``, and produced ZERO
    inventory rows. Completeness was keyed on DECODING the command, so
    the sites nobody could decode were the ones that vanished.

    The blind-spot entry stays as well, because the two say different
    things: the row says the capability is exercised here, the blind spot
    says the scan could not read what it ran.

    Kills: recording an opaque launch as a blind spot without also
    emitting a row.
    """
    visitor = moduleGenerator._VisitorCallSites("synthetic.py")
    visitor.fnCollect(ast.parse(textwrap.dedent("""
        def fnExecuteCommand(sCommand, sWorkingDirectory):
            return subprocess.Popen(
                sCommand, shell=True, cwd=sWorkingDirectory,
            )
    """)))
    assert [dictRow["sPrimitive"] for dictRow in visitor.listRows] == [
        moduleGenerator.S_PRIMITIVE_UNKNOWN_COMMAND
    ], (
        "the most permissive command authority in the package produced "
        "no inventory row"
    )
    assert visitor.listRows[0]["bMutationCapable"] is True, (
        "an undecodable command must count as mutation-capable"
    )
    assert len(visitor.listUnresolvedSubprocessSites) == 1, (
        "an opaque subprocess launch was silently dropped"
    )
    assert visitor.listUnresolvedSubprocessSites[0]["sFunction"] == (
        "fnExecuteCommand"
    )


def testANameAssignedTwiceIsNotGuessedAt(moduleGenerator):
    """Two candidate values is not a resolution -- but it is still a row.

    The refusal to guess is unchanged; what changed is what the refusal
    costs. The site is now recorded with an UNKNOWN command rather than
    left to the blind-spot count alone, so declining to decode no longer
    removes a capability use from the record.
    """
    visitor = moduleGenerator._VisitorCallSites("synthetic.py")
    visitor.fnCollect(ast.parse(textwrap.dedent("""
        def fnAmbiguous(bFlag):
            saCommand = ["docker", "rm", "a"]
            if bFlag:
                saCommand = ["git", "status"]
            subprocess.run(saCommand)
    """)))
    assert [dictRow["sPrimitive"] for dictRow in visitor.listRows] == [
        moduleGenerator.S_PRIMITIVE_UNKNOWN_COMMAND
    ], "the scan guessed which of two assignments was live"
    assert len(visitor.listUnresolvedSubprocessSites) == 1


def testTheScannerSeesADockerSdkMutation(moduleGenerator):
    """docker-py reaches the daemon without a CLI or a primitive.

    ``vaibify destroy`` removes a volume and an image through the SDK.
    A scan that looked only for ``subprocess.run(["docker", ...])`` and
    for named gateway primitives reported on a boundary it had never
    looked at: neither call produced a row.
    """
    listRows = _flistScanSource(moduleGenerator, """
        def fnRemoveImage(sFullName):
            dockerClient = docker.from_env()
            dockerClient.images.remove(sFullName, force=True)
    """)
    listSdk = [
        dictRow for dictRow in listRows
        if dictRow["sReferenceKind"] == (
            moduleGenerator.S_REFERENCE_DIRECT_DOCKER_SDK
        )
    ]
    assert len(listSdk) == 1, listRows
    assert listSdk[0]["sPrimitive"] == "sdk images.remove"
    assert listSdk[0]["bMutationCapable"] is True


def testTheScannerFollowsAnSdkObjectToItsMutation(moduleGenerator):
    """The mutation is a method on the object the SDK handed back.

    ``volume = client.volumes.get(name)`` then ``volume.remove()``: a
    chain-only scan sees the READ and misses the delete, which is
    exactly the shape ``vaibify destroy`` uses.
    """
    listRows = _flistScanSource(moduleGenerator, """
        def fnRemoveVolume(sVolumeName):
            dockerClient = docker.from_env()
            volume = dockerClient.volumes.get(sVolumeName)
            volume.remove(force=True)
    """)
    listMutating = [
        dictRow for dictRow in listRows if dictRow["bMutationCapable"]
    ]
    assert [dictRow["sPrimitive"] for dictRow in listMutating] == [
        "sdk volume.remove",
    ], listRows


def testAnSdkReadIsRecordedAsARead(moduleGenerator):
    """Listing containers reaches the daemon and changes nothing."""
    listRows = _flistScanSource(moduleGenerator, """
        def flistContainers():
            return docker.from_env().containers.list()
    """)
    assert len(listRows) == 1, listRows
    assert listRows[0]["bMutationCapable"] is False


def testTheScannerFollowsAChainedSdkMutation(moduleGenerator):
    """``client.volumes.get(name).remove()`` is one expression.

    A chain walk that stopped at the first call recorded the READ and
    missed the delete -- the shape a review used to defeat the previous
    version of this scan.
    """
    listRows = _flistScanSource(moduleGenerator, """
        def fnRemove(sName):
            dockerClient = docker.from_env()
            dockerClient.volumes.get(sName).remove(force=True)
    """)
    listMutating = [
        dictRow["sPrimitive"] for dictRow in listRows
        if dictRow["bMutationCapable"]
    ]
    assert listMutating == ["sdk get.remove"], listRows


def testAClientFetchedFromAMappingIsStillTheDockerSdk(moduleGenerator):
    """``dictCtx["docker"].containers.list(...)`` is a Docker call.

    The root is a subscript, not a name. A root test that only
    understood names dropped a real read from the record while
    tightening away the false positives -- coverage lost to a fix.
    """
    listRows = _flistScanSource(moduleGenerator, """
        def fnMountedPaths(dictCtx):
            for container in dictCtx["docker"].containers.list(all=True):
                del container
    """)
    assert [dictRow["sPrimitive"] for dictRow in listRows] == [
        "sdk containers.list",
    ], listRows


def testAnUnrelatedMappingIsNotMistakenForTheDockerSdk(moduleGenerator):
    """A subscript root is only a client when its KEY says so."""
    assert _flistScanSource(moduleGenerator, """
        def fnUnrelated(dictRegistry, sKey):
            dictRegistry["entries"].images.remove(sKey)
    """) == []


def testAClientIsRecognisedByOriginNotBySpelling(moduleGenerator):
    """``d = docker.from_env()`` is a client; ``client`` alone is not.

    A root test that accepted any name containing "docker" or "client"
    both missed a client bound to a short name and falsely claimed an
    unrelated library's. Coverage that turns on what somebody called a
    local is coverage a rename silently empties.
    """
    listRecognised = _flistScanSource(moduleGenerator, """
        def fnRemove(sName):
            d = docker.from_env()
            d.images.remove(sName)
    """)
    assert [dictRow["sPrimitive"] for dictRow in listRecognised] == [
        "sdk images.remove",
    ], listRecognised
    assert _flistScanSource(moduleGenerator, """
        def fnUnrelated(client, image):
            client.images.remove(image)
    """) == []


def testAnUntraceableClientIsDeclaredRatherThanDropped(moduleGenerator):
    """A client received as a PARAMETER is counted, not guessed at.

    Origin tracking cannot follow a client across a function boundary
    without interprocedural analysis. Guessing from the name is what it
    replaced; saying nothing would lose coverage to a precision fix. So
    the site joins the declared blind spot and its ratchet.
    """
    visitor = moduleGenerator._VisitorCallSites("synthetic.py")
    visitor.fnCollect(ast.parse(textwrap.dedent("""
        def fsDescribeImage(dockerClient, config):
            return dockerClient.images.get(config.sImageName)
    """)))
    assert visitor.listRows == []
    assert len(visitor.listUnresolvedSdkSites) == 1, (
        "an untraceable docker-py chain was silently dropped"
    )


def testAnUnrelatedLibraryIsNotMistakenForTheDockerSdk(moduleGenerator):
    """A collection name alone is not evidence of a Docker call.

    ``photoLibrary.images.remove(image)`` reads exactly like
    ``dockerClient.images.remove`` to a scan matching on ``images``.
    False rows dilute a record whose whole value is that every row
    means something.
    """
    assert _flistScanSource(moduleGenerator, """
        def fnUnrelated(photoLibrary, image):
            photoLibrary.images.remove(image)
    """) == []


def testANonDockerAttributeCallIsNotRecorded(moduleGenerator):
    """The SDK scan must not sweep in every attribute call."""
    assert _flistScanSource(moduleGenerator, """
        def fnSaveIt(dictRegistry, sKey):
            dictRegistry.entries.remove(sKey)
    """) == []


def testTwoReferencesInOneFunctionGetDistinctRows(moduleGenerator):
    """Repeated sites are separate rows with separate classifications."""
    listRows = moduleGenerator._flistNumberOrdinals(_flistScanSource(
        moduleGenerator, """
            def fnTwice(connectionDocker):
                connectionDocker.fnWriteFile("cid", "/a", b"")
                connectionDocker.fnWriteFile("cid", "/b", b"")
        """,
    ))
    assert len(listRows) == 2
    assert len({moduleGenerator.fsRowKey(row) for row in listRows}) == 2


# ---------------------------------------------------------------------
# The scope list cannot be quietly narrowed.
# ---------------------------------------------------------------------

def testEveryPublicGatewayMethodIsInTheScopeList(moduleGenerator):
    """Class methods count, which is where the first version was blind.

    The scan can only find references to primitives it knows about, so
    the scope list is the one place the boundary can be narrowed
    without touching a single call site. The first version read a
    module's ``__all__`` and otherwise walked MODULE-LEVEL definitions
    -- and ``dockerConnection.py`` has no ``__all__`` and defines every
    primitive as a method of ``DockerConnection``, so the check passed
    while looking at nothing at all.
    """
    listMissing = []
    for sModule in ("dockerConnection.py", "containerManager.py"):
        pathModule = PATH_REPOSITORY / "vaibify" / "docker" / sModule
        for sName in _flistPublicCallables(pathModule):
            if sName in _SET_GATEWAY_NAMES_OUT_OF_SCOPE:
                continue
            if sName not in moduleGenerator.DICT_PRIMITIVE_ACCESS:
                listMissing.append(f"{sModule}::{sName}")
    assert listMissing == [], (
        "these public gateway callables are not in the inventory's "
        f"scope list, so their references are invisible to it: "
        f"{listMissing}. Add each to DICT_PRIMITIVE_ACCESS with its "
        "access kind, or name it in "
        "_SET_GATEWAY_NAMES_OUT_OF_SCOPE with a reason."
    )


def _flistPublicCallables(pathModule):
    """Return every public function AND public method in a module."""
    treeAst = ast.parse(pathModule.read_text(encoding="utf-8"))
    listNames = []
    for node in ast.walk(treeAst):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and (
            not node.name.startswith("_")
        ):
            listNames.append(node.name)
    return sorted(set(listNames))


# Public gateway callables that do NOT reach a container, each with the
# reason it is out of scope. An allow-list of names, not a pattern: a
# heuristic over names is exactly what let a new class method slip past
# the first version, because a name it did not recognise looked like a
# name it did not need.
_SET_GATEWAY_NAMES_OUT_OF_SCOPE = {
    # Pure argument/flag assembly for a later launch; no daemon call.
    "flistBuildRunArgs",
    "fnMountSecrets",
    # Validation and naming helpers.
    "fnValidateReservationIdOrRaise",
    # Reads that answer about the HOST or the client, not a container.
    "ftProbeNetworkIsolation",
    "read",
    "close",
    "fsResolveDockerHost",
}
