"""The mutation inventory is complete, unique, current, and well-formed.

The inventory (``tests/mutationInventory.json``, generated by
``tools/generateMutationInventory.py``) is the mandatory checkpoint
before any migration onto a single mutation carrier: one row per
reference that can reach a container, so a 280-site surgery is judged
against a record rather than against whoever last read the diff.

A record that can silently fall behind the code is worse than no record,
because it reads as coverage. THE FIRST VERSION OF THIS FILE WAS THAT
RECORD. It compared the inventory against the same scanner that built
it, and that scanner recognised only a direct call -- so 24 primitives
passed as callbacks (``asyncio.to_thread(connection.fnWriteFile, ...)``)
and 25 Docker CLI invocations assembled from scratch were invisible to
both. 21 of the callbacks were mutation-capable, including the
clean-outputs deletion the whole boundary was justified by. An external
review found it; the tests below are what would have.

So the scanner is now checked ADVERSARIALLY, against synthetic sources
containing each shape it must not miss, rather than only against the
tree it was written from. A scan that agrees with itself proves nothing.
"""

import ast
import importlib.util
import pathlib
import textwrap

import pytest


PATH_REPOSITORY = pathlib.Path(__file__).resolve().parent.parent

# The number of rows still awaiting a reviewer's semantic judgement.
# This is a RATCHET: it may only ever be lowered, and lowering it means
# somebody classified those rows. Raising it means new call sites
# shipped unreviewed, which is the state this record exists to make
# visible.
I_UNCLASSIFIED_ROW_BUDGET = 288


def _fmoduleGenerator():
    """Import the inventory generator by path (tools/ is not a package)."""
    pathTool = PATH_REPOSITORY / "tools" / "generateMutationInventory.py"
    spec = importlib.util.spec_from_file_location(
        "generateMutationInventoryUnderTest", pathTool,
    )
    moduleTool = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(moduleTool)
    return moduleTool


@pytest.fixture(scope="module")
def moduleGenerator():
    return _fmoduleGenerator()


def _flistScanSource(moduleGenerator, sSource, sPath="synthetic.py"):
    """Run the scanner over a synthetic module and return its rows."""
    visitor = moduleGenerator._VisitorCallSites(sPath)
    visitor.fnCollect(ast.parse(textwrap.dedent(sSource)))
    return visitor.listRows


# ---------------------------------------------------------------------
# The record matches the source.
# ---------------------------------------------------------------------

def testTheInventoryMatchesAFreshScanOfTheSource(moduleGenerator):
    """No added, removed, duplicated, edited, or hand-altered row."""
    dictDrift = moduleGenerator.fdictCompareAgainstSource(
        moduleGenerator.fdictLoadInventory(),
        moduleGenerator.flistScanPackage(),
    )
    assert dictDrift["listAdded"] == [], (
        "these container references are not in the inventory, so "
        "nothing decided whether they may reach a container: "
        f"{dictDrift['listAdded']}. Run "
        "`python tools/generateMutationInventory.py --write` and "
        "classify them."
    )
    assert dictDrift["listRemoved"] == [], (
        "the inventory describes references the source no longer has, "
        f"so a reviewer would be reasoning about fiction: "
        f"{dictDrift['listRemoved']}"
    )
    assert dictDrift["listDuplicated"] == [], (
        f"two rows claim the same site, so one is being ignored and "
        f"nobody knows which: {dictDrift['listDuplicated']}"
    )
    assert dictDrift["listEdited"] == [], (
        "these sites CHANGED since they were recorded, so their "
        "classification describes something else and must be re-read: "
        f"{dictDrift['listEdited']}"
    )
    assert dictDrift["listAltered"] == [], (
        "these rows disagree with a fresh scan about a field the "
        "SCANNER owns, so somebody edited a derived value by hand: "
        f"{dictDrift['listAltered']}"
    )
    assert dictDrift["listCountMismatch"] == [], (
        f"the recorded row count is not the number of rows: "
        f"{dictDrift['listCountMismatch']}"
    )


def testTheUnclassifiedBudgetOnlyEverShrinks(moduleGenerator):
    """The semantic review is unfinished, and says so out loud."""
    listUnclassified = moduleGenerator.flistUnclassifiedKeys(
        moduleGenerator.fdictLoadInventory(),
    )
    assert len(listUnclassified) <= I_UNCLASSIFIED_ROW_BUDGET, (
        f"{len(listUnclassified)} inventory rows are unclassified, over "
        f"the budget of {I_UNCLASSIFIED_ROW_BUDGET}. New call sites "
        f"must be classified as they are added, not deferred onto a "
        f"backlog that only grows."
    )
    if len(listUnclassified) < I_UNCLASSIFIED_ROW_BUDGET:
        pytest.fail(
            f"{len(listUnclassified)} rows are now classified, which is "
            f"progress -- lower I_UNCLASSIFIED_ROW_BUDGET to "
            f"{len(listUnclassified)} so the ratchet holds the gain."
        )


def testClassifiedRowsUseTheDeclaredVocabulary(moduleGenerator):
    """A classification must be comparable, and an exclusion explained.

    The ratchet above counts rows still holding the sentinel. On its
    own that is trivially defeated: replace UNCLASSIFIED with an empty
    string, or with prose, and the row counts as classified while
    saying nothing a reviewer could check. Enumerated values make two
    classifications comparable, and an exclusion from the carrier
    without a rationale is how a boundary's exceptions grow unaudited.
    """
    listViolations = moduleGenerator.flistSchemaViolations(
        moduleGenerator.fdictLoadInventory(),
    )
    assert listViolations == [], (
        f"these classified rows do not use the declared vocabulary: "
        f"{listViolations}"
    )


# The subprocess launches whose command the scan cannot read. This is a
# DECLARED blind spot with a ratchet, not a silence: each one might be a
# Docker invocation, and the honest position is to say how many the
# record cannot speak for rather than to imply it covers them.
I_UNRESOLVED_SUBPROCESS_BUDGET = 26


def testTheScanDeclaresWhatItCannotRead(moduleGenerator):
    """The blind spot is counted, and may only shrink.

    A boundary that silently drops the commands it cannot parse reports
    a completeness it does not have -- which is exactly how the first
    version of this inventory came to claim 231 sites when there were
    288. Resolving a site (by naming its command literally, or by
    routing it through a gateway) lowers this number; adding an opaque
    one raises it and fails here.
    """
    dictInventory = moduleGenerator.fdictLoadInventory()
    listUnresolved = moduleGenerator.flistUnresolvedSubprocessSites()
    assert len(listUnresolved) <= I_UNRESOLVED_SUBPROCESS_BUDGET, (
        f"{len(listUnresolved)} subprocess launches build their command "
        f"where the scan cannot read it, over the budget of "
        f"{I_UNRESOLVED_SUBPROCESS_BUDGET}. Any of them could be a "
        f"Docker invocation: {listUnresolved}"
    )
    assert dictInventory["iUnresolvedSubprocessCount"] == len(
        listUnresolved,
    ), (
        "the recorded blind-spot count disagrees with a fresh scan; "
        "regenerate the inventory"
    )
    if len(listUnresolved) < I_UNRESOLVED_SUBPROCESS_BUDGET:
        pytest.fail(
            f"only {len(listUnresolved)} sites are now opaque -- lower "
            f"I_UNRESOLVED_SUBPROCESS_BUDGET to hold the gain."
        )


# ---------------------------------------------------------------------
# The scanner is checked against what it must not miss.
# ---------------------------------------------------------------------

def testTheScannerSeesAPrimitivePassedAsACallback(moduleGenerator):
    """``asyncio.to_thread(connection.fnWriteFile, ...)`` is a call site.

    The exact omission an external review found. The AST node for a
    passed bound method is an attribute LOAD, not a Call, so a scanner
    that visits Call nodes sees the ``to_thread`` and nothing else --
    and 21 mutation-capable sites, including a container-wide file
    deletion, were absent from a record that claimed completeness.
    """
    listRows = _flistScanSource(moduleGenerator, """
        async def fnCleanOutputs(connectionDocker, sContainerId, sCommand):
            await asyncio.to_thread(
                connectionDocker.ftResultExecuteCommand,
                sContainerId, sCommand,
            )
    """)
    assert len(listRows) == 1, listRows
    assert listRows[0]["sPrimitive"] == "ftResultExecuteCommand"
    assert listRows[0]["sReferenceKind"] == (
        moduleGenerator.S_REFERENCE_PASSED_CALLABLE
    )
    assert listRows[0]["bMutationCapable"] is True


def testTheScannerSeesAPrimitiveBoundToALocalName(moduleGenerator):
    """An alias is a reference, and the reference is what matters."""
    listRows = _flistScanSource(moduleGenerator, """
        def fnWriteEverything(connectionDocker, listPaths):
            fnWriter = connectionDocker.fnWriteFile
            for sPath in listPaths:
                fnWriter("cid", sPath, b"")
    """)
    listPassed = [
        dictRow for dictRow in listRows
        if dictRow["sReferenceKind"] == (
            moduleGenerator.S_REFERENCE_PASSED_CALLABLE
        )
    ]
    assert len(listPassed) == 1, listRows
    assert listPassed[0]["sPrimitive"] == "fnWriteFile"


def testADirectCallIsNotAlsoCountedAsAPassedCallable(moduleGenerator):
    """One reference, one row -- the two shapes must not overlap."""
    listRows = _flistScanSource(moduleGenerator, """
        def fnRun(connectionDocker):
            connectionDocker.ftResultExecuteCommand("cid", "true")
    """)
    assert len(listRows) == 1, listRows
    assert listRows[0]["sReferenceKind"] == (
        moduleGenerator.S_REFERENCE_DIRECT_CALL
    )


def testTheScannerSeesADockerCommandBuiltFromScratch(moduleGenerator):
    """A subprocess reaches the daemon without passing any primitive.

    ``docker stop`` in a browser lifecycle route and ``docker cp``
    writing onto the HOST filesystem both bypass the gateways entirely,
    so a scan that enumerated only primitives reported on a boundary it
    had never looked at.
    """
    listRows = _flistScanSource(moduleGenerator, """
        def fnStopIt(sContainerName):
            subprocess.run(
                ["docker", "stop", sContainerName],
                capture_output=True, text=True,
            )
    """)
    assert len(listRows) == 1, listRows
    assert listRows[0]["sPrimitive"] == "docker stop"
    assert listRows[0]["bMutationCapable"] is True
    assert listRows[0]["sAccess"] == (
        moduleGenerator.S_ACCESS_DIRECT_DOCKER_CLI
    )


def testADockerReadCommandIsRecordedAsARead(moduleGenerator):
    """``docker inspect`` reaches the daemon but changes nothing."""
    listRows = _flistScanSource(moduleGenerator, """
        def fnInspect(sContainerName):
            subprocess.run(["docker", "inspect", sContainerName])
    """)
    assert len(listRows) == 1, listRows
    assert listRows[0]["bMutationCapable"] is False


def testANonDockerSubprocessIsNotRecorded(moduleGenerator):
    """The scan must not sweep in every subprocess in the package."""
    assert _flistScanSource(moduleGenerator, """
        def fnRunGit():
            subprocess.run(["git", "status"], capture_output=True)
    """) == []


def testADockerCommandBoundToALocalNameIsStillSeen(moduleGenerator):
    """``saCommand = [...]`` then ``run(saCommand)`` is the common shape.

    Ten real Docker invocations -- ``rm``, ``tag``, ``exec``, ``stats``
    -- were invisible purely because their argv had a name.
    """
    listRows = _flistScanSource(moduleGenerator, """
        def fnRemoveIt(sContainerName):
            saCommand = ["docker", "rm", sContainerName]
            subprocess.run(saCommand, capture_output=True)
    """)
    assert len(listRows) == 1, listRows
    assert listRows[0]["sPrimitive"] == "docker rm"
    assert listRows[0]["bMutationCapable"] is True


def testAnUnreadableCommandIsDeclaredRatherThanDropped(moduleGenerator):
    """A command the scan cannot follow is counted, not ignored."""
    visitor = moduleGenerator._VisitorCallSites("synthetic.py")
    visitor.fnCollect(ast.parse(textwrap.dedent("""
        def fnRunWhatever(saCommandFromElsewhere):
            subprocess.run(saCommandFromElsewhere, capture_output=True)
    """)))
    assert visitor.listRows == []
    assert len(visitor.listUnresolvedSubprocessSites) == 1, (
        "an opaque subprocess launch was silently dropped"
    )
    assert visitor.listUnresolvedSubprocessSites[0]["sFunction"] == (
        "fnRunWhatever"
    )


def testANameAssignedTwiceIsNotGuessedAt(moduleGenerator):
    """Two candidate values is not a resolution."""
    visitor = moduleGenerator._VisitorCallSites("synthetic.py")
    visitor.fnCollect(ast.parse(textwrap.dedent("""
        def fnAmbiguous(bFlag):
            saCommand = ["docker", "rm", "a"]
            if bFlag:
                saCommand = ["git", "status"]
            subprocess.run(saCommand)
    """)))
    assert visitor.listRows == [], (
        "the scan guessed which of two assignments was live"
    )
    assert len(visitor.listUnresolvedSubprocessSites) == 1


def testTwoReferencesInOneFunctionGetDistinctRows(moduleGenerator):
    """Repeated sites are separate rows with separate classifications."""
    listRows = moduleGenerator._flistNumberOrdinals(_flistScanSource(
        moduleGenerator, """
            def fnTwice(connectionDocker):
                connectionDocker.fnWriteFile("cid", "/a", b"")
                connectionDocker.fnWriteFile("cid", "/b", b"")
        """,
    ))
    assert len(listRows) == 2
    assert len({moduleGenerator.fsRowKey(row) for row in listRows}) == 2


# ---------------------------------------------------------------------
# The scope list cannot be quietly narrowed.
# ---------------------------------------------------------------------

def testEveryPublicGatewayMethodIsInTheScopeList(moduleGenerator):
    """Class methods count, which is where the first version was blind.

    The scan can only find references to primitives it knows about, so
    the scope list is the one place the boundary can be narrowed
    without touching a single call site. The first version read a
    module's ``__all__`` and otherwise walked MODULE-LEVEL definitions
    -- and ``dockerConnection.py`` has no ``__all__`` and defines every
    primitive as a method of ``DockerConnection``, so the check passed
    while looking at nothing at all.
    """
    listMissing = []
    for sModule in ("dockerConnection.py", "containerManager.py"):
        pathModule = PATH_REPOSITORY / "vaibify" / "docker" / sModule
        for sName in _flistPublicCallables(pathModule):
            if sName in _SET_GATEWAY_NAMES_OUT_OF_SCOPE:
                continue
            if sName not in moduleGenerator.DICT_PRIMITIVE_ACCESS:
                listMissing.append(f"{sModule}::{sName}")
    assert listMissing == [], (
        "these public gateway callables are not in the inventory's "
        f"scope list, so their references are invisible to it: "
        f"{listMissing}. Add each to DICT_PRIMITIVE_ACCESS with its "
        "access kind, or name it in "
        "_SET_GATEWAY_NAMES_OUT_OF_SCOPE with a reason."
    )


def _flistPublicCallables(pathModule):
    """Return every public function AND public method in a module."""
    treeAst = ast.parse(pathModule.read_text(encoding="utf-8"))
    listNames = []
    for node in ast.walk(treeAst):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and (
            not node.name.startswith("_")
        ):
            listNames.append(node.name)
    return sorted(set(listNames))


# Public gateway callables that do NOT reach a container, each with the
# reason it is out of scope. An allow-list of names, not a pattern: a
# heuristic over names is exactly what let a new class method slip past
# the first version, because a name it did not recognise looked like a
# name it did not need.
_SET_GATEWAY_NAMES_OUT_OF_SCOPE = {
    # Pure argument/flag assembly for a later launch; no daemon call.
    "flistBuildRunArgs",
    "fnMountSecrets",
    # Validation and naming helpers.
    "fnValidateReservationIdOrRaise",
    # Reads that answer about the HOST or the client, not a container.
    "ftProbeNetworkIsolation",
    "read",
    "close",
    "fsResolveDockerHost",
}
