"""The mutation inventory is complete, unique, and current.

The inventory (``tests/mutationInventory.json``, generated by
``tools/generateMutationInventory.py``) is the mandatory checkpoint
before any migration onto a single mutation carrier: one row per
container-mutation call site in the shipped package, so a 200-site
surgery is judged against a record rather than against whoever last
read the diff.

A record that can silently fall behind the code is worse than no record,
because it reads as coverage. So these tests re-scan the source and fail
on four things:

* a call site the record does not contain (something new can reach a
  container and nothing decided whether that is all right);
* a recorded call site the source no longer has (the record describes
  code that is gone, and a reviewer would be reasoning about fiction);
* a duplicated key (two rows for one site means one of them is being
  ignored, and nobody knows which); and
* an EDITED call site -- same key, different fingerprint. A call that
  changed has to be re-read; inheriting its old classification is
  exactly how a reviewed record stops describing what it reviewed.

The fifth property is a ratchet rather than a failure, and the reason is
stated plainly: the semantic classification has not been done. It is
reviewer's work, and a generator that guessed it -- or a test that
declared the guess acceptable -- would launder a guess into a record.
The count of unclassified rows is pinned here so it can only go DOWN.
"""

import ast
import importlib.util
import pathlib

import pytest


PATH_REPOSITORY = pathlib.Path(__file__).resolve().parent.parent

# The number of rows still awaiting a reviewer's semantic judgement.
# This is a RATCHET: it may only ever be lowered, and lowering it means
# somebody classified those rows. Raising it means new mutation call
# sites shipped unreviewed, which is the state this record exists to
# make visible.
I_UNCLASSIFIED_ROW_BUDGET = 231


def _fmoduleGenerator():
    """Import the inventory generator by path (tools/ is not a package)."""
    pathTool = PATH_REPOSITORY / "tools" / "generateMutationInventory.py"
    spec = importlib.util.spec_from_file_location(
        "generateMutationInventoryUnderTest", pathTool,
    )
    moduleTool = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(moduleTool)
    return moduleTool


@pytest.fixture(scope="module")
def moduleGenerator():
    return _fmoduleGenerator()


def testTheInventoryMatchesAFreshScanOfTheSource(moduleGenerator):
    """No added, removed, duplicated, or edited call site."""
    dictDrift = moduleGenerator.fdictCompareAgainstSource(
        moduleGenerator.fdictLoadInventory(),
        moduleGenerator.flistScanPackage(),
    )
    assert dictDrift["listAdded"] == [], (
        "these container-mutation call sites are not in the inventory, "
        "so nothing decided whether they may reach a container: "
        f"{dictDrift['listAdded']}. Run "
        "`python tools/generateMutationInventory.py --write` and "
        "classify them."
    )
    assert dictDrift["listRemoved"] == [], (
        "the inventory describes call sites the source no longer has, "
        f"so a reviewer would be reasoning about fiction: "
        f"{dictDrift['listRemoved']}"
    )
    assert dictDrift["listDuplicated"] == [], (
        f"two rows claim the same call site, so one is being ignored "
        f"and nobody knows which: {dictDrift['listDuplicated']}"
    )
    assert dictDrift["listEdited"] == [], (
        "these call sites CHANGED since they were recorded, so their "
        "classification describes something else and must be re-read: "
        f"{dictDrift['listEdited']}"
    )


def testTheUnclassifiedBudgetOnlyEverShrinks(moduleGenerator):
    """The semantic review is unfinished, and says so out loud."""
    listUnclassified = moduleGenerator.flistUnclassifiedKeys(
        moduleGenerator.fdictLoadInventory(),
    )
    assert len(listUnclassified) <= I_UNCLASSIFIED_ROW_BUDGET, (
        f"{len(listUnclassified)} inventory rows are unclassified, over "
        f"the budget of {I_UNCLASSIFIED_ROW_BUDGET}. New mutation call "
        f"sites must be classified as they are added, not deferred onto "
        f"a backlog that only grows."
    )
    if len(listUnclassified) < I_UNCLASSIFIED_ROW_BUDGET:
        pytest.fail(
            f"{len(listUnclassified)} rows are now classified, which is "
            f"progress -- lower I_UNCLASSIFIED_ROW_BUDGET to "
            f"{len(listUnclassified)} so the ratchet holds the gain."
        )


def testEveryDockerPrimitiveIsInTheScopeList(moduleGenerator):
    """A new primitive on either gateway must join the scanned set.

    The scan can only find calls to primitives it knows about, so the
    scope list is the one place a boundary can be quietly narrowed: add
    a public exec or write primitive to a gateway, forget this list, and
    every call site of it is invisible to the record forever. Read from
    each gateway's ``__all__``, because that is what the rest of the
    package is allowed to call.
    """
    listMissing = []
    for sModule in ("dockerConnection.py", "containerManager.py"):
        pathModule = PATH_REPOSITORY / "vaibify" / "docker" / sModule
        for sExported in _flistPublicNames(pathModule):
            if _fbNameLooksLikeAContainerPrimitive(sExported) and (
                sExported not in moduleGenerator.DICT_PRIMITIVE_ACCESS
            ):
                listMissing.append(f"{sModule}::{sExported}")
    assert listMissing == [], (
        "these gateway primitives are not in the inventory's scope "
        f"list, so their call sites are invisible to it: {listMissing}. "
        "Add each to DICT_PRIMITIVE_ACCESS with its access kind."
    )


def _flistPublicNames(pathModule):
    """Return a module's ``__all__`` entries, or its public defs."""
    treeAst = ast.parse(pathModule.read_text(encoding="utf-8"))
    for nodeAssign in ast.walk(treeAst):
        if isinstance(nodeAssign, ast.Assign) and any(
            isinstance(nodeTarget, ast.Name)
            and nodeTarget.id == "__all__"
            for nodeTarget in nodeAssign.targets
        ):
            return [
                nodeElement.value
                for nodeElement in nodeAssign.value.elts
                if isinstance(nodeElement, ast.Constant)
            ]
    return [
        node.name for node in treeAst.body
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
        and not node.name.startswith("_")
    ]


# The gateways export more than container primitives -- argument
# builders, path helpers, config readers. A name is in scope when it
# names a container OPERATION, which these stems identify; anything else
# is out of scope by construction and the list says which.
_TUPLE_PRIMITIVE_STEMS = (
    "ExecuteCommand", "RunInContainer", "ExecCreate", "ExecStart",
    "ExecResize", "WriteFile", "FetchFile", "StreamFile", "InspectExec",
    "RootShellProbe", "ProcessGroup", "StartContainer", "StopContainer",
    "RemoveStopped", "CreateContainerFor", "StartCreatedContainer",
    "SettleReservationContainers", "TerminateDockerProcess",
    "GetRunningContainers", "ContainerGetById", "EvictAbsentContainers",
)


def _fbNameLooksLikeAContainerPrimitive(sName):
    """Return True when an exported name reaches a container."""
    return any(sStem in sName for sStem in _TUPLE_PRIMITIVE_STEMS)


def testTheGatewaysThemselvesAreMarkedAsTheBoundary(moduleGenerator):
    """A gateway's own internals are the boundary, not callers of it.

    A migration must be able to tell "this call site should move onto
    the carrier" from "this call site IS the thing the carrier calls".
    Conflating them is how a refactor ends up wrapping a primitive in
    itself.
    """
    dictInventory = moduleGenerator.fdictLoadInventory()
    listInsideGateway = [
        dictRow for dictRow in dictInventory["listRows"]
        if dictRow["bInsideGateway"]
    ]
    assert listInsideGateway, (
        "no rows are marked as inside a gateway, so either the marking "
        "broke or the gateway modules stopped calling their own "
        "primitives -- both need a look"
    )
    for dictRow in listInsideGateway:
        assert dictRow["sFile"] in moduleGenerator.SET_GATEWAY_MODULES, (
            f"{dictRow['sFile']} is marked as a gateway but is not one"
        )
