"""The image key must cover every input, and no generated artifact.

Lane 2 reuses an immutable image instead of rebuilding per run, so a
key that misses an input silently ships a stale container. Two failure
modes are pinned here:

* an input that can change the image but is absent from the key
  (entrypoint, agent CLI, staged docs, the generator itself), and
* a *generated* file in the key. ``vaibify build`` writes
  ``docker/director.py`` and friends into the build context; they are
  gitignored, absent on a fresh clone, and stale on a developer machine
  -- this checkout's copy is already behind its source. Keying on them
  reintroduces the staleness the key exists to prevent.
"""

import pathlib
import sys

import pytest


_PATH_REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_PATH_REPO / "tools"))

from computeBuildInputHash import (  # noqa: E402
    flistBuildInputPaths,
    fsComputeBuildInputHash,
)


def testHashIsStableAcrossCalls():
    """An unchanged tree must produce an unchanged key."""
    assert fsComputeBuildInputHash() == fsComputeBuildInputHash()


@pytest.mark.falsification
def testGeneratedBuildContextCopiesAreNotKeyed():
    """Kills: hashing the gitignored copies instead of their sources.

    Mutation: add ``docker/director.py`` to the input globs. The copy
    is regenerated by ``vaibify build`` and gitignored, so on a fresh
    clone it does not exist and on a stale checkout it disagrees with
    its source -- either way the key stops describing the image.

    Checked against the DECLARED patterns, not only the resolved
    paths. This test first shipped asserting on resolved paths alone
    and the re-kill harness scored the mutant as SURVIVING: the
    harness runs in a pristine worktree where the gitignored artifact
    does not exist, so the added glob matched nothing and the
    assertion passed while the declaration was wrong. It only ever
    "worked" because the file happened to exist in the author's tree.
    """
    listGenerated = [
        "docker/director.py",
        "docker/overleafSync.py",
        "docker/latexConnector.py",
        "docker/zenodoClient.py",
        "docker/requirements.txt",
        "docker/system-packages.txt",
        "docker/binaries.env",
        "docker/container.conf",
        "docker/pip-flags.txt",
    ]
    import computeBuildInputHash as moduleHash
    listDeclared = [
        sPattern for sPattern in (
            tuple(moduleHash.T_BUILD_CONTEXT_GLOBS)
            + tuple(moduleHash.T_GENERATOR_SOURCES)
        )
        if sPattern in listGenerated
    ]
    assert not listDeclared, (
        "These are build-context artifacts written by `vaibify build`, "
        f"not sources; declaring them as inputs is unsound: "
        f"{listDeclared}"
    )
    listInputs = flistBuildInputPaths()
    listKeyed = [s for s in listGenerated if s in listInputs]
    assert not listKeyed, (
        f"Generated build-context artifacts reached the key: "
        f"{listKeyed}"
    )
    listStagedDocs = [s for s in listInputs if "docs-staged" in s]
    assert not listStagedDocs, (
        f"Staged doc copies keyed instead of their sources: "
        f"{listStagedDocs}"
    )


def testEverySourceBehindAGeneratedCopyIsKeyed():
    """The originals of the staged files must be in the key."""
    listInputs = flistBuildInputPaths()
    for sRequired in (
        "vaibify/gui/director.py",
        "vaibify/reproducibility/overleafSync.py",
        "vaibify/reproducibility/latexConnector.py",
        "vaibify/reproducibility/zenodoClient.py",
    ):
        assert sRequired in listInputs, (
            f"{sRequired} ships into the image but is not keyed."
        )


def testInputsBeyondTheDockerfileAreKeyed():
    """A two-file key would reuse an image after an entrypoint change."""
    listInputs = flistBuildInputPaths()
    for sRequired in (
        "docker/Dockerfile",
        "docker/entrypoint.sh",
        "docker/vaibifyDo.py",
        "vaibify/cli/commandBuild.py",
        "vaibify/docker/imageBuilder.py",
        "docs/vision.md",
    ):
        assert sRequired in listInputs, (
            f"{sRequired} can change the image but is not keyed."
        )


@pytest.mark.falsification
def testFreshBuildTriggerCoversEveryHashInput():
    """Kills: a build input that can merge without a fresh build.

    The hash and the workflow trigger are two statements of the same
    thing -- "these files change the image" -- written in different
    files, and they drifted immediately: the hash correctly covered
    director.py, the reproducibility clients and the staged docs
    while the trigger listed only docker/** and two builder modules.
    A change to a script COPYed into the image could merge with no
    fresh build while the hash said the image had changed.

    Mutation: drop a path from the workflow's pull_request paths.
    """
    import fnmatch
    import yaml

    pathWorkflow = (
        _PATH_REPO / ".github" / "workflows" / "freshImageBuild.yml"
    )
    dictWorkflow = yaml.safe_load(pathWorkflow.read_text())
    # ``on`` is a YAML 1.1 boolean; accept either spelling.
    dictOn = dictWorkflow.get("on", dictWorkflow.get(True))
    listPatterns = dictOn["pull_request"]["paths"]

    def fbCovered(sInput):
        for sPattern in listPatterns:
            if fnmatch.fnmatch(sInput, sPattern):
                return True
            sPrefix = sPattern.replace("/**", "/")
            if sPattern.endswith("/**") and sInput.startswith(sPrefix):
                return True
        return False

    listUncovered = [
        sInput for sInput in flistBuildInputPaths()
        if not fbCovered(sInput)
    ]
    assert not listUncovered, (
        "These files are hashed into the image key but no "
        "freshImageBuild.yml trigger path matches them, so changing "
        f"one merges without a fresh build: {listUncovered}"
    )


def testAbsentInputStillChangesTheKey():
    """A vanished input is a change, not a silent skip."""
    import computeBuildInputHash as moduleHash
    sBefore = moduleHash.fsComputeBuildInputHash()
    tOriginal = moduleHash.T_GENERATOR_SOURCES
    try:
        moduleHash.T_GENERATOR_SOURCES = tOriginal + (
            "vaibify/thisFileDoesNotExist.py",
        )
        assert moduleHash.fsComputeBuildInputHash() != sBefore
    finally:
        moduleHash.T_GENERATOR_SOURCES = tOriginal
    assert moduleHash.fsComputeBuildInputHash() == sBefore
