"""The host capability inventory is complete, current, and well-formed.

The inventory (``tests/hostCapabilityInventory.json``, generated by
``tools/generateHostCapabilityInventory.py``) is Phase A of the
host-mode plan: one row per call site that hands command text to the
container connection, each awaiting or carrying a reviewed disposition
saying whether that command is meaningful on a host. A record that can
silently fall behind the code reads as coverage, so the same scan runs
here in CI and fails on an added, removed, altered, duplicated, or
hand-edited row.

The undisposed budget is a fall-only ratchet held with NO slack: the
committed number must equal the actual undisposed count, so a new
undisposed call site cannot ship without an explicit, reviewed edit to
the committed inventory -- and that edit is where a rise is refused.
"""

import importlib.util
import json
import pathlib
import textwrap

PATH_REPOSITORY = pathlib.Path(__file__).resolve().parent.parent
PATH_INVENTORY = PATH_REPOSITORY / "tests" / "hostCapabilityInventory.json"
S_REGENERATE_INSTRUCTION = (
    "Regenerate with: python tools/generateHostCapabilityInventory.py "
    "--write, then review any new rows for a host-mode disposition."
)

_moduleGeneratorCache = None


def _fmoduleGenerator():
    """Import the inventory generator by path (tools/ is not a package)."""
    global _moduleGeneratorCache
    if _moduleGeneratorCache is None:
        pathTool = (
            PATH_REPOSITORY / "tools" / "generateHostCapabilityInventory.py"
        )
        specModule = importlib.util.spec_from_file_location(
            "generateHostCapabilityInventory", pathTool,
        )
        _moduleGeneratorCache = importlib.util.module_from_spec(specModule)
        specModule.loader.exec_module(_moduleGeneratorCache)
    return _moduleGeneratorCache


def _fdictCommittedInventory():
    """Return the checked-in inventory, parsed."""
    return json.loads(PATH_INVENTORY.read_text(encoding="utf-8"))


def testInventoryMatchesTheSource():
    """A fresh in-memory scan agrees with the committed JSON exactly.

    Any added, removed, altered, duplicated, or hand-edited row -- and a
    stale row count or budget field -- fails here, naming the drifted
    fingerprints so the fix is a reviewed regeneration, never a guess.
    """
    moduleGenerator = _fmoduleGenerator()
    dictDrift = moduleGenerator.fdictCompareAgainstSource(
        _fdictCommittedInventory(), moduleGenerator.flistScanPackage(),
    )
    listProblems = [
        f"{sKind}: {objProblem}"
        for sKind, listKindProblems in sorted(dictDrift.items())
        for objProblem in listKindProblems
    ]
    assert not listProblems, (
        "tests/hostCapabilityInventory.json has drifted from the source:\n"
        + "\n".join(listProblems) + "\n" + S_REGENERATE_INSTRUCTION
    )


def testEveryDispositionNamesAKnownFingerprint():
    """No disposition is orphaned on a fingerprint no row carries."""
    dictInventory = _fdictCommittedInventory()
    setKnown = {
        dictRow["sFingerprint"] for dictRow in dictInventory["listRows"]
    }
    listOrphaned = sorted(
        sFingerprint
        for sFingerprint in dictInventory["dictDispositions"]
        if sFingerprint not in setKnown
    )
    assert not listOrphaned, (
        "Dispositions recorded against fingerprints no row carries -- a "
        "judgement bound to code nobody can re-read: "
        f"{listOrphaned}"
    )


def testDispositionVocabularyIsClosed():
    """Every disposition uses the closed three-word vocabulary, filled in.

    A disposition outside the vocabulary is not comparable; one with no
    supporting symbols or rationale is a warrant with nothing read --
    the fingerprint is an identity, never a warrant.
    """
    moduleGenerator = _fmoduleGenerator()
    listViolations = moduleGenerator.flistDispositionSchemaViolations(
        _fdictCommittedInventory(),
    )
    assert not listViolations, "\n".join(listViolations)


def testUndisposedBudgetOnlyFalls():
    """The undisposed count never exceeds the budget, with no slack.

    Equality is required in both directions: above the budget means an
    undisposed call site shipped unreviewed, below it means dispositions
    were recorded without banking the fall -- slack a later regression
    could silently spend.
    """
    moduleGenerator = _fmoduleGenerator()
    dictInventory = _fdictCommittedInventory()
    iUndisposed = len(
        moduleGenerator.flistUndisposedFingerprints(dictInventory),
    )
    iBudget = dictInventory["iUndisposedSiteBudget"]
    assert iUndisposed <= iBudget, (
        f"{iUndisposed} rows are undisposed but the committed budget is "
        f"{iBudget}: new call sites shipped without a host-mode "
        f"disposition. Dispose them or, with review, raise the budget "
        f"explicitly. {S_REGENERATE_INSTRUCTION}"
    )
    assert iBudget == iUndisposed, (
        f"The committed budget ({iBudget}) must equal the actual "
        f"undisposed count ({iUndisposed}) exactly -- bank the fall. "
        f"{S_REGENERATE_INSTRUCTION}"
    )


def testUnknownCommandRowsSurvive(tmp_path):
    """An unreadable command argument yields an UNKNOWN row, never no row.

    The synthetic module hands the exec method its arguments through
    ``*`` unpacking, so the command expression cannot be identified.
    Completeness rests on seeing the call, not on decoding the command
    -- the withdrawn director module is the standing demonstration of
    what a decode-keyed record loses.
    """
    moduleGenerator = _fmoduleGenerator()
    pathSynthetic = tmp_path / "syntheticOpaqueLaunch.py"
    pathSynthetic.write_text(textwrap.dedent(
        """
        def fnLaunchOpaque(connection, sContainerId, listArguments):
            connection.ftResultExecuteCommand(sContainerId, *listArguments)
        """
    ), encoding="utf-8")
    listRows = moduleGenerator.flistScanModuleSource(
        "synthetic/syntheticOpaqueLaunch.py",
        pathSynthetic.read_text(encoding="utf-8"),
    )
    assert len(listRows) == 1, (
        f"expected exactly one row for the opaque launch, got {listRows}"
    )
    assert listRows[0]["sMethod"] == "ftResultExecuteCommand"
    assert listRows[0]["sCommandExpression"] == (
        moduleGenerator.S_UNKNOWN_COMMAND
    ), (
        "an unreadable command argument must surface as UNKNOWN, not "
        f"as {listRows[0]['sCommandExpression']!r}"
    )
