"""Route modules for the Vaibify FastAPI application."""

__all__ = [
    "stepRoutes",
    "fileRoutes",
    "draftRoutes",
    "syncRoutes",
    "testRoutes",
    "plotRoutes",
    "pipelineRoutes",
    "terminalRoutes",
    "workflowRoutes",
    "settingsRoutes",
    "figureRoutes",
    "scriptRoutes",
    "systemRoutes",
    "repoRoutes",
    "gitRoutes",
    "sessionRoutes",
    "levelRoutes",
    "reproducibilityRoutes",
]

from . import (
    stepRoutes,
    fileRoutes,
    draftRoutes,
    syncRoutes,
    testRoutes,
    plotRoutes,
    pipelineRoutes,
    terminalRoutes,
    workflowRoutes,
    settingsRoutes,
    figureRoutes,
    scriptRoutes,
    systemRoutes,
    repoRoutes,
    gitRoutes,
    sessionRoutes,
    levelRoutes,
    reproducibilityRoutes,
)
