"""Which PROOF level a published file's agreement belongs to.

The remote verifies compare a file on disk against the copy a remote
serves. That single comparison answers two different questions, and
until 2026-08-26 vaibify only asked one of them.

**Level 2 is about publishing the generating data.** The step outputs,
the scripts that made them, the inputs they read, the test standards,
the AI declaration, and the project definition that describes how they
fit together. If a published copy of any of those differs from the
researcher's, the data is not honestly published.

**Level 3 is about a third party reproducing it.** ``MANIFEST.sha256``,
``requirements.lock``, ``reproduce.sh``, ``.vaibify/environment.json``,
the ``Dockerfile`` and the dependency declarations. These are the
envelope: their EXISTENCE has always been an L3 criterion, but whether
the PUBLISHED copy matched was never checked at all. A pushed
``reproduce.sh`` that has drifted from the local one means reproduction
fails, and nothing said so.

The levels stay independent, which is why this module exists rather
than one widened set. Folding the envelope into the L2 comparison
would make Level 2 -- "I published my data" -- depend on artifacts
whose entire purpose is Level 3, so a researcher with a stale
``requirements.lock`` would be told their data was not published. That
is the wrong statement, and the ladder is explicitly built so a
higher rung never reaches down.

**Some tracked files belong to neither.** ``.vaibify/test_markers/**``
are regenerated by every local test run, so comparing them would put a
level into permanent flicker over "you ran your tests again" rather
than anything about publication. ``.gitignore`` governs the repository
rather than describing the work. Files here are not compared, and the
badge says so -- "not compared" rather than "not checked", because an
orange to-do the researcher cannot discharge is worse than no badge.

One network pass answers both questions: the verify compares the union
and each gate reads the paths it owns. The partition is derived here
rather than stamped into ``syncStatus.json``, so no persisted schema
changes and a cache written by an older hub still answers correctly.

**The Level 3 envelope criterion covers BOTH remotes (2026-08-26,
superseding an earlier same-day ruling).** It was first GitHub-only,
on the grounds that a Zenodo deposit is a data archive and a project
reproducing from the repository is doing nothing wrong. That was
reversed: Level 3 claims a third party can re-fetch and re-execute,
and GitHub is not an archive — repos are renamed, made private,
force-pushed, deleted. An envelope that lives only there gives the
claim the lifetime of a mutable host, so the reader who arrives after
the link rots has the data and no way to run it, while Level 3 told
them otherwise.

The objection that the envelope might be archived somewhere else does
not apply to vaibify v1.0, which supports exactly two remotes. Within
that closed world "the envelope is in the permanent archive" reduces
to "the envelope is in Zenodo"; the criterion generalises to "at least
one active repo and one complete archive" when more backends exist.

Two things landed WITH the Zenodo criterion rather than after it.
Zenodo's own GitHub integration archives a code release as a separate
record with its own DOI, so a project legitimately has a data deposit
AND a software deposit — both on Zenodo — and a check against the
single declared ``dictRemotes.zenodo`` record would fire falsely on
the arrangement Zenodo promotes; the verify therefore consults every
DECLARED record (``dictRemotes.zenodo.listRecords`` plus the primary),
and a file agrees with Zenodo when ANY declared record serves its
bytes. And Zenodo deposits are immutable, so re-agreement costs a new
published version rather than a push: Level 3 is a release-time
property, red through most of a project's life and green at
publication. That is judged correct, and the UI says so rather than
leaving it to a researcher's surprise.

The criterion has its own name — ``envelope-not-in-zenodo-archive`` —
because its remediation is "publish a deposit version", not "push".
"""

import posixpath

from .manifestWriter import flistCollectCanonicalRepoPaths
from .repoFiles import ffilesEnsureRepoFiles


__all__ = [
    "TUPLE_LEVEL3_ENVELOPE_PATHS",
    "TUPLE_UNCOMPARED_PREFIXES",
    "TUPLE_UNCOMPARED_PATHS",
    "I_PUBLICATION_SCOPE_VERSION",
    "fbCachedScopeIsCurrent",
    "flistCollectComparisonPaths",
    "fsetSelectLevel2Paths",
    "fsetSelectLevel3Paths",
    "flistSelectEnvelopePathsPresent",
    "fdictCountAtLevel2",
    "fbPathIsCompared",
]


S_PROJECTS_DIRECTORY = ".vaibify/projects"

# What "Level 2 is published" MEANS, as a version.
#
# A cached verify is evidence for a claim, and the claim is defined by
# the scope in force when the verify ran. When the scope grows, every
# existing cache becomes evidence for a WEAKER claim than the one the
# gate now makes -- and the gate could not tell, because a file that
# was never compared is absent from `listDiverged` exactly like a file
# that matched. That is not hypothetical: adding `project.json` to
# Level 2 left every project's GitHub row showing a green check while
# `project.json` sat beside it orange, never compared by anything.
#
# So the gate requires the cache to have been written under the
# CURRENT scope. A mismatch is not a failure of publication, it is an
# absence of evidence, and the remediation is one click of Verify now.
#
# Bump this whenever the membership rules change --
# TUPLE_LEVEL3_ENVELOPE_PATHS, TUPLE_UNCOMPARED_*, or what
# flistCollectComparisonPaths gathers. Do NOT bump it for a change
# that only alters which of the two levels an already-compared path
# lands in: the bytes were compared either way, and forcing a global
# re-verify for a reclassification would spend the researcher's time
# to learn nothing.
#
#
# Version 3 is the one bump that is about the COMPARISON AUTHORITY
# rather than the membership: the Zenodo verify began consulting every
# declared record instead of the single primary one. A version-2
# Zenodo cache is evidence about one deposit, not about the archive --
# its divergence entries say "not in THE record" where the Level 3
# criterion now asks "not in ANY declared record" -- so it cannot
# answer the current question and must not pretend to.
#
#   1  pre-split: the manifest set alone.
#   2  the union of both levels, adding the reproducibility envelope
#      and .vaibify/projects/*.json (2026-08-26).
#   3  the Zenodo comparison consults every declared record
#      (2026-08-26, same day -- the multi-record widening shipped
#      with the envelope-not-in-zenodo-archive criterion).
#   4  project.json stopped carrying the mutable sync bookkeeping
#      (dictSyncStatus and the Zenodo publish record moved to the
#      syncStatus.json sidecar, 2026-08-27). The membership did not
#      change, but what a compared project.json MEANS did: a
#      version-3 verdict about it -- match or divergence -- is a
#      statement about bytes the definition no longer contains, so
#      it cannot answer whether the CURRENT definition is published.
I_PUBLICATION_SCOPE_VERSION = 4

# The reproducibility envelope: what a third party needs in order to
# re-fetch and re-execute. Their presence is already checked by the L3
# artifact rows; this module is about whether the PUBLISHED copy
# agrees.
TUPLE_LEVEL3_ENVELOPE_PATHS = (
    "MANIFEST.sha256",
    "requirements.lock",
    "reproduce.sh",
    ".vaibify/environment.json",
    "Dockerfile",
    "requirements.txt",
    "environment.yml",
    "pyproject.toml",
)

# Tracked, published, and deliberately never compared. Test markers
# are rewritten by every local test run; comparing them would report
# "you ran your tests again" as a publication defect.
TUPLE_UNCOMPARED_PREFIXES = (".vaibify/test_markers/",)
TUPLE_UNCOMPARED_PATHS = (".gitignore",)


def flistCollectComparisonPaths(dictWorkflow, filesRepo):
    """Return every repo-relative path a remote verify should compare.

    The union of both levels' scopes. Paths that do not exist locally
    are left in: the caller hashes them and drops what it cannot read,
    which is the same filter it already applies to declared outputs.
    """
    filesRepo = ffilesEnsureRepoFiles(filesRepo)
    listPaths = list(flistCollectCanonicalRepoPaths(dictWorkflow))
    listPaths.extend(_flistProjectDefinitionPaths(filesRepo))
    listPaths.extend(TUPLE_LEVEL3_ENVELOPE_PATHS)
    listSeen = []
    for sPath in listPaths:
        if sPath and sPath not in listSeen and fbPathIsCompared(sPath):
            listSeen.append(sPath)
    return sorted(listSeen)


def _flistProjectDefinitionPaths(filesRepo):
    """Return the repo-relative project.json paths, or an empty list.

    The project definition is a LEVEL 2 artifact (2026-08-25 ruling):
    it describes how the published data was generated, which is what
    Level 2 publishes. A third party also needs it, but needing a file
    to reproduce does not make it envelope -- by that argument the
    data itself would be Level 3.
    """
    try:
        listNames = filesRepo.flistListJsonFilenames(
            S_PROJECTS_DIRECTORY,
        )
    except (OSError, ValueError, AttributeError):
        return []
    return [
        posixpath.join(S_PROJECTS_DIRECTORY, sName)
        for sName in (listNames or [])
    ]


def fbCachedScopeIsCurrent(dictStatus):
    """Return True iff a cached verify covered the CURRENT scope.

    False for every cache written before scope versioning existed,
    deliberately. Such a cache genuinely did not compare the files the
    current scope includes, so treating its silence as agreement is
    the defect this exists to remove -- and the researcher gets a row
    that says "verify again", not one that says "unpublished".
    """
    return (
        (dictStatus or {}).get("iScopeVersion")
        == I_PUBLICATION_SCOPE_VERSION
    )


def fbPathIsCompared(sPath):
    """Return False for a tracked path no verify should compare."""
    if sPath in TUPLE_UNCOMPARED_PATHS:
        return False
    return not sPath.startswith(TUPLE_UNCOMPARED_PREFIXES)


def fsetSelectLevel3Paths(listPaths):
    """Return the envelope subset of ``listPaths``."""
    setEnvelope = set(TUPLE_LEVEL3_ENVELOPE_PATHS)
    return {sPath for sPath in listPaths if sPath in setEnvelope}


def flistSelectEnvelopePathsPresent(filesRepo):
    """Return the envelope paths that actually exist in the repo.

    Every path probed here must be sampled by the poll snapshot
    (``repoFiles.TUPLE_SNAPSHOT_CONTENT_PATHS``), because the adapter
    the file-status poll passes raises ``KeyError`` for anything it did
    not sample rather than guessing. The subset is pinned by
    ``testPublicationScopeSeparatesTheLevels``.
    """
    filesRepo = ffilesEnsureRepoFiles(filesRepo)
    return [
        sPath for sPath in TUPLE_LEVEL3_ENVELOPE_PATHS
        if filesRepo.fbIsFile(sPath)
    ]


def fdictCountAtLevel2(dictStatus):
    """Return ``{iTotalFiles, iMatching, iDivergedCount}`` over L2 only.

    One verify writes one set of counts spanning both levels, so the
    Level 2 rows would otherwise report an envelope divergence as a
    reason the researcher's DATA is unpublished -- the exact statement
    the split exists to prevent, and the one the gate stopped making
    while the row kept making it.

    A cache written before the split carries no ``listComparedPaths``.
    Its compared set was entirely Level 2 material, so its aggregate
    IS the Level 2 answer and is returned unchanged; no project loses
    a verified row by upgrading.
    """
    listCompared = (dictStatus or {}).get("listComparedPaths")
    iTotal = int((dictStatus or {}).get("iTotalFiles") or 0)
    listDiverged = (dictStatus or {}).get("listDiverged") or []
    if listCompared is None:
        return {
            "iTotalFiles": iTotal,
            "iMatching": int((dictStatus or {}).get("iMatching") or 0),
            "iDivergedCount": len(listDiverged),
        }
    setLevel2 = fsetSelectLevel2Paths(listCompared)
    setDiverged = {
        (dictEntry or {}).get("sPath") for dictEntry in listDiverged
    }
    iDiverged = len(setLevel2 & setDiverged)
    return {
        "iTotalFiles": len(setLevel2),
        "iMatching": len(setLevel2) - iDiverged,
        "iDivergedCount": iDiverged,
    }


def fsetSelectLevel2Paths(listPaths):
    """Return the published-data subset of ``listPaths``.

    Defined as the complement of the envelope within the compared set,
    rather than as its own list. A new artifact category therefore
    lands in Level 2 by default, which is the safe direction: Level 2
    is the claim a researcher makes first and the one whose scope
    should not silently shrink. An envelope addition is an explicit
    edit to the tuple above.
    """
    setEnvelope = set(TUPLE_LEVEL3_ENVELOPE_PATHS)
    return {
        sPath for sPath in listPaths
        if sPath not in setEnvelope and fbPathIsCompared(sPath)
    }
