"""Which PROOF level a published file's agreement belongs to.

The remote verifies compare a file on disk against the copy a remote
serves. That single comparison answers two different questions, and
until 2026-08-26 vaibify only asked one of them.

**Level 2 is about publishing the generating data.** The step outputs,
the scripts that made them, the inputs they read, the test standards,
the AI declaration, and the project definition that describes how they
fit together. If a published copy of any of those differs from the
researcher's, the data is not honestly published.

**Level 3 is about a third party reproducing it.** ``MANIFEST.sha256``,
``requirements.lock``, ``reproduce.sh``, ``.vaibify/environment.json``,
the ``Dockerfile`` and the dependency declarations. These are the
envelope: their EXISTENCE has always been an L3 criterion, but whether
the PUBLISHED copy matched was never checked at all. A pushed
``reproduce.sh`` that has drifted from the local one means reproduction
fails, and nothing said so.

The levels stay independent, which is why this module exists rather
than one widened set. Folding the envelope into the L2 comparison
would make Level 2 -- "I published my data" -- depend on artifacts
whose entire purpose is Level 3, so a researcher with a stale
``requirements.lock`` would be told their data was not published. That
is the wrong statement, and the ladder is explicitly built so a
higher rung never reaches down.

**Some tracked files belong to neither.** ``.vaibify/test_markers/**``
are regenerated by every local test run, so comparing them would put a
level into permanent flicker over "you ran your tests again" rather
than anything about publication. ``.gitignore`` governs the repository
rather than describing the work. Files here are not compared, and the
badge says so -- "not compared" rather than "not checked", because an
orange to-do the researcher cannot discharge is worse than no badge.

One network pass answers both questions: the verify compares the union
and each gate reads the paths it owns. The partition is derived here
rather than stamped into ``syncStatus.json``, so no persisted schema
changes and a cache written by an older hub still answers correctly.

**The Level 3 envelope criterion is GitHub-only, deliberately
(2026-08-26 ruling).** The symmetric Zenodo criterion was considered
and declined: a Zenodo deposit is a data archive, and a workflow that
never places ``reproduce.sh`` or the ``Dockerfile`` in its deposit is
doing nothing wrong. Applying the criterion there would block Level 3
for every project that archives data to a DOI and reproduces from the
repository — which is the ordinary arrangement. Reproduction fetches
from the repo; the DOI is the citable archive of results. If that ever
stops being true for a project, the honest form is an opt-in per
project, not an unconditional criterion.
"""

import posixpath

from .manifestWriter import flistCollectCanonicalRepoPaths
from .repoFiles import ffilesEnsureRepoFiles


__all__ = [
    "TUPLE_LEVEL3_ENVELOPE_PATHS",
    "TUPLE_UNCOMPARED_PREFIXES",
    "TUPLE_UNCOMPARED_PATHS",
    "flistCollectComparisonPaths",
    "fsetSelectLevel2Paths",
    "fsetSelectLevel3Paths",
    "fbPathIsCompared",
]


S_PROJECTS_DIRECTORY = ".vaibify/projects"

# The reproducibility envelope: what a third party needs in order to
# re-fetch and re-execute. Their presence is already checked by the L3
# artifact rows; this module is about whether the PUBLISHED copy
# agrees.
TUPLE_LEVEL3_ENVELOPE_PATHS = (
    "MANIFEST.sha256",
    "requirements.lock",
    "reproduce.sh",
    ".vaibify/environment.json",
    "Dockerfile",
    "requirements.txt",
    "environment.yml",
    "pyproject.toml",
)

# Tracked, published, and deliberately never compared. Test markers
# are rewritten by every local test run; comparing them would report
# "you ran your tests again" as a publication defect.
TUPLE_UNCOMPARED_PREFIXES = (".vaibify/test_markers/",)
TUPLE_UNCOMPARED_PATHS = (".gitignore",)


def flistCollectComparisonPaths(dictWorkflow, filesRepo):
    """Return every repo-relative path a remote verify should compare.

    The union of both levels' scopes. Paths that do not exist locally
    are left in: the caller hashes them and drops what it cannot read,
    which is the same filter it already applies to declared outputs.
    """
    filesRepo = ffilesEnsureRepoFiles(filesRepo)
    listPaths = list(flistCollectCanonicalRepoPaths(dictWorkflow))
    listPaths.extend(_flistProjectDefinitionPaths(filesRepo))
    listPaths.extend(TUPLE_LEVEL3_ENVELOPE_PATHS)
    listSeen = []
    for sPath in listPaths:
        if sPath and sPath not in listSeen and fbPathIsCompared(sPath):
            listSeen.append(sPath)
    return sorted(listSeen)


def _flistProjectDefinitionPaths(filesRepo):
    """Return the repo-relative project.json paths, or an empty list.

    The project definition is a LEVEL 2 artifact (2026-08-25 ruling):
    it describes how the published data was generated, which is what
    Level 2 publishes. A third party also needs it, but needing a file
    to reproduce does not make it envelope -- by that argument the
    data itself would be Level 3.
    """
    try:
        listNames = filesRepo.flistListJsonFilenames(
            S_PROJECTS_DIRECTORY,
        )
    except (OSError, ValueError, AttributeError):
        return []
    return [
        posixpath.join(S_PROJECTS_DIRECTORY, sName)
        for sName in (listNames or [])
    ]


def fbPathIsCompared(sPath):
    """Return False for a tracked path no verify should compare."""
    if sPath in TUPLE_UNCOMPARED_PATHS:
        return False
    return not sPath.startswith(TUPLE_UNCOMPARED_PREFIXES)


def fsetSelectLevel3Paths(listPaths):
    """Return the envelope subset of ``listPaths``."""
    setEnvelope = set(TUPLE_LEVEL3_ENVELOPE_PATHS)
    return {sPath for sPath in listPaths if sPath in setEnvelope}


def fsetSelectLevel2Paths(listPaths):
    """Return the published-data subset of ``listPaths``.

    Defined as the complement of the envelope within the compared set,
    rather than as its own list. A new artifact category therefore
    lands in Level 2 by default, which is the safe direction: Level 2
    is the claim a researcher makes first and the one whose scope
    should not silently shrink. An envelope addition is an explicit
    edit to the tuple above.
    """
    setEnvelope = set(TUPLE_LEVEL3_ENVELOPE_PATHS)
    return {
        sPath for sPath in listPaths
        if sPath not in setEnvelope and fbPathIsCompared(sPath)
    }
