"""Render ``reproduce.sh`` from a workflow + the L3 envelope.

The output script is the canonical "stock-host reproduction recipe":
given the project repo plus the AICS L3 envelope
(``.vaibify/environment.json``, ``requirements.lock``,
``MANIFEST.sha256``), running ``./reproduce.sh`` on a fresh host
with Docker installed should reproduce every declared artefact.

The script lives at ``<projectRepo>/reproduce.sh`` so it is part of
the repo (and therefore pinned in ``MANIFEST.sha256``). The
``manifestWriter`` envelope already covers files at the repo root, so
no additional wiring is needed beyond regenerating the manifest after
``fnGenerateReproduceScript`` writes a new script body.
"""

import os
import stat
from pathlib import Path


__all__ = [
    "S_REPRODUCE_SCRIPT_FILENAME",
    "fnGenerateReproduceScript",
    "fsRenderReproduceScript",
    "flistRenderStepCommands",
]


S_REPRODUCE_SCRIPT_FILENAME = "reproduce.sh"

_S_SCRIPT_PREAMBLE = """\
#!/usr/bin/env bash
# Auto-generated by vaibify. Reproduces this workflow on a stock host.
# Requires: docker, jq, sha256sum.
set -euo pipefail

sImageRef=$(jq -r .dictContainer.sImageDigest \\
    .vaibify/environment.json)
if [ -z "$sImageRef" ] || [ "$sImageRef" = "null" ]; then
    echo "error: sImageDigest missing from .vaibify/environment.json" >&2
    exit 2
fi

docker pull "$sImageRef"
docker run --rm -v "$PWD":/work -w /work "$sImageRef" bash -c '
  set -euo pipefail
  pip install --require-hashes -r requirements.lock
"""

_S_SCRIPT_EPILOGUE = """\
  sha256sum -c MANIFEST.sha256
'
"""


def fnGenerateReproduceScript(sProjectRepo, dictWorkflow):
    """Write ``reproduce.sh`` to the project repo root, chmod +x.

    Idempotent: writing the same workflow twice produces the same
    bytes. Returns the absolute path written so callers can update
    the manifest or surface the path to the user.
    """
    sScript = fsRenderReproduceScript(dictWorkflow)
    pathOutput = Path(sProjectRepo) / S_REPRODUCE_SCRIPT_FILENAME
    pathOutput.write_text(sScript, encoding="utf-8")
    _fnMarkExecutable(pathOutput)
    return str(pathOutput)


def _fnMarkExecutable(pathOutput):
    """Add owner+group+other execute bits to the script file."""
    iMode = pathOutput.stat().st_mode
    pathOutput.chmod(iMode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def fsRenderReproduceScript(dictWorkflow):
    """Return the full ``reproduce.sh`` body as a string.

    Pure function so tests can compare against a fixture without
    touching the filesystem. Step commands are rendered as
    indented continuations of the container ``bash -c`` block.
    """
    listStepLines = flistRenderStepCommands(dictWorkflow)
    sBody = "\n".join("  " + sLine for sLine in listStepLines)
    if sBody:
        sBody = sBody + "\n"
    return _S_SCRIPT_PREAMBLE + sBody + _S_SCRIPT_EPILOGUE


def flistRenderStepCommands(dictWorkflow):
    """Return the shell lines that execute every workflow step in order.

    Each step contributes its ``saDataCommands`` then
    ``saPlotCommands``; ``cd`` into the step directory keeps relative
    paths inside the step's working tree the way the live runner does.
    Steps with no commands (e.g., ai-declaration) are skipped.
    """
    listLines = []
    for dictStep in (dictWorkflow or {}).get("listSteps", []) or []:
        listLines.extend(_flistRenderOneStep(dictStep))
    return listLines


def _flistRenderOneStep(dictStep):
    """Return the shell lines for one step's commands."""
    if not isinstance(dictStep, dict):
        return []
    listCommands = _flistGatherStepCommands(dictStep)
    if not listCommands:
        return []
    sDirectory = (dictStep.get("sDirectory") or "").strip()
    listLines = [f"# Step: {dictStep.get('sName', '?')}"]
    if sDirectory and sDirectory != ".":
        listLines.append(f"( cd {_fsShellQuote(sDirectory)} && \\")
        for sCommand in listCommands:
            listLines.append(f"    {sCommand} && \\")
        listLines[-1] = listLines[-1][:-4]
        listLines.append(")")
    else:
        listLines.extend(listCommands)
    return listLines


def _flistGatherStepCommands(dictStep):
    """Return data-then-plot commands for one step, skipping empties."""
    listOut = []
    for sKey in ("saDataCommands", "saPlotCommands"):
        for sCommand in dictStep.get(sKey, []) or []:
            sStripped = (sCommand or "").strip()
            if sStripped:
                listOut.append(sStripped)
    return listOut


def _fsShellQuote(sValue):
    """Return sValue as a POSIX single-quoted shell argument."""
    return "'" + sValue.replace("'", "'\\''") + "'"
