"""Render ``reproduce.sh`` from a workflow + the L3 envelope.

The output script is the canonical "stock-host reproduction recipe":
given the project repo plus the PROOF L3 envelope
(``.vaibify/environment.json``, ``requirements.lock``,
``MANIFEST.sha256``), running ``./reproduce.sh`` on a fresh host
with Docker installed should reproduce every declared artefact.

The script lives at ``<projectRepo>/reproduce.sh`` so it is part of
the repo (and therefore pinned in ``MANIFEST.sha256``). The
``manifestWriter`` envelope already covers files at the repo root, so
no additional wiring is needed beyond regenerating the manifest after
``fsGenerateReproduceScript`` writes a new script body.

Note on host-vs-container paths: ``sProjectRepo`` here is the
container-side path (e.g. ``/workspace/foo``). The FastAPI process
runs on the host, so a naive ``Path.write_text`` would write to a
host file that happens to share the container's absolute path —
which silently leaks artefacts onto the host and never reaches the
repo inside the container. The writer therefore takes a docker
connection and routes the bytes through ``fnWriteFile`` /
``ftResultExecuteCommand``.
"""

import posixpath
import re

from vaibify.reproducibility.repoFiles import fsShellQuotePosix


__all__ = [
    "S_REPRODUCE_SCRIPT_FILENAME",
    "S_REPRODUCTION_REPO_ROOT",
    "fsGenerateReproduceScript",
    "fsRenderReproduceScript",
    "flistRenderStepCommands",
]


S_REPRODUCE_SCRIPT_FILENAME = "reproduce.sh"

# The repo root AS THE REPRODUCER SEES IT. The generated script runs
# ``docker run -v "$PWD":/work -w /work``, so every step command must
# be substituted against this root, never against the authoring
# container's ``/workspace/<repo>``: that path names a directory the
# reproducer's container does not have. Absolute paths under this root
# are correct from inside any step directory the body ``cd``s into,
# which relative ones would not be. Changing this constant means
# changing the ``docker run`` mount in the preamble with it.
S_REPRODUCTION_REPO_ROOT = "/work"

# The reproduction body (step comments and commands) is delivered to
# the container's shell through a *quoted* heredoc, never through a
# host-side ``bash -c '...'`` argument. A quoted heredoc passes its
# body to the container verbatim: the host shell performs no
# expansion and no quote interpretation, so a single quote in a step
# command — or a workflow-controlled step name — cannot close a host
# argument and inject a command onto the reproducer's host. The one
# residual escape is a body line that forges the terminator; that is
# rejected before the script is emitted (``_fnRejectDelimiterForgery``).
_S_HEREDOC_DELIMITER = "VAIBIFY_REPRODUCE_EOF"

_RE_CONTROL_CHARACTERS = re.compile(r"[\x00-\x1f\x7f]")

# The environment key holding the epoch the pinned artefacts were
# dated and salted with. Read on the reproducing host and handed to
# the container as a real environment entry, because a *quoted*
# heredoc — the thing that keeps workflow-controlled step text off the
# host shell — cannot carry a host value into its body.
_S_ENVELOPE_EPOCH_KEY = "iSourceDateEpoch"

_S_HOST_PREAMBLE = """\
#!/usr/bin/env bash
# Auto-generated by vaibify. Reproduces this workflow on a stock host.
# Requires: docker, jq, sha256sum.
set -euo pipefail

sImageRef=$(jq -r .dictContainer.sImageDigest \\
    .vaibify/environment.json)
if [ -z "$sImageRef" ] || [ "$sImageRef" = "null" ]; then
    echo "error: sImageDigest missing from .vaibify/environment.json" >&2
    exit 2
fi

# The epoch RECORDED when the manifest was pinned, never one derived
# from HEAD here: the commit that published the manifest moved HEAD,
# so a re-derived epoch would date and salt every figure differently
# from the pinned ones and the closing sha256sum -c could not pass.
sSourceDateEpoch=$(jq -r '.{sEpochKey} // ""' \\
    .vaibify/environment.json)
case "$sSourceDateEpoch" in
    ''|0|*[!0-9]*) sSourceDateEpoch="" ;;
esac
if [ -z "$sSourceDateEpoch" ]; then
    echo "vaibify: .vaibify/environment.json records no {sEpochKey};" >&2
    echo "  this run's figures and archives will carry its wall-clock" >&2
    echo "  time, so sha256sum -c will report every timestamped" >&2
    echo "  artefact (PDF, EPS, PS, SVG) as differing. Regenerate the" >&2
    echo "  environment envelope on the authoring machine to fix it." >&2
fi

# A pull that fails over an image already on this host is survivable
# for the AUTHOR and fatal for everyone else, so say which one happened
# rather than silently doing either. The pinned reference is a digest,
# so a local copy at that digest IS the pinned image; what a failed
# pull proves is that nobody ELSE can run this script yet.
if ! docker pull "$sImageRef"; then
    if docker image inspect "$sImageRef" > /dev/null 2>&1; then
        echo "vaibify: could not pull $sImageRef; running the copy" >&2
        echo "  already on this host. A reproducer without that copy" >&2
        echo "  cannot run this script -- publish the image." >&2
    else
        echo "error: cannot pull $sImageRef and no local copy exists" >&2
        exit 2
    fi
fi

# --entrypoint bash bypasses the image's development entrypoint. That
# entrypoint configures an interactive workspace: it writes system git
# config (which needs the root phase this invocation does not run, so
# it exits non-zero here), clones the project's configured repos, and
# installs agent tooling. A reproduction wants none of it -- it wants
# the pinned steps, over the mounted repo, and nothing that reaches the
# network or the wall clock.
docker run --rm -i --entrypoint bash \\
    -e "SOURCE_DATE_EPOCH=$sSourceDateEpoch" \\
    -v "$PWD":/work -w /work "$sImageRef" \\
    -s <<'{sDelimiter}'
""".format(
    sDelimiter=_S_HEREDOC_DELIMITER,
    sEpochKey=_S_ENVELOPE_EPOCH_KEY,
)


def _fsBuildContainerPreamble():
    """Return the heredoc lines that run before the first step command.

    Applies the same two guarantees the live runner applies — the
    recorded ``SOURCE_DATE_EPOCH`` and matplotlib's ``svg.hashsalt``
    derived from it — by calling the runner's own salt builder rather
    than respelling the rcParam here. A second authority on what the
    determinism guarantee *is* would drift from the runner, and the two
    lanes disagreeing is the defect this exists to fix.

    An absent epoch is unset rather than exported empty (an empty
    ``SOURCE_DATE_EPOCH`` is a value some tools reject and others read
    as "now", which is two wrong answers), and the host preamble has
    already said on stderr what that costs.
    """
    from vaibify.gui.determinismEnvironment import (
        fsBuildMatplotlibSaltShell,
    )
    return "\n".join([
        "set -euo pipefail",
        'if [ -n "${SOURCE_DATE_EPOCH:-}" ]; then',
        "    " + fsBuildMatplotlibSaltShell("$SOURCE_DATE_EPOCH"),
        "else",
        "    unset SOURCE_DATE_EPOCH",
        "fi",
        "pip install --require-hashes -r requirements.lock",
        "",
    ])


_S_SCRIPT_EPILOGUE = """\
sha256sum -c MANIFEST.sha256
{sDelimiter}
""".format(sDelimiter=_S_HEREDOC_DELIMITER)


def fsGenerateReproduceScript(
    sProjectRepo, dictWorkflow,
    connectionDocker=None, sContainerId="",
):
    """Write ``reproduce.sh`` inside the container at the project repo root.

    Idempotent: writing the same workflow twice produces the same
    bytes. Returns the container-absolute path written so callers can
    update the manifest or surface the path to the user.

    Routes the write through ``connectionDocker.fnWriteFile`` because
    ``sProjectRepo`` is a container path (e.g. ``/workspace/foo``);
    a host-side ``Path.write_text`` would land in a host file at the
    same absolute path rather than inside the container. Both
    ``connectionDocker`` and ``sContainerId`` are required; passing
    either as falsy raises ``ValueError`` so callers can never silently
    fall back to the host path.
    """
    from vaibify.config.connectionAvailability import (
        fbDockerReachable,
    )
    if not fbDockerReachable(connectionDocker) or not sContainerId:
        raise ValueError(
            "fsGenerateReproduceScript requires a docker connection "
            "and container id; reproduce.sh must be written inside "
            "the container because sProjectRepo is a container path."
        )
    sScript = fsRenderReproduceScript(dictWorkflow)
    sContainerPath = posixpath.join(
        sProjectRepo, S_REPRODUCE_SCRIPT_FILENAME,
    )
    connectionDocker.fnWriteFile(
        sContainerId, sContainerPath, sScript.encode("utf-8"),
    )
    _fnMarkExecutableInContainer(
        connectionDocker, sContainerId, sContainerPath,
    )
    return sContainerPath


def _fnMarkExecutableInContainer(
    connectionDocker, sContainerId, sContainerPath,
):
    """Add owner+group+other execute bits to a container-side file."""
    sCommand = "chmod a+x " + _fsShellQuote(sContainerPath)
    connectionDocker.ftResultExecuteCommand(sContainerId, sCommand)


def fsRenderReproduceScript(dictWorkflow):
    """Return the full ``reproduce.sh`` body as a string.

    Pure function so tests can compare against a fixture without
    touching the filesystem. Step commands are rendered as lines of
    the container heredoc body; the host shell never interprets them.
    """
    listStepLines = flistRenderStepCommands(dictWorkflow)
    _fnRejectUnresolvedTokens(listStepLines)
    sBody = "\n".join(listStepLines)
    if sBody:
        sBody = sBody + "\n"
    sScript = (
        _S_HOST_PREAMBLE + _fsBuildContainerPreamble()
        + sBody + _S_SCRIPT_EPILOGUE
    )
    _fnRejectDelimiterForgery(sScript)
    return sScript


def _fnRejectDelimiterForgery(sScript):
    """Refuse to emit a script whose body forges the heredoc terminator.

    The reproduction body reaches the container shell through a quoted
    heredoc, so a step command or name occupying a line equal to the
    terminator would close the heredoc early and hand the remaining
    lines to the host shell — the exact breakout the heredoc exists to
    prevent. The terminator appears legitimately on exactly one line
    (the closing delimiter); any other exact-line occurrence is a
    tampering attempt, so fail loud rather than emit an injectable
    script.
    """
    iExactMatches = sum(
        1 for sLine in sScript.splitlines()
        if sLine == _S_HEREDOC_DELIMITER
    )
    if iExactMatches != 1:
        raise ValueError(
            "reproduce.sh body contains the reserved heredoc "
            "terminator; refusing to emit an injectable script."
        )


def flistRenderStepCommands(dictWorkflow):
    """Return the shell lines that execute every workflow step in order.

    Each step contributes its ``saDataCommands`` then
    ``saPlotCommands``; ``cd`` into the step directory keeps relative
    paths inside the step's working tree the way the live runner does.
    Steps with no commands (e.g., ai-declaration) are skipped.
    """
    dictVariables = _fdictBuildReproductionVariables(dictWorkflow)
    listLines = []
    for dictStep in (dictWorkflow or {}).get("listSteps", []) or []:
        listLines.extend(_flistRenderOneStep(dictStep, dictVariables))
    return listLines


def _fdictBuildReproductionVariables(dictWorkflow):
    """Return the substitution variables as seen from the reproduction mount.

    The same two builders the live runner uses, rebuilt against
    :data:`S_REPRODUCTION_REPO_ROOT`. Sharing the builders is the
    point: a private copy here would drift from the runner, and a
    reproduction that resolves its paths differently from the run it
    reproduces is not a reproduction.
    """
    from vaibify.gui.workflowManager import (
        fdictBuildGlobalVariablesForRoot,
        fdictBuildStepVariables,
    )
    dictWorkflow = dictWorkflow or {}
    dictVariables = fdictBuildGlobalVariablesForRoot(
        dictWorkflow, S_REPRODUCTION_REPO_ROOT,
    )
    listSteps = _flistStepsSafeToIndex(dictWorkflow.get("listSteps"))
    if listSteps:
        dictVariables.update(
            fdictBuildStepVariables(
                {"listSteps": listSteps}, dictVariables,
            ),
        )
    return dictVariables


def _flistStepsSafeToIndex(listSteps):
    """Return listSteps with non-dict entry replaced by an empty step.

    This renderer skips a corrupt step rather than refusing the whole
    script, and the shared variable builder does not -- it indexes
    ``sStepId`` straight off each entry. REPLACED, never filtered: the
    deprecated positional ``{StepNN.stem}`` form is keyed on position,
    so dropping an entry would silently renumber every step after it
    and resolve those tokens to the wrong file. An empty dict declares
    no outputs, so it contributes no variables and holds its place.
    """
    if not isinstance(listSteps, list):
        return []
    return [
        dictStep if isinstance(dictStep, dict) else {}
        for dictStep in listSteps
    ]


def _flistRenderOneStep(dictStep, dictVariables):
    """Return the shell lines for one step's commands."""
    if not isinstance(dictStep, dict):
        return []
    listCommands = _flistGatherStepCommands(dictStep, dictVariables)
    if not listCommands:
        return []
    from vaibify.gui.workflowManager import fsResolveCommand
    sName = _fsSanitizeCommentText(dictStep.get("sName", "?"))
    sDirectory = fsResolveCommand(
        (dictStep.get("sDirectory") or "").strip(), dictVariables,
    )
    listLines = [f"# Step: {sName}"]
    if sDirectory and sDirectory != ".":
        listLines.append(f"( cd {_fsShellQuote(sDirectory)} && \\")
        for sCommand in listCommands:
            listLines.append(f"    {sCommand} && \\")
        listLines[-1] = listLines[-1][:-4]
        listLines.append(")")
    else:
        listLines.extend(listCommands)
    return listLines


def _fsSanitizeCommentText(sValue):
    """Collapse a value to a single safe line for a shell comment.

    The step name is workflow-controlled (it originates from
    ``project.json``, which the in-container agent can write).
    Rendered raw into the reproduction body, a newline would end the
    ``# Step:`` comment and turn the remainder of the name into live
    script. Replacing every control character (newlines, tabs, escape
    sequences) with a space and collapsing the result keeps the name a
    human-readable, single-line label that can never leave its comment.
    """
    sCleaned = _RE_CONTROL_CHARACTERS.sub(" ", str(sValue))
    return " ".join(sCleaned.split()) or "?"


def _flistGatherStepCommands(dictStep, dictVariables):
    """Return data-then-plot commands for one step, skipping empties.

    Each command is substituted the way the live runner substitutes
    it. Copying the raw text instead emitted a script that created a
    literal ``{sPlotDirectory}`` directory and failed on the first
    cross-step path -- while ``fbVerifyReproduceScript`` reported it
    green, because that gate checks existence and manifest membership,
    not whether the script can run.
    """
    from vaibify.gui.workflowManager import fsResolveCommand
    listOut = []
    for sKey in ("saDataCommands", "saPlotCommands"):
        for sCommand in dictStep.get(sKey, []) or []:
            sStripped = (sCommand or "").strip()
            if sStripped:
                listOut.append(
                    fsResolveCommand(sStripped, dictVariables),
                )
    return listOut


def _fnRejectUnresolvedTokens(listStepLines):
    """Refuse to emit a script still carrying vaibify template tokens.

    The same fail-loud stance as :func:`_fnRejectDelimiterForgery`,
    for the same reason: a script that cannot execute is worse than no
    script, because the L3 gate that reads it reports a green row
    either way and the researcher only finds out at the end of an
    hours-long rebuild. A residual token here means the workflow
    references an output no step declares -- ``resolve-commands``
    reports which.
    """
    from vaibify.gui.workflowManager import flistResidualWorkflowTokens
    listTokens = []
    for sLine in listStepLines:
        listTokens.extend(flistResidualWorkflowTokens(sLine))
    if listTokens:
        raise ValueError(
            "reproduce.sh commands carry unresolved tokens "
            + ", ".join(sorted(set(listTokens)))
            + "; every cross-step reference must name a declared "
            + "output (see resolve-commands)."
        )


def _fsShellQuote(sValue):
    """Return sValue as a POSIX single-quoted shell argument."""
    return fsShellQuotePosix(sValue)
