"""The canonical on-disk form of a generated ledger.

Three files in ``tests/`` are ledgers: a machine scan of the source,
merged with a reviewer's recorded judgement, checked in so that a drift
check can compare the two. ``mutationInventory.json``,
``hostCapabilityInventory.json`` and ``styleInventory.json`` are all
built and rewritten by a tool, never hand-edited, and each has its own
generator because each scans for something different.

What they share is a *shape problem*, and it is the reason this module
exists rather than three copies of ``json.dumps``. A ledger is
regenerated by every branch that touches the source it scans, so its
on-disk layout decides how often two branches that changed unrelated
things nevertheless collide. Three properties follow, and each was
adopted in response to a collision that had already happened:

**One record per line.** A record spread over twenty lines means git's
three lines of context cover a fraction of one record, so any two
changes within about twenty-five lines conflict -- including two
branches adding rows for entirely different modules that happen to sort
near each other. One line per record widens that window from a fraction
of a record to three whole records, and it makes the diff readable: a
changed record shows as one changed line instead of a wall of
punctuation.

**No derived counts.** ``mutationInventory.json`` carried three fields
holding the lengths of three lists in the same file. They sat at the
top, so *every* branch that added or removed a single row rewrote the
same three lines -- a guaranteed conflict between two branches with
nothing else in common. They were also redundant: each drift check
already compared its recorded list against a fresh scan, which is the
comparison that matters. A number derived from data beside it is not a
check, it is a second copy.

**A byte-exact canonical form.** The rendering here is the only
rendering. ``tests/testLedgerFormatIsCanonical.py`` fails when a
checked-in ledger does not equal what this module would produce from
its own parsed contents, so a hand-edit that reformats a file cannot
survive. That test exists because it happened: a ledger was once
rewritten with an ad-hoc ``json.dumps(..., indent=1)`` while its
generator wrote ``indent=2``, so the committed file disagreed with its
own generator and the next ``--write`` rewrote all ten thousand lines.
Every drift check parses JSON, so not one of them could see it.

Note the division of labour. The drift checks own *content* -- whether
the record still describes the source. This module owns *form* only. A
file can be canonically formatted and badly wrong.
"""

import json

# Records sit two levels in: one for the ledger object, one for the
# collection. Purely cosmetic -- leading whitespace has no bearing on
# how git resolves a conflict.
S_RECORD_INDENT = "    "


def fsRenderLedger(dictLedger, tRecordCollectionKeys):
    """Return the canonical text for one ledger, trailing newline included.

    ``tRecordCollectionKeys`` names the top-level keys holding record
    collections -- a list of records, or a dict keyed by fingerprint.
    Those render one record per line. Every other key renders as
    ordinary indented JSON, which is what a scalar, a purpose string, or
    a small budget mapping wants.

    Top-level keys keep the generator's insertion order, so a generator
    can put its purpose statement first. Keys *within* a record are
    sorted, so a record's on-disk form cannot depend on the order the
    scanner happened to build it in.
    """
    listKeys = list(dictLedger)
    listLines = ["{"]
    for iIndex, sKey in enumerate(listKeys):
        sTrailing = "" if iIndex == len(listKeys) - 1 else ","
        if sKey in tRecordCollectionKeys:
            listLines.extend(
                _flistRenderRecords(sKey, dictLedger[sKey], sTrailing),
            )
            continue
        sRendered = json.dumps(dictLedger[sKey], indent=2, sort_keys=True)
        sIndented = "\n  ".join(sRendered.split("\n"))
        listLines.append(f"  {json.dumps(sKey)}: {sIndented}{sTrailing}")
    listLines.append("}")
    return "\n".join(listLines) + "\n"


def _flistRenderRecords(sKey, jsonRecords, sTrailing):
    """Return the lines for one record collection, one record per line."""
    if isinstance(jsonRecords, dict):
        sOpen, sClose = "{", "}"
        listEntries = [
            f"{json.dumps(sName)}: "
            f"{json.dumps(jsonRecords[sName], sort_keys=True)}"
            for sName in sorted(jsonRecords)
        ]
    else:
        sOpen, sClose = "[", "]"
        listEntries = [
            json.dumps(jsonRecord, sort_keys=True)
            for jsonRecord in jsonRecords
        ]
    if not listEntries:
        return [f"  {json.dumps(sKey)}: {sOpen}{sClose}{sTrailing}"]
    listLines = [f"  {json.dumps(sKey)}: {sOpen}"]
    for iIndex, sEntry in enumerate(listEntries):
        sComma = "" if iIndex == len(listEntries) - 1 else ","
        listLines.append(f"{S_RECORD_INDENT}{sEntry}{sComma}")
    listLines.append(f"  {sClose}{sTrailing}")
    return listLines
