"""Manage conftest.py marker plugin and tests directory in containers."""

__all__ = [
    "fsConftestPath",
    "fsConftestContent",
    "fsBuildConftestSource",
    "fnWriteConftestMarker",
    "fnEnsureTestsDirectory",
]

import posixpath


def fsConftestPath(sStepDirectory):
    """Return the conftest.py path for a step's tests directory."""
    return posixpath.join(sStepDirectory, "tests", "conftest.py")


def fsConftestContent(sProjectRepoPath=""):
    """Return the conftest.py marker plugin source for a project repo.

    When ``sProjectRepoPath`` is empty, returns the template body
    without its prologue — useful only for tests that inspect the
    template structure. Runtime callers (``fnWriteConftestMarker``)
    always pass a project-repo path so the generated file is
    self-contained.
    """
    if not sProjectRepoPath:
        return _CONFTEST_MARKER_TEMPLATE
    return fsBuildConftestSource(sProjectRepoPath)


def fsBuildConftestSource(sProjectRepoPath):
    """Return conftest.py source with a project-repo-aware prologue.

    Substitutes ``sProjectRepoPath`` into a small header that defines
    ``_PROJECT_REPO``, ``_MARKER_DIR``, and ``_WORKFLOWS_DIR``. The
    template body references those names without redefining them, so
    marker writes land at ``<sProjectRepoPath>/.vaibify/test_markers/``
    instead of the legacy workspace-rooted path. The ``!r``
    substitution produces a quoted Python literal and sidesteps the
    f-string/format-escape trap that affects the template body.
    """
    sPrologue = _S_CONFTEST_PROLOGUE_FORMAT.format(
        sProjectRepoPath=sProjectRepoPath,
    )
    return sPrologue + _CONFTEST_MARKER_TEMPLATE


def _fsAbsoluteStepDir(sStepDirectory, sProjectRepoPath):
    """Return container-absolute step dir for path ops in this module."""
    if not sStepDirectory or posixpath.isabs(sStepDirectory):
        return sStepDirectory
    if not sProjectRepoPath:
        return sStepDirectory
    return posixpath.join(sProjectRepoPath, sStepDirectory)


def fnWriteConftestMarker(
    connectionDocker, sContainerId, sStepDirectory, sProjectRepoPath,
):
    """Write the conftest.py marker plugin into a step's tests dir."""
    sAbsStepDir = _fsAbsoluteStepDir(sStepDirectory, sProjectRepoPath)
    sPath = fsConftestPath(sAbsStepDir)
    sSource = fsBuildConftestSource(sProjectRepoPath)
    connectionDocker.fnWriteFile(
        sContainerId, sPath, sSource.encode("utf-8"),
    )


def fnEnsureTestsDirectory(
    connectionDocker, sContainerId, sStepDirectory,
    sProjectRepoPath="",
):
    """Create the tests subdirectory in the container if missing."""
    from .pipelineRunner import fsShellQuote
    sAbsStepDir = _fsAbsoluteStepDir(sStepDirectory, sProjectRepoPath)
    sTestsDir = posixpath.join(sAbsStepDir, "tests")
    connectionDocker.ftResultExecuteCommand(
        sContainerId, f"mkdir -p {fsShellQuote(sTestsDir)}"
    )


_S_CONFTEST_PROLOGUE_FORMAT = (
    "from pathlib import Path\n"
    "_PROJECT_REPO = Path({sProjectRepoPath!r})\n"
    "_MARKER_DIR = _PROJECT_REPO / '.vaibify' / 'test_markers'\n"
    "_WORKFLOWS_DIR = _PROJECT_REPO / '.vaibify' / 'workflows'\n"
)


_CONFTEST_MARKER_TEMPLATE = '''\
"""Vaibify test result marker plugin.

Auto-generated by vaibify. Do not remove.
Writes a JSON result marker after every pytest session so the
dashboard can detect test outcomes regardless of how pytest was invoked.
Records git blob SHA1 digests of the step's output files so a fresh
clone can reconstruct staleness state.
"""

import hashlib
import json
import os
import time
from datetime import datetime, timezone

_CATEGORY_MAP = {
    "test_integrity": "integrity",
    "test_qualitative": "qualitative",
    "test_quantitative": "quantitative",
}


def _fsGetCategory(sNodeId):
    """Map a test node ID to a category name."""
    for sPrefix, sCategory in _CATEGORY_MAP.items():
        if sPrefix in sNodeId:
            return sCategory
    return "other"


def _fdictBuildCategoryResults(session):
    """Tally pass/fail counts per test category from session items."""
    dictCategories = {}
    for item in session.items:
        sCategory = _fsGetCategory(item.nodeid)
        dictCat = dictCategories.setdefault(
            sCategory, {"iPassed": 0, "iFailed": 0}
        )
        if not hasattr(item, "rep_call") or item.rep_call is None:
            continue
        if item.rep_call.passed:
            dictCat["iPassed"] += 1
        elif item.rep_call.failed:
            dictCat["iFailed"] += 1
    return dictCategories


def _fsStepDirRepoRel(sDir):
    """Return a step directory as a posix path relative to the project repo.

    Accepts container-absolute paths whose prefix matches
    ``_PROJECT_REPO`` (e.g. ``/workspace/GJ1132_XUV/step1``), legacy
    workspace-rooted paths, or already-relative paths. Produces a
    normalized repo-relative posix string so the workflow's
    repo-relative entries and the live ``__file__``-derived directory
    compare on equal footing.
    """
    if not sDir:
        return ""
    sNorm = os.path.normpath(sDir)
    sRepo = os.path.normpath(str(_PROJECT_REPO))
    if sNorm == sRepo:
        return ""
    if sNorm.startswith(sRepo + os.sep):
        sNorm = sNorm[len(sRepo) + 1:]
    elif sNorm.startswith("/"):
        sNorm = sNorm.lstrip("/")
    return sNorm.replace(os.sep, "/")


def _fsRepoRelFromFile(sFile, sStepDirRel):
    """Return a workflow's file entry as a repo-relative posix path."""
    sFilePosix = sFile.replace(os.sep, "/")
    sRepoPosix = str(_PROJECT_REPO).replace(os.sep, "/")
    if sFilePosix.startswith(sRepoPosix + "/"):
        return sFilePosix[len(sRepoPosix) + 1:]
    if sFilePosix.startswith("/"):
        return sFilePosix.lstrip("/")
    if sStepDirRel:
        sJoined = sStepDirRel + "/" + sFilePosix
    else:
        sJoined = sFilePosix
    return os.path.normpath(sJoined).replace(os.sep, "/")


def _flistStepOutputFiles(sStepDir):
    """Return repo-relative posix paths of the step's output files.

    Reads every workflow JSON under ``.vaibify/workflows`` and
    collects files from the step whose directory (repo-relative)
    matches sStepDir's repo-relative form. Duplicates are removed
    while order is preserved.
    """
    listResult = []
    setSeen = set()
    sWantedRel = _fsStepDirRepoRel(sStepDir)
    if not _WORKFLOWS_DIR.is_dir():
        return listResult
    for pathJson in sorted(_WORKFLOWS_DIR.glob("*.json")):
        try:
            dictWorkflow = json.loads(pathJson.read_text())
        except (OSError, ValueError):
            continue
        for dictStep in dictWorkflow.get("listSteps", []):
            sCandidateRel = _fsStepDirRepoRel(
                dictStep.get("sDirectory", "")
            )
            if sCandidateRel != sWantedRel:
                continue
            for sKey in ("saDataFiles", "saPlotFiles"):
                for sFile in dictStep.get(sKey, []):
                    if "{" in sFile:
                        continue
                    sRel = _fsRepoRelFromFile(sFile, sWantedRel)
                    if sRel and sRel not in setSeen:
                        listResult.append(sRel)
                        setSeen.add(sRel)
    return listResult


def _fsBlobSha(sHostPath):
    """Return the git-blob SHA1 for a file, or empty string on error."""
    try:
        with open(sHostPath, "rb") as handle:
            baContent = handle.read()
    except OSError:
        return ""
    sHeader = "blob " + str(len(baContent)) + chr(0)
    hasher = hashlib.sha1()
    hasher.update(sHeader.encode("utf-8"))
    hasher.update(baContent)
    return hasher.hexdigest()


def _fdictComputeOutputHashes(sStepDir):
    """Return {repo-rel-path: blob-sha} for the step's output files."""
    dictHashes = {}
    for sRel in _flistStepOutputFiles(sStepDir):
        sAbs = str(_PROJECT_REPO / sRel)
        sSha = _fsBlobSha(sAbs)
        if sSha:
            dictHashes[sRel] = sSha
    return dictHashes


def pytest_sessionfinish(session, exitstatus):
    """Write a JSON marker after every pytest run."""
    sStepDir = str(Path(__file__).resolve().parent.parent)
    sStepDirRel = _fsStepDirRepoRel(sStepDir)
    fNow = time.time()
    dictMarker = {
        "sDirectory": sStepDirRel,
        "iExitStatus": exitstatus,
        "fTimestamp": fNow,
        "sRunAtUtc": datetime.fromtimestamp(
            fNow, tz=timezone.utc,
        ).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "iCollected": session.testscollected,
        "dictCategories": _fdictBuildCategoryResults(session),
        "dictOutputHashes": _fdictComputeOutputHashes(sStepDir),
    }
    _MARKER_DIR.mkdir(parents=True, exist_ok=True)
    sFilename = sStepDirRel.replace("/", "_") + ".json"
    (_MARKER_DIR / sFilename).write_text(
        json.dumps(dictMarker, indent=2)
    )


import pytest

@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item, call):
    """Store the call report on the item for sessionfinish access."""
    outcome = yield
    if call.when == "call":
        item.rep_call = outcome.get_result()
'''
