"""Manage conftest.py marker plugin and tests directory in containers."""

import posixpath


def fsConftestPath(sStepDirectory):
    """Return the conftest.py path for a step's tests directory."""
    return posixpath.join(sStepDirectory, "tests", "conftest.py")


def fsConftestContent():
    """Return the conftest.py marker plugin source code."""
    return _CONFTEST_MARKER_TEMPLATE


def fnWriteConftestMarker(
    connectionDocker, sContainerId, sStepDirectory,
):
    """Write the conftest.py marker plugin into a step's tests dir."""
    sPath = fsConftestPath(sStepDirectory)
    connectionDocker.fnWriteFile(
        sContainerId, sPath,
        _CONFTEST_MARKER_TEMPLATE.encode("utf-8"),
    )


def fnEnsureTestsDirectory(connectionDocker, sContainerId, sStepDirectory):
    """Create the tests subdirectory in the container if missing."""
    from .pipelineRunner import fsShellQuote
    sTestsDir = posixpath.join(sStepDirectory, "tests")
    connectionDocker.ftResultExecuteCommand(
        sContainerId, f"mkdir -p {fsShellQuote(sTestsDir)}"
    )


_CONFTEST_MARKER_TEMPLATE = '''\
"""Vaibify test result marker plugin.

Auto-generated by vaibify. Do not remove.
Writes a JSON result marker after every pytest session so the
dashboard can detect test outcomes regardless of how pytest was invoked.
"""

import json
import os
import time
from pathlib import Path

_MARKER_DIR = Path("/workspace/.vaibify/test_markers")

_CATEGORY_MAP = {
    "test_integrity": "integrity",
    "test_qualitative": "qualitative",
    "test_quantitative": "quantitative",
}


def _fsStepDirToMarkerName(sStepDir):
    """Convert a step directory path to a safe marker filename."""
    return sStepDir.strip("/").replace("/", "_") + ".json"


def _fsGetCategory(sNodeId):
    """Map a test node ID to a category name."""
    for sPrefix, sCategory in _CATEGORY_MAP.items():
        if sPrefix in sNodeId:
            return sCategory
    return "other"


def _fdictBuildCategoryResults(session):
    """Tally pass/fail counts per test category from session items."""
    dictCategories = {}
    for item in session.items:
        sCategory = _fsGetCategory(item.nodeid)
        dictCat = dictCategories.setdefault(
            sCategory, {"iPassed": 0, "iFailed": 0}
        )
        if not hasattr(item, "rep_call") or item.rep_call is None:
            continue
        if item.rep_call.passed:
            dictCat["iPassed"] += 1
        elif item.rep_call.failed:
            dictCat["iFailed"] += 1
    return dictCategories


def pytest_sessionfinish(session, exitstatus):
    """Write a JSON marker after every pytest run."""
    sStepDir = str(Path(__file__).resolve().parent.parent)
    dictMarker = {
        "sDirectory": sStepDir,
        "iExitStatus": exitstatus,
        "fTimestamp": time.time(),
        "iCollected": session.testscollected,
        "dictCategories": _fdictBuildCategoryResults(session),
    }
    _MARKER_DIR.mkdir(parents=True, exist_ok=True)
    sFilename = _fsStepDirToMarkerName(sStepDir)
    (_MARKER_DIR / sFilename).write_text(
        json.dumps(dictMarker, indent=2)
    )


import pytest

@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item, call):
    """Store the call report on the item for sessionfinish access."""
    outcome = yield
    if call.when == "call":
        item.rep_call = outcome.get_result()
'''
