"""Manage deterministic test file templates and their content hashes."""

__all__ = [
    "fsQuantitativeTemplateHash",
    "fsIntegrityTemplateHash",
    "fsQualitativeTemplateHash",
    "fsBuildQuantitativeTestCode",
    "fsBuildIntegrityTestCode",
    "fsBuildQualitativeTestCode",
]

import hashlib
import re


def _fsComputeTemplateHash(sTemplate):
    """Strip any existing hash line, then SHA-256 the remainder."""
    sStripped = re.sub(
        r"^# vaibify-template-hash: [0-9a-f]+\n", "",
        sTemplate, count=1,
    )
    sDigest = hashlib.sha256(sStripped.encode("utf-8")).hexdigest()
    return sDigest[:16]


def _fsEmbedTemplateHash(sTemplate):
    """Prepend a template-hash comment as the second line."""
    sHash = _fsComputeTemplateHash(sTemplate)
    listLines = sTemplate.split("\n", 1)
    sFirstLine = listLines[0]
    sRest = listLines[1] if len(listLines) > 1 else ""
    return (
        sFirstLine + "\n"
        + f"# vaibify-template-hash: {sHash}\n"
        + sRest
    )


def _fbFileMatchesTemplate(
    connectionDocker, sContainerId, sFilePath, sTemplate,
):
    """Return True if the file is safe to overwrite."""
    from .llmInvoker import fsReadFileFromContainer
    sExisting = fsReadFileFromContainer(
        connectionDocker, sContainerId, sFilePath,
    )
    if not sExisting or not isinstance(sExisting, str):
        return True
    sExpectedHash = _fsComputeTemplateHash(sTemplate)
    matchHash = re.search(
        r"^# vaibify-template-hash: ([0-9a-f]+)",
        sExisting, re.MULTILINE,
    )
    if matchHash:
        return matchHash.group(1) == sExpectedHash
    sEmbedded = _fsEmbedTemplateHash(sTemplate)
    return sExisting.strip() == sEmbedded.strip()


def fsQuantitativeTemplateHash():
    """Return the current quantitative template hash."""
    return _fsComputeTemplateHash(fsBuildQuantitativeTestCode())


def fsIntegrityTemplateHash():
    """Return the current integrity template hash."""
    return _fsComputeTemplateHash(fsBuildIntegrityTestCode())


def fsQualitativeTemplateHash():
    """Return the current qualitative template hash."""
    return _fsComputeTemplateHash(fsBuildQualitativeTestCode())


_QUANTITATIVE_TEMPLATE_HEADER = \
    '"""Quantitative benchmark tests generated by vaibify."""\n\nimport pytest\n\n'

_QUANTITATIVE_TEMPLATE_FOOTER = '''

def _fdictLoadStandardsFile():
    """Load the quantitative standards JSON file."""
    sJsonPath = str(
        pathlib.Path(__file__).parent / "quantitative_standards.json"
    )
    with open(sJsonPath, encoding="utf-8") as fileHandle:
        return json.load(fileHandle)


_DICT_STANDARDS = _fdictLoadStandardsFile()
_F_DEFAULT_RTOL = _DICT_STANDARDS.get("fDefaultRtol", 1e-6)
_LIST_STANDARDS = _DICT_STANDARDS["listStandards"]
_STEP_DIRECTORY = str(pathlib.Path(__file__).parent.parent)


@pytest.mark.parametrize(
    "dictStandard",
    _LIST_STANDARDS,
    ids=[s["sName"] for s in _LIST_STANDARDS],
)
def test_quantitative_benchmark(dictStandard):
    """Compare output value against stored benchmark within tolerance."""
    fActual = _fLoadValue(
        dictStandard["sDataFile"],
        dictStandard["sAccessPath"],
        _STEP_DIRECTORY,
        sFormat=dictStandard.get("sFormat", ""),
    )
    fExpected = dictStandard["fValue"]
    fRtol = dictStandard.get("fRtol", _F_DEFAULT_RTOL)
    fAtol = dictStandard.get("fAtol", 1e-08)
    assert np.allclose(fActual, fExpected, rtol=fRtol, atol=fAtol), (
        f"{dictStandard[\'sName\']}: expected {fExpected}, got {fActual}"
    )
'''


def fsBuildQuantitativeTestCode():
    """Return the deterministic quantitative test file content."""
    from .dataLoaders import fsReadLoaderSource
    sLoaderSource = fsReadLoaderSource()
    sTemplate = (
        _QUANTITATIVE_TEMPLATE_HEADER
        + sLoaderSource
        + _QUANTITATIVE_TEMPLATE_FOOTER
    )
    return _fsEmbedTemplateHash(sTemplate)


_INTEGRITY_TEST_TEMPLATE = '''"""Integrity tests generated by vaibify."""

import json
import os
import pathlib

import numpy as np
import pytest

try:
    import h5py
except ImportError:
    h5py = None

try:
    import csv as csvModule
except ImportError:
    csvModule = None


def _fdictLoadIntegrityStandards():
    """Load the integrity standards JSON file."""
    sJsonPath = str(
        pathlib.Path(__file__).parent / "integrity_standards.json"
    )
    with open(sJsonPath, encoding="utf-8") as fileHandle:
        return json.load(fileHandle)


_DICT_STANDARDS = _fdictLoadIntegrityStandards()
_LIST_STANDARDS = _DICT_STANDARDS["listStandards"]
_STEP_DIRECTORY = str(pathlib.Path(__file__).parent.parent)


def _fnCheckFileExists(sFullPath):
    """Assert the file exists and is non-empty."""
    assert os.path.isfile(sFullPath), f"File not found: {sFullPath}"
    assert os.path.getsize(sFullPath) > 0, f"File is empty: {sFullPath}"


def _fnCheckShape(daData, tExpectedShape, sFullPath):
    """Assert the data array shape matches the expected shape."""
    if tExpectedShape is not None:
        assert list(daData.shape) == tExpectedShape, (
            f"{sFullPath}: expected shape {tExpectedShape}, "
            f"got {list(daData.shape)}"
        )


def _fnCheckNanInf(daData, bCheckNaN, bCheckInf, sFullPath):
    """Assert no NaN or Inf values in numeric data."""
    if not np.issubdtype(daData.dtype, np.number):
        return
    if bCheckNaN:
        assert not np.any(np.isnan(daData)), (
            f"{sFullPath}: contains NaN values"
        )
    if bCheckInf:
        assert not np.any(np.isinf(daData)), (
            f"{sFullPath}: contains Inf values"
        )


def _fnCheckNpy(sFullPath, dictStandard):
    """Validate a numpy .npy file."""
    daData = np.load(sFullPath, allow_pickle=False)
    tShape = dictStandard.get("tExpectedShape")
    _fnCheckShape(daData, tShape, sFullPath)
    _fnCheckNanInf(
        daData, dictStandard.get("bCheckNaN", False),
        dictStandard.get("bCheckInf", False), sFullPath,
    )


def _fnCheckNpz(sFullPath, dictStandard):
    """Validate a numpy .npz archive."""
    archiveNpz = np.load(sFullPath, allow_pickle=False)
    assert len(archiveNpz.files) > 0, f"{sFullPath}: empty npz archive"
    for sKey in archiveNpz.files:
        daData = archiveNpz[sKey]
        if np.issubdtype(daData.dtype, np.number):
            _fnCheckNanInf(
                daData, dictStandard.get("bCheckNaN", False),
                dictStandard.get("bCheckInf", False), sFullPath,
            )


def _fnCheckCsv(sFullPath, dictStandard):
    """Validate a CSV file."""
    import csv
    with open(sFullPath, newline="", encoding="utf-8") as fh:
        listRows = list(csv.DictReader(fh))
    tShape = dictStandard.get("tExpectedShape")
    if tShape is not None and len(tShape) >= 1:
        assert len(listRows) == tShape[0], (
            f"{sFullPath}: expected {tShape[0]} rows, got {len(listRows)}"
        )
    if dictStandard.get("bCheckNaN", False):
        for dictRow in listRows:
            for sVal in dictRow.values():
                try:
                    fVal = float(sVal)
                    assert not np.isnan(fVal), (
                        f"{sFullPath}: contains NaN"
                    )
                    if dictStandard.get("bCheckInf", False):
                        assert not np.isinf(fVal), (
                            f"{sFullPath}: contains Inf"
                        )
                except ValueError:
                    pass


def _fnCheckJson(sFullPath, dictStandard):
    """Validate a JSON file."""
    with open(sFullPath, encoding="utf-8") as fh:
        json.load(fh)


def _fnCheckHdf5(sFullPath, dictStandard):
    """Validate an HDF5 file."""
    assert h5py is not None, "h5py is not installed"
    with h5py.File(sFullPath, "r") as fh:
        assert len(fh.keys()) > 0, f"{sFullPath}: empty HDF5 file"
        if dictStandard.get("bCheckNaN", False):
            def fnCheckDataset(sName, obj):
                if isinstance(obj, h5py.Dataset):
                    daData = np.array(obj)
                    if np.issubdtype(daData.dtype, np.number):
                        _fnCheckNanInf(
                            daData, True,
                            dictStandard.get("bCheckInf", False),
                            sFullPath,
                        )
            fh.visititems(fnCheckDataset)


def _fnCheckWhitespace(sFullPath, dictStandard):
    """Validate a whitespace-delimited file."""
    with open(sFullPath, encoding="utf-8") as fh:
        listRows = [
            s for s in fh if s.strip()
            and not s.strip().startswith("#")
        ]
    tShape = dictStandard.get("tExpectedShape")
    if tShape is not None and len(tShape) >= 1:
        assert len(listRows) >= tShape[0], (
            f"{sFullPath}: expected >= {tShape[0]} rows"
        )
    if dictStandard.get("bCheckNaN", False):
        for sLine in listRows:
            for sToken in sLine.split():
                try:
                    fVal = float(sToken)
                    assert not np.isnan(fVal)
                    if dictStandard.get("bCheckInf", False):
                        assert not np.isinf(fVal)
                except ValueError:
                    pass


def _fnCheckKeyvalue(sFullPath, dictStandard):
    """Validate a key=value text file."""
    with open(sFullPath, encoding="utf-8") as fh:
        listLines = [s for s in fh if "=" in s]
    assert len(listLines) > 0, f"{sFullPath}: no key=value pairs"


def _fnCheckJsonl(sFullPath, dictStandard):
    """Validate a JSON Lines file."""
    import json as jsonMod
    with open(sFullPath, encoding="utf-8") as fh:
        listRecords = [jsonMod.loads(s) for s in fh if s.strip()]
    assert len(listRecords) > 0, f"{sFullPath}: empty JSONL"


def _fnCheckGenericText(sFullPath, dictStandard):
    """Validate a generic text file by checking it is non-empty."""
    with open(sFullPath, encoding="utf-8") as fh:
        sContent = fh.read()
    assert len(sContent.strip()) > 0, f"{sFullPath}: empty file"


_DICT_INTEGRITY_CHECKERS = {
    "npy": _fnCheckNpy,
    "npz": _fnCheckNpz,
    "csv": _fnCheckCsv,
    "json": _fnCheckJson,
    "hdf5": _fnCheckHdf5,
    "whitespace": _fnCheckWhitespace,
    "keyvalue": _fnCheckKeyvalue,
    "jsonl": _fnCheckJsonl,
}


def _fnDispatchIntegrityCheck(sFullPath, dictStandard):
    """Load and check the file using the appropriate format checker."""
    sFormat = dictStandard.get("sFormat", "")
    fnChecker = _DICT_INTEGRITY_CHECKERS.get(
        sFormat, _fnCheckGenericText,
    )
    fnChecker(sFullPath, dictStandard)


if not _LIST_STANDARDS:
    def test_no_integrity_outputs():
        """Placeholder when no data files are present."""
        assert True
else:
    @pytest.mark.parametrize(
        "dictStandard",
        _LIST_STANDARDS,
        ids=[s["sFileName"] for s in _LIST_STANDARDS],
    )
    def test_integrity_check(dictStandard):
        """Validate structural integrity of a data file."""
        sFullPath = os.path.join(
            _STEP_DIRECTORY, dictStandard["sFileName"],
        )
        _fnCheckFileExists(sFullPath)
        _fnDispatchIntegrityCheck(sFullPath, dictStandard)
'''


_QUALITATIVE_TEST_TEMPLATE = '''"""Qualitative tests generated by vaibify."""

import json
import os
import pathlib

import pytest


def _fdictLoadQualitativeStandards():
    """Load the qualitative standards JSON file."""
    sJsonPath = str(
        pathlib.Path(__file__).parent / "qualitative_standards.json"
    )
    with open(sJsonPath, encoding="utf-8") as fileHandle:
        return json.load(fileHandle)


_DICT_STANDARDS = _fdictLoadQualitativeStandards()
_LIST_STANDARDS = _DICT_STANDARDS["listStandards"]
_STEP_DIRECTORY = str(pathlib.Path(__file__).parent.parent)


def _flistLoadColumns(sFullPath, sFormat):
    """Load column names from a tabular or array file."""
    if sFormat == "npz":
        import numpy as np
        return list(np.load(sFullPath, allow_pickle=False).files)
    if sFormat in ("npy", "hdf5"):
        return []
    if sFormat == "csv":
        import csv
        with open(sFullPath, newline="", encoding="utf-8") as fh:
            reader = csv.DictReader(fh)
            return list(reader.fieldnames or [])
    with open(sFullPath, encoding="utf-8") as fh:
        return fh.readline().split()


def _flistLoadJsonKeys(sFullPath):
    """Load top-level keys from a JSON file."""
    with open(sFullPath, encoding="utf-8") as fh:
        dictData = json.load(fh)
    if isinstance(dictData, dict):
        return list(dictData.keys())
    return []


def _fnCheckExpectedColumns(sFullPath, sFormat, listExpected):
    """Assert all expected columns are present in the file."""
    if not listExpected:
        return
    listActual = _flistLoadColumns(sFullPath, sFormat)
    for sColumn in listExpected:
        assert sColumn in listActual, (
            f"{sFullPath}: missing column {sColumn!r}"
        )


def _fnCheckExpectedJsonKeys(sFullPath, listExpected):
    """Assert all expected JSON keys are present in the file."""
    if not listExpected:
        return
    listActual = _flistLoadJsonKeys(sFullPath)
    for sKey in listExpected:
        assert sKey in listActual, (
            f"{sFullPath}: missing JSON key {sKey!r}"
        )


if not _LIST_STANDARDS:
    def test_no_qualitative_outputs():
        """Placeholder when no qualitative checks are needed."""
        assert True
else:
    @pytest.mark.parametrize(
        "dictStandard",
        _LIST_STANDARDS,
        ids=[s["sFileName"] for s in _LIST_STANDARDS],
    )
    def test_qualitative_check(dictStandard):
        """Validate qualitative properties of a data file."""
        sFullPath = os.path.join(
            _STEP_DIRECTORY, dictStandard["sFileName"],
        )
        sFormat = dictStandard.get("sFormat", "")
        _fnCheckExpectedColumns(
            sFullPath, sFormat,
            dictStandard.get("listExpectedColumns", []),
        )
        _fnCheckExpectedJsonKeys(
            sFullPath,
            dictStandard.get("listExpectedJsonKeys", []),
        )
'''


def fsBuildIntegrityTestCode():
    """Return the deterministic integrity test file content."""
    return _fsEmbedTemplateHash(_INTEGRITY_TEST_TEMPLATE)


def fsBuildQualitativeTestCode():
    """Return the deterministic qualitative test file content."""
    return _fsEmbedTemplateHash(_QUALITATIVE_TEST_TEMPLATE)
